--- to be removed from final 
DELETE FROM PS_CIS_XPE_IMPORT WHERE CIS_STAGE NOT IN (
'BIL',
'MTC',
'ORI',
'OR2',
'RIM'
)
/
--- remove duplicates / previously processed rows
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_STAGE='DUP' WHERE
A.CIS_STAGE='RIM' AND EXISTS (SELECT 'X' FROM PS_CIS_XPE_IMPORT B WHERE
B.KEY1=A.KEY1 AND B.KEY2=A.KEY2 AND B.CIS_STAGE!='ORI' AND B.CIS_STAGE!='RIM' )
/
--- mark non-duplicates as transactions ready to be processed
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_STAGE='NEW' WHERE A.CIS_STAGE='RIM'
/
--- match error - not found facility to site mapping
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_STAGE='E01' WHERE A.CIS_STAGE='NEW'
AND NOT EXISTS (SELECT 'X' FROM XPE_DCC_CFG_PCS B 
WHERE B.SITE_ID=A.ATTR_VALUE8)
/
--- match site to facility
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_TARGTCUST1DET1 = (
SELECT MAX(B.FACILITY_ID) FROM XPE_DCC_CFG_PCS B
WHERE B.SITE_ID=A.ATTR_VALUE8), A.CIS_STAGE='M02'
WHERE A.CIS_STAGE='NEW'
/
--- match error - not found carrier mapping
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_STAGE='E02' WHERE A.CIS_STAGE='M02'
AND NOT EXISTS (SELECT 'X' FROM XPE_DCC_CFG_CARRIERS B 
WHERE B.CARRIER_ID=A.KEY3)
/
--- match carrier
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_TARGTCUST1DET2 = (
SELECT MAX(B.CARRIER_NAME) FROM XPE_DCC_CFG_CARRIERS  B
WHERE B.CARRIER_ID=A.KEY3), A.CIS_STAGE='M03'
WHERE A.CIS_STAGE='M02'
/
--- mark for material / uom conversion
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_STAGE='M04' WHERE 
A.CIS_STAGE='M03' AND A.ATTR_VALUE3 LIKE '%-%'
/
UPDATE PS_CIS_XPE_IMPORT A SET 
A.CIS_TARGTCUST1DET3=SUBSTR(A.ATTR_VALUE3, INSTR(A.ATTR_VALUE3, '-')+1, LENGTH(A.ATTR_VALUE3)-INSTR(A.ATTR_VALUE3, '-')),
A.CIS_TARGTCUST1DET4=SUBSTR(A.ATTR_VALUE3, 1, INSTR(A.ATTR_VALUE3, '-')-1), 
A.CIS_STAGE='M05' 
WHERE A.CIS_STAGE='M04'
/
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_STAGE='E02' WHERE A.CIS_STAGE='M04'
/
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_TARGTCUST1DET3 = '%', 
A.CIS_TARGTCUST1DET4=A.ATTR_VALUE3, A.CIS_STAGE='M05' WHERE A.CIS_STAGE='M03'
/
--- PC scales to cust id mapping
--- 180104 begin: I/O suffix removal from pcs id code
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_TARGTCUST2DET4=SUBSTR(A.CIS_TARGTCUST2DET1, LENGTH(A.CIS_TARGTCUST2DET1), 1) WHERE A.CIS_STAGE='M05'
/
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_TARGTCUST2DET1=SUBSTR(A.CIS_TARGTCUST2DET1, 0, LENGTH(A.CIS_TARGTCUST2DET1)-1)
WHERE A.CIS_STAGE='M05' AND A.CIS_TARGTCUST2DET4 IN ('I', 'i', 'O', 'o')
/
--- 180104 end : I/O suffix removal from pcs id code
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_STAGE='E04' WHERE A.CIS_STAGE='M05'
AND NOT EXISTS (SELECT 'X' FROM XPE_DCC_CFG_PCSSHORTNAMES B WHERE
A.CIS_TARGTCUST2DET1=B.PCSSHORTNAME_ID) AND A.CIS_STAGE='M05'
/
UPDATE PS_CIS_XPE_IMPORT A SET (A.CIS_TARGTCUST2DET2, A.CIS_TARGTCUST4DET1,
A.CIS_TARGTCUST4DET2, A.CIS_TARGET_VENDOR2, A.CIS_TARGET_VENDOR3)=
(SELECT MAX(B.PCSSHORT_NAME), MAX(B.COV_BILL_ID), MAX(B.COV_BILL_LOC_NUM), MAX(B.BILL_CYCLE_ID),
MAX(B.INV_SUPRESS)
FROM XPE_DCC_CFG_PCSSHORTNAMES B WHERE
A.CIS_TARGTCUST2DET1=B.PCSSHORTNAME_ID), A.CIS_STAGE='M06'
WHERE A.CIS_STAGE='M05'
/
--- contract / term / carrier line mapping
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_STAGE='E05' WHERE 
A.CIS_STAGE='M06' AND NOT EXISTS
(
SELECT 
C.XPE_PRICING_TERM_TYPE,
A.KEY2 AS TICKET_ID,
A.CIS_TARGTCUST2DET1 AS XPE_DCC_PCS_ID,
A.CIS_TARGTCUST2DET2 AS XPE_DCC_PCSNAME,
A.KEY3 AS CARRIER_ID,
A.CIS_TARGTCUST1DET2 AS XPE_CARRIER_NAME,
A.CIS_TARGTCUST1DET1 AS XPE_FACILITY,
A.CIS_TARGTCUST1DET3 AS XPE_PRODUCT_UOM,
A.CIS_TARGTCUST1DET4 AS XPE_PRODUCT_ID,
A.ATTR_VALUE8 AS SITE_ID,
E.XPE_CONTRACT_STATUS 
FROM 
--PS_CIS_XPE_IMPORT A,
XPE_DCC_CONTRACTS F,
XPE_DCC_CONTRACT_VERSION E,
XPE_DCC_CONTRACT_CARRIER B, 
XPE_DCC_CONTRACT_PRICING_TERM C,
XPE_DCC_CONTRACT_LINE D
WHERE
--- import to contract matching section
A.CIS_TARGTCUST2DET1 = F.XPE_DCC_PCSNAME
AND D.XPE_FACILITY = A.ATTR_VALUE8
AND B.XPE_CARRIER_ID = A.KEY3
AND D.XPE_PRODUCT_UOM = A.CIS_TARGTCUST1DET3 
AND D.XPE_PRODUCT_ID = A.CIS_TARGTCUST1DET4 
--- contract structure mapping section
AND B.XPE_CONTRACT_ID = C.XPE_CONTRACT_ID 
AND B.XPE_CONTRACT_VERSION = C.XPE_CONTRACT_VERSION 
AND B.XPE_CONTRACT_LINE = C.XPE_CONTRACT_LINE 
AND B.XPE_PRICING_TERM_LINE = C.XPE_PRICING_TERM_LINE 
AND C.XPE_CONTRACT_ID = D.XPE_CONTRACT_ID 
AND C.XPE_CONTRACT_VERSION = D.XPE_CONTRACT_VERSION 
AND C.XPE_CONTRACT_LINE = D.XPE_CONTRACT_LINE 
AND D.XPE_CONTRACT_ID = E.XPE_CONTRACT_ID 
AND D.XPE_CONTRACT_VERSION = E.XPE_CONTRACT_VERSION 
AND E.XPE_CONTRACT_ID = F.XPE_CONTRACT_ID 
--- other contract constraints
AND E.XPE_CONTRACT_STATUS = 'APR'
)
/
--- contract / carrier / pricing line parameters mapping - update section
--- 180104 - adding milestone, min / max criteria for non-RTE pricing methods
--- new version - allows for multiple RTEs pricing term rows and PLT/TIR
INSERT INTO PS_CIS_XPE_IMPORT (
PROCESSID,
CIS_PRCS_REQST_ID,
CIS_EXEC_PLAN_CODE,
CIS_EXEC_PLAN_STEP,
CIS_EXEC_DATE,
CIS_STAGE,
CIS_TRANS_IN_OUT,
CIS_BILLCYCLE_INFO,
KEY1,
KEY2,
KEY3,
KEY4,
KEY_DATE_01,
CIS_ORIG_CUSTID1,
TRANS_DT1,
CIS_TRANS_DT2,
CIS_TRANS_DT3,
CIS_TRANS_DT4,
CIS_TRANS_DT5,
ATTR_VALUE1,
ATTR_VALUE2,
ATTR_VALUE3,
ATTR_VALUE4,
ATTR_VALUE5,
ATTR_VALUE6,
ATTR_VALUE7,
ATTR_VALUE8,
QTY_1,
QTY_2,
QTY_3,
QTY_4,
QTY_5,
CIS_TARGTCUST2DET1,
CIS_TRANS_BI_AMT3,
CIS_TRANS_BI_AMT2,
CIS_TRANS_BI_AMT5,
CIS_TRANS_BI_AMT6,
CIS_TRANS_BI_AMT1,
CIS_ORIG_CUSTID2,
CIS_ORIG_CUSTID3,
CIS_TARGTCUST1DET1,
CIS_TARGTCUST1DET2,
CIS_TARGTCUST1DET3,
CIS_TARGTCUST1DET4,
CIS_TARGTCUST2DET2,
CIS_TARGTCUST2DET3,
CIS_TARGTCUST3DET2,
CIS_TARGTCUST3DET3,
CIS_TARGTCUST3DET4,
CIS_TARGTCUST3DET5,
CIS_TARGTCUST3DET1,
CIS_TRANS_AGGAMT10,
CIS_TARGTCUST4DET1,
CIS_TARGTCUST4DET2,
CIS_TARGTCUST4DET3,
CIS_TARGET_VENDOR4
) SELECT 
A.PROCESSID,
A.CIS_PRCS_REQST_ID,
'MLT-TERM',
B.XPE_PRICING_TERM_LINE,
A.CIS_EXEC_DATE,
'M07',
A.CIS_TRANS_IN_OUT,
A.CIS_BILLCYCLE_INFO,
A.KEY1,
A.KEY2,
A.KEY3,
A.KEY4,
A.KEY_DATE_01,
A.CIS_ORIG_CUSTID1,
A.TRANS_DT1,
A.CIS_TRANS_DT2,
A.CIS_TRANS_DT3,
A.CIS_TRANS_DT4,
A.CIS_TRANS_DT5,
A.ATTR_VALUE1,
A.ATTR_VALUE2,
A.ATTR_VALUE3,
A.ATTR_VALUE4,
A.ATTR_VALUE5,
A.ATTR_VALUE6,
A.ATTR_VALUE7,
A.ATTR_VALUE8,
A.QTY_1,
A.QTY_2,
A.QTY_3,
A.QTY_4,
A.QTY_5,
A.CIS_TARGTCUST2DET1,
A.CIS_TRANS_BI_AMT3,
A.CIS_TRANS_BI_AMT2,
C.XPE_CHARGE_OVER_MIN,
C.XPE_CHARGE_OVER_MAX,
C.XPE_RATE,
F.SETID,
F.CUST_ID,
A.CIS_TARGTCUST1DET1,
A.CIS_TARGTCUST1DET2,
A.CIS_TARGTCUST1DET3,
A.CIS_TARGTCUST1DET4,
A.CIS_TARGTCUST2DET2,
C.XPE_PRICING_TERM_TYPE,
B.XPE_CONTRACT_VERSION,
B.XPE_CONTRACT_LINE,
B.XPE_PRICING_TERM_LINE,
B.XPE_CARRIER_ID,
B.XPE_CONTRACT_ID,
A.CIS_TRANS_AGGAMT10,
A.CIS_TARGTCUST4DET1,
A.CIS_TARGTCUST4DET2,
E.XPE_ACCTG_OPTIONS_SET,
D.XPE_SW_APPR_NBR
FROM PS_CIS_XPE_IMPORT A, XPE_DCC_CONTRACT_CARRIER B, XPE_DCC_CONTRACT_PRICING_TERM C,
XPE_DCC_CONTRACT_LINE D, XPE_DCC_CONTRACT_VERSION E, XPE_DCC_CONTRACTS F
WHERE 
--- import to contract matching section
A.CIS_TARGTCUST2DET1 = F.XPE_DCC_PCSNAME
AND D.XPE_FACILITY = A.ATTR_VALUE8 --- A.CIS_TARGTCUST1DET1 
AND B.XPE_CARRIER_ID = A.KEY3
AND D.XPE_PRODUCT_UOM = A.CIS_TARGTCUST1DET3 
AND D.XPE_PRODUCT_ID = A.CIS_TARGTCUST1DET4 
--- contract structure mapping section
AND B.XPE_CONTRACT_ID = C.XPE_CONTRACT_ID 
AND B.XPE_CONTRACT_VERSION = C.XPE_CONTRACT_VERSION 
AND B.XPE_CONTRACT_LINE = C.XPE_CONTRACT_LINE 
AND B.XPE_PRICING_TERM_LINE = C.XPE_PRICING_TERM_LINE 
AND C.XPE_CONTRACT_ID = D.XPE_CONTRACT_ID 
AND C.XPE_CONTRACT_VERSION = D.XPE_CONTRACT_VERSION 
AND C.XPE_CONTRACT_LINE = D.XPE_CONTRACT_LINE 
AND D.XPE_CONTRACT_ID = E.XPE_CONTRACT_ID 
AND D.XPE_CONTRACT_VERSION = E.XPE_CONTRACT_VERSION 
AND E.XPE_CONTRACT_ID = F.XPE_CONTRACT_ID 
--- other contract constraints
AND E.XPE_CONTRACT_STATUS = 'APR'
AND A.CIS_STAGE='M06'
AND C.XPE_PRICING_TERM_TYPE IN ('RTE', 'TIR', 'PLT')
/
/* old version - deprecated
UPDATE PS_CIS_XPE_IMPORT A SET (A.CIS_TARGTCUST3DET1,
A.CIS_TARGTCUST3DET2,
A.CIS_TARGTCUST3DET3,
A.CIS_TARGTCUST3DET4,
A.CIS_TARGTCUST3DET5,
A.CIS_ORIG_CUSTID2,
A.CIS_ORIG_CUSTID3,
A.CIS_TARGTCUST2DET3,
A.CIS_TRANS_BI_AMT1,
A.CIS_TRANS_BI_AMT5,
A.CIS_TRANS_BI_AMT6) = (
SELECT B.XPE_CONTRACT_ID,
B.XPE_CONTRACT_VERSION,
B.XPE_CONTRACT_LINE,
B.XPE_PRICING_TERM_LINE,
B.XPE_CARRIER_ID,
F.SETID,
F.CUST_ID,
C.XPE_PRICING_TERM_TYPE,
C.XPE_RATE,
C.XPE_CHARGE_OVER_MIN,
C.XPE_CHARGE_OVER_MAX
FROM XPE_DCC_CONTRACT_CARRIER B, XPE_DCC_CONTRACT_PRICING_TERM C,
XPE_DCC_CONTRACT_LINE D, XPE_DCC_CONTRACT_VERSION E, XPE_DCC_CONTRACTS F
--- ,
--- PS_CIS_XPE_IMPORT A
WHERE 
--- current txn table selection
--- A.CIS_STAGE='M05' AND 
--- dcc contract structure joins
B.XPE_CONTRACT_ID = C.XPE_CONTRACT_ID AND
B.XPE_CONTRACT_VERSION = C.XPE_CONTRACT_VERSION AND
B.XPE_CONTRACT_LINE = C.XPE_CONTRACT_LINE AND
B.XPE_PRICING_TERM_LINE = C.XPE_PRICING_TERM_LINE AND
C.XPE_CONTRACT_ID = D.XPE_CONTRACT_ID AND
C.XPE_CONTRACT_VERSION = D.XPE_CONTRACT_VERSION AND
C.XPE_CONTRACT_LINE = D.XPE_CONTRACT_LINE AND
D.XPE_CONTRACT_ID = E.XPE_CONTRACT_ID AND
D.XPE_CONTRACT_VERSION = E.XPE_CONTRACT_VERSION AND
E.XPE_CONTRACT_ID = F.XPE_CONTRACT_ID AND 
--- txn table derived keys to contract structure mapping
F.XPE_DCC_PCSNAME = A.CIS_TARGTCUST2DET2 AND
B.XPE_CARRIER_ID = A.CIS_TARGTCUST1DET2 AND
D.XPE_FACILITY = A.CIS_TARGTCUST1DET1 AND 
D.XPE_PRODUCT_UOM = A.CIS_TARGTCUST1DET3 AND 
D.XPE_PRODUCT_ID = A.CIS_TARGTCUST1DET4 AND 
--- other contract constraints
E.XPE_CONTRACT_STATUS = 'APR'), A.CIS_STAGE='M07'
WHERE A.CIS_STAGE='M06'
*/
--- 180116 begin - charge id identification --- CIS_TARGTCUST5DETx series
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_STAGE = 'E20' WHERE A.CIS_STAGE='M07'
AND NOT EXISTS (
SELECT 'X' FROM XPE_DCC_CFG_PRODUCTSERVICE B
WHERE B.ITEM_ID=A.CIS_TARGTCUST1DET4 )
/
UPDATE PS_CIS_XPE_IMPORT A SET (A.CIS_TARGTCUST5DET1, A.CIS_TARGTCUST5DET2) = (
SELECT MAX(B.CLASS_TYPE), MAX(B.CLASS_ID) FROM XPE_DCC_CFG_PRODUCTSERVICE B
WHERE B.ITEM_ID=A.CIS_TARGTCUST1DET4) WHERE A.CIS_STAGE IN ( 'M07' )
/
UPDATE PS_CIS_XPE_IMPORT A SET (A.CIS_TARGTCUST5DET3, A.CIS_TARGTCUST5DET4, A.CIS_TARGTCUST5DET5) 
= 
(SELECT MAX(B.CHARGE_ID), MAX(B.PRODUCT_SERVICE_ID), MAX(B.ENTRY_TYPE)
FROM XPE_DCC_CFG_ACCOUNTING B
WHERE B.ACCOUNTING_CLASS = A.CIS_TARGTCUST5DET2)
WHERE A.CIS_STAGE IN ( 'M07'
--, 'BIL'
) AND A.CIS_TARGTCUST5DET1 = 'AC'
AND (A.CIS_TARGTCUST5DET1 IS NOT NULL AND A.CIS_TARGTCUST5DET2 IS NOT NULL)
/
--- SELECT A.CIS_TARGTCUST4DET3, A.CIS_TARGTCUST5DET3, A.CIS_TARGTCUST5DET4, A.CIS_TARGTCUST5DET5 FROM PS_CIS_XPE_IMPORT A WHERE A.CIS_STAGE='M07'
--- SELECT * FROM XPE_DCC_CFG_ACCOUNTING WHERE DEAL_CLASS='SPOT'
UPDATE PS_CIS_XPE_IMPORT A SET (A.CIS_TARGTCUST5DET3, A.CIS_TARGTCUST5DET4, A.CIS_TARGTCUST5DET5) 
= 
(SELECT MAX(B.CHARGE_ID), MAX(B.PRODUCT_SERVICE_ID), MAX(B.ENTRY_TYPE)
FROM XPE_DCC_CFG_ACCOUNTING B
WHERE B.DEAL_CLASS = A.CIS_TARGTCUST4DET3 AND B.PRODUCT_SERVICE_ID IS NULL)
WHERE A.CIS_STAGE IN ( 'M07'
-- , 'BIL'
) AND A.CIS_TARGTCUST5DET1 = 'DC'
AND (A.CIS_TARGTCUST5DET1 IS NOT NULL AND A.CIS_TARGTCUST4DET3 IS NOT NULL)
/
--- MC to be added
/*
UPDATE PS_CIS_XPE_IMPORT A SET (A.CIS_TARGTCUST5DET3, A.CIS_TARGTCUST5DET4) 
= 
(SELECT MAX(B.CHARGE_ID), MAX(B.PRODUCT_SERVICE_ID) 
FROM XPE_DCC_CFG_ACCOUNTING B
WHERE B.MATERIAL_CATEGORY = A.CIS_TARGTCUST5DET2)
WHERE A.CIS_STAGE IN ( 'M07') AND A.CIS_TARGTCUST5DET1 = 'MC'
AND (A.CIS_TARGTCUST5DET1 IS NOT NULL AND A.CIS_TARGTCUST5DET2 IS NOT NULL)
/ 
*/
--- 180116 end - charge id identification --- CIS_TARGTCUST5DETx series
--- finish mapping section
INSERT INTO XPE_DCC_PLATFORM_EVENT
(XPE_CONTRACT_ID,   
XPE_CONTRACT_VERSION,
XPE_CONTRACT_LINE,
XPE_PRICING_TERM_LINE,
XPE_CARRIER_ID,
XPE_VEHICLE_TYPE,
XPE_SUB_NBR,
XPE_VEHICLE_NBR,
XPE_EVENT_DTTM,
XPE_EVENT_NBR,
XPE_EVENT_TYPE,
XPE_EVENT_REF,
XPE_EVENT_UOM,
-- XPE_EVENT_QTY,
COLUMN1)
SELECT A.CIS_TARGTCUST3DET1,
A.CIS_TARGTCUST3DET2,
A.CIS_TARGTCUST3DET3,
A.CIS_TARGTCUST3DET4,
A.KEY3,
'UNK',
1,
A.CIS_ORIG_CUSTID1,
A.KEY_DATE_01,
A.KEY2,
'SCI',
A.KEY2,
A.CIS_TARGTCUST1DET3,
-- A.QTY_5, 
'U'
FROM PS_CIS_XPE_IMPORT A WHERE A.CIS_STAGE='M06'
AND A.CIS_TARGTCUST3DET1 IS NOT NULL
/
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_STAGE='MTC' WHERE A.CIS_STAGE='M06'
/

---SELECT * FROM PS_CIS_XPE_IMPORT A  WHERE A.CIS_STAGE='MTC'

UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_STAGE='RDY' WHERE A.CIS_STAGE='M07'
/
--- begin: 180104 tier and plateau deals
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_STAGE='TAP' WHERE A.CIS_STAGE='RDY' 
AND A.CIS_TARGTCUST2DET3 IN ('TIR', 'PLT')
/
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_STAGE='IGT' WHERE A.CIS_STAGE='TAP' 
AND A.QTY_5<A.CIS_TRANS_BI_AMT5
/
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_TRANS_BI_AMT7=(
SELECT MIN(B.CIS_TRANS_BI_AMT5) FROM PS_CIS_XPE_IMPORT B
WHERE
A.PROCESSID=B.PROCESSID
AND A.CIS_PRCS_REQST_ID=B.CIS_PRCS_REQST_ID
AND A.CIS_EXEC_PLAN_CODE=B.CIS_EXEC_PLAN_CODE
AND A.CIS_TARGTCUST3DET2=B.CIS_TARGTCUST3DET2
AND A.CIS_TARGTCUST3DET3=B.CIS_TARGTCUST3DET3
AND A.CIS_TARGTCUST3DET1=B.CIS_TARGTCUST3DET1
AND A.CIS_STAGE=B.CIS_STAGE)
WHERE A.CIS_STAGE='TAP'
/
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_STAGE='TP1'
WHERE A.CIS_STAGE='TAP' AND A.CIS_TRANS_BI_AMT5=A.CIS_TRANS_BI_AMT7
/
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_STAGE='IGN'
WHERE A.CIS_STAGE='TAP' 
/
--- shortcut - add conversion / pre-built amount to plateau
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_STAGE='SLP'
WHERE A.CIS_STAGE='TP1' 
/
--- end: 180104 tier and plateau deals
--- single line pricing marking
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_STAGE='SLP' WHERE A.CIS_STAGE='RDY' 
AND A.CIS_TARGTCUST2DET3='RTE' AND (A.CIS_TRANS_BI_AMT6 IS NULL OR A.CIS_TRANS_BI_AMT6=0.00)
/
--- single line pricing with penalty marking
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_STAGE='PEN' WHERE A.CIS_STAGE='RDY' 
AND A.CIS_TARGTCUST2DET3='RTE' AND A.CIS_TRANS_BI_AMT6 IS NOT NULL AND A.CIS_TRANS_BI_AMT6>0.00
/
--- commit point 180107 947 
--- single rate price calc
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_TRANS_BI_AMT2=
ROUND(A.CIS_TRANS_BI_AMT1*A.QTY_5, 2), A.CIS_EXEC_PLAN_CODE='PRC-SLP99',
A.CIS_TRANS_BI_AMT3=A.QTY_5,
A.CIS_STAGE='PRC' WHERE A.CIS_STAGE='SLP'
/
--- 180104 begin: single rate price with penalty calc
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_TRANS_BI_AMT2=
ROUND(A.CIS_TRANS_BI_AMT1*A.QTY_5, 2), A.CIS_EXEC_PLAN_CODE='PRC-PEN01',
A.CIS_TRANS_BI_AMT3=A.QTY_5,
A.CIS_STAGE='PN1' WHERE A.CIS_STAGE='PEN'
/
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_STAGE='PRC' WHERE A.CIS_STAGE='PN1'
AND A.CIS_TRANS_BI_AMT2 >= A.CIS_TRANS_BI_AMT6
/
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_STAGE='PN3', A.CIS_TRANS_BI_AMT7=A.CIS_TRANS_BI_AMT6-A.CIS_TRANS_BI_AMT2
WHERE A.CIS_STAGE='PN1'
/
--- penalty insert begin
INSERT INTO PS_CIS_XPE_IMPORT (
PROCESSID,
CIS_PRCS_REQST_ID,
CIS_EXEC_PLAN_CODE,
CIS_EXEC_PLAN_STEP,
CIS_EXEC_DATE,
CIS_STAGE,
CIS_TRANS_IN_OUT,
CIS_BILLCYCLE_INFO,
KEY1,
KEY2,
KEY3,
KEY4,
KEY_DATE_01,
CIS_ORIG_CUSTID1,
TRANS_DT1,
CIS_TRANS_DT2,
CIS_TRANS_DT3,
CIS_TRANS_DT4,
CIS_TRANS_DT5,
ATTR_VALUE1,
ATTR_VALUE2,
ATTR_VALUE3,
ATTR_VALUE4,
ATTR_VALUE5,
ATTR_VALUE6,
ATTR_VALUE7,
ATTR_VALUE8,
QTY_1,
QTY_2,
QTY_3,
QTY_4,
QTY_5,
CIS_TARGTCUST2DET1,
CIS_TRANS_BI_AMT3,
CIS_TRANS_BI_AMT2,
CIS_TRANS_BI_AMT1,
--- attributes derived earlier
CIS_ORIG_CUSTID2,
CIS_ORIG_CUSTID3,
CIS_TARGTCUST1DET1,
CIS_TARGTCUST1DET2,
CIS_TARGTCUST1DET3,
CIS_TARGTCUST1DET4,
CIS_TARGTCUST2DET2,
CIS_TARGTCUST2DET3,
CIS_TARGTCUST3DET2,
CIS_TARGTCUST3DET3,
CIS_TARGTCUST3DET4,
CIS_TARGTCUST3DET5,
CIS_TARGTCUST3DET1,
CIS_TRANS_AGGAMT10,
CIS_TARGTCUST4DET1,
CIS_TARGTCUST4DET2,
CIS_TARGTCUST4DET3,
CIS_TARGTCUST5DET3, 
CIS_TARGTCUST5DET4,
CIS_TARGTCUST5DET5,
CIS_TARGET_VENDOR4
)
SELECT
A.PROCESSID,
A.CIS_PRCS_REQST_ID,
'PRC-PEN03',
A.CIS_EXEC_PLAN_STEP || '-P',
A.CIS_EXEC_DATE,
'PN4',
A.CIS_TRANS_IN_OUT,
A.CIS_BILLCYCLE_INFO,
A.KEY1,
A.KEY2,
A.KEY3,
A.KEY4,
A.KEY_DATE_01,
A.CIS_ORIG_CUSTID1,
A.TRANS_DT1,
A.CIS_TRANS_DT2,
A.CIS_TRANS_DT3,
A.CIS_TRANS_DT4,
A.CIS_TRANS_DT5,
A.ATTR_VALUE1,
A.ATTR_VALUE2,
A.ATTR_VALUE3,
A.ATTR_VALUE4,
A.ATTR_VALUE5,
A.ATTR_VALUE6,
A.ATTR_VALUE7,
A.ATTR_VALUE8,
A.QTY_1,
A.QTY_2,
A.QTY_3,
A.QTY_4,
A.QTY_5,
A.CIS_TARGTCUST2DET1,
A.CIS_TRANS_BI_AMT2,
A.CIS_TRANS_BI_AMT7 ,
A.CIS_TRANS_BI_AMT1,
--- attributes derived earlier
A.CIS_ORIG_CUSTID2,
A.CIS_ORIG_CUSTID3,
A.CIS_TARGTCUST1DET1,
A.CIS_TARGTCUST1DET2,
A.CIS_TARGTCUST1DET3,
A.CIS_TARGTCUST1DET4,
A.CIS_TARGTCUST2DET2,
A.CIS_TARGTCUST2DET3,
A.CIS_TARGTCUST3DET2,
A.CIS_TARGTCUST3DET3,
A.CIS_TARGTCUST3DET4,
A.CIS_TARGTCUST3DET5,
A.CIS_TARGTCUST3DET1,
A.CIS_TRANS_AGGAMT10,
A.CIS_TARGTCUST4DET1,
A.CIS_TARGTCUST4DET2,
A.CIS_TARGTCUST4DET3,
A.CIS_TARGTCUST5DET3, 
A.CIS_TARGTCUST5DET4, 
A.CIS_TARGTCUST5DET5,
A.CIS_TARGET_VENDOR4
FROM PS_CIS_XPE_IMPORT A
WHERE A.CIS_STAGE='PN3' 
/
--- penalty insert end
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_STAGE='PRC'
WHERE A.CIS_STAGE IN ('PN3','PN4')
/
--- commit 180107 1018am
--- 180104 end: single rate price with penalty calc
--- derived calculations: line-based surcharge (percentage)
INSERT INTO PS_CIS_XPE_IMPORT (
PROCESSID,
CIS_PRCS_REQST_ID,
CIS_EXEC_PLAN_CODE,
CIS_EXEC_PLAN_STEP,
CIS_EXEC_DATE,
CIS_STAGE,
CIS_TRANS_IN_OUT,
CIS_BILLCYCLE_INFO,
KEY1,
KEY2,
KEY3,
KEY4,
KEY_DATE_01,
CIS_ORIG_CUSTID1,
TRANS_DT1,
CIS_TRANS_DT2,
CIS_TRANS_DT3,
CIS_TRANS_DT4,
CIS_TRANS_DT5,
ATTR_VALUE1,
ATTR_VALUE2,
ATTR_VALUE3,
ATTR_VALUE4,
ATTR_VALUE5,
ATTR_VALUE6,
ATTR_VALUE7,
ATTR_VALUE8,
QTY_1,
QTY_2,
QTY_3,
QTY_4,
QTY_5,
CIS_TARGTCUST2DET1,
CIS_TRANS_BI_AMT3,
CIS_TRANS_BI_AMT2,
CIS_TRANS_BI_AMT1,
--- attributes derived earlier
CIS_ORIG_CUSTID2,
CIS_ORIG_CUSTID3,
CIS_TARGTCUST1DET1,
CIS_TARGTCUST1DET2,
CIS_TARGTCUST1DET3,
CIS_TARGTCUST1DET4,
CIS_TARGTCUST2DET2,
CIS_TARGTCUST2DET3,
CIS_TARGTCUST3DET2,
CIS_TARGTCUST3DET3,
CIS_TARGTCUST3DET4,
CIS_TARGTCUST3DET5,
CIS_TARGTCUST3DET1,
CIS_TRANS_AGGAMT10,
CIS_TARGTCUST4DET1,
CIS_TARGTCUST4DET2,
CIS_TARGTCUST4DET3,
CIS_TARGTCUST5DET3, 
CIS_TARGTCUST5DET4, 
CIS_TARGTCUST5DET5,
CIS_TARGET_VENDOR4
)
SELECT
1,
1,
'DRV-FEE-LQT01',
'DRV-' || C.XPE_PRICING_TERM_LINE,
A.CIS_EXEC_DATE,
'DRV',
A.CIS_TRANS_IN_OUT,
A.CIS_BILLCYCLE_INFO,
A.KEY1,
A.KEY2,
A.KEY3,
A.KEY4,
A.KEY_DATE_01,
A.CIS_ORIG_CUSTID1,
A.TRANS_DT1,
A.CIS_TRANS_DT2,
A.CIS_TRANS_DT3,
A.CIS_TRANS_DT4,
A.CIS_TRANS_DT5,
A.ATTR_VALUE1,
A.ATTR_VALUE2,
A.ATTR_VALUE3,
A.ATTR_VALUE4,
A.ATTR_VALUE5,
A.ATTR_VALUE6,
A.ATTR_VALUE7,
A.ATTR_VALUE8,
A.QTY_1,
A.QTY_2,
A.QTY_3,
A.QTY_4,
A.QTY_5,
A.CIS_TARGTCUST2DET1,
A.CIS_TRANS_BI_AMT2,
ROUND ( A.CIS_TRANS_BI_AMT2 * (C.XPE_RATE/100) , 2) ,
C.XPE_RATE,
--- attributes derived earlier
A.CIS_ORIG_CUSTID2,
A.CIS_ORIG_CUSTID3,
A.CIS_TARGTCUST1DET1,
A.CIS_TARGTCUST1DET2,
A.CIS_TARGTCUST1DET3,
A.CIS_TARGTCUST1DET4,
A.CIS_TARGTCUST2DET2,
A.CIS_TARGTCUST2DET3,
A.CIS_TARGTCUST3DET2,
A.CIS_TARGTCUST3DET3,
A.CIS_TARGTCUST3DET4,
A.CIS_TARGTCUST3DET5,
A.CIS_TARGTCUST3DET1,
A.CIS_TRANS_AGGAMT10,
A.CIS_TARGTCUST4DET1,
A.CIS_TARGTCUST4DET2,
A.CIS_TARGTCUST4DET3,
A.CIS_TARGTCUST5DET3, 
A.CIS_TARGTCUST5DET4, 
A.CIS_TARGTCUST5DET5,
A.CIS_TARGET_VENDOR4
FROM PS_CIS_XPE_IMPORT A, 
XPE_DCC_CONTRACT_PRICING_TERM C,
XPE_DCC_CONTRACT_LINE D, XPE_DCC_CONTRACT_VERSION E, XPE_DCC_CONTRACTS F
WHERE A.CIS_STAGE='PRC' AND 
C.XPE_CONTRACT_ID = A.CIS_TARGTCUST3DET1 AND 
C.XPE_CONTRACT_VERSION = A.CIS_TARGTCUST3DET2 AND
C.XPE_CONTRACT_LINE = A.CIS_TARGTCUST3DET3 AND 
-- B.XPE_PRICING_TERM_LINE = A.CIS_TARGTCUST3DET3 AND
C.XPE_PRICING_TERM_TYPE = 'FEE'
AND C.XPE_PERIOD_TYPE IN (
'LQT',
'TQT',
'EVE'
) AND 
--- dcc contract structure joins
C.XPE_CONTRACT_ID = D.XPE_CONTRACT_ID AND
C.XPE_CONTRACT_VERSION = D.XPE_CONTRACT_VERSION AND
C.XPE_CONTRACT_LINE = D.XPE_CONTRACT_LINE AND
D.XPE_CONTRACT_ID = E.XPE_CONTRACT_ID AND
D.XPE_CONTRACT_VERSION = E.XPE_CONTRACT_VERSION AND
E.XPE_CONTRACT_ID = F.XPE_CONTRACT_ID AND 
--- other contract constraints
E.XPE_CONTRACT_STATUS = 'APR'
/
--- defaults prior to interface insert
UPDATE PS_CIS_XPE_IMPORT A SET (A.ATTR_VALUE1, A.ATTR_VALUE2, A.ATTR_VALUE3)=
(SELECT MAX(B.DESCR), MAX(B.UNIT_OF_MEASURE), MAX(B.DST_ID) FROM SYSADM.PS_BI_CHARGE B
WHERE B.SETID='MASTR' AND B.CHARGE_ID = A.CIS_TARGTCUST5DET3
AND B.EFF_STATUS = 'A') WHERE A.CIS_STAGE IN ('PRC', 
'DRV') AND A.CIS_TARGTCUST5DET3 IS NOT NULL
/
UPDATE PS_CIS_XPE_IMPORT A SET A.ATTR_VALUE4 = SUBSTR(A.ATTR_VALUE3, 4, 6)
WHERE A.ATTR_VALUE3 LIKE 'REV-%' AND A.CIS_STAGE IN ('PRC', 
'DRV') AND A.ATTR_VALUE3 IS NOT NULL
/
UPDATE PS_CIS_XPE_IMPORT A SET 
A.BUSINESS_UNIT_CA=' ',
A.CONTRACT_NUM=' ',
A.CONTRACT_TYPE=' ',
A.CONTRACT_LINE_NUM=0,
A.BUSINESS_UNIT_PC=' ',
A.PROJECT_ID=' ',
A.ACTIVITY_ID=' ',
A.RESOURCE_ID=' ',
A.PROCESS_FLAG=' ',
A.CHARTFIELD1=' ',
A.CHARTFIELD2=' ',
A.CHARTFIELD3=' ',
A.ERROR_MESSAGE=' ',
A.VCHR_BLD_KEY_C1=' ',
A.VCHR_BLD_KEY_C2=' ',
A.VCHR_BLD_KEY_N1=0,
A.VCHR_BLD_KEY_N2=0,
A.VOUCHER_ID=' ',
A.VOUCHER_LINE_NUM=0,
A.RUN_TYPE=' ',
A.CIS_STAGE='F01'
WHERE A.CIS_STAGE IN ('PRC', 
'DRV')
/
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_STAGE='E60' WHERE A.CIS_STAGE IN ('FIN', 'F01')
AND NOT EXISTS
(SELECT 'X' FROM XPE_DCC_CONTRACT_LINE C WHERE 
C.XPE_CONTRACT_ID = A.CIS_TARGTCUST3DET1 AND 
C.XPE_CONTRACT_VERSION = A.CIS_TARGTCUST3DET2 AND
C.XPE_CONTRACT_LINE = A.CIS_TARGTCUST3DET3 
)
/
--SELECT C.BUSINESS_UNIT_GL, C.XPE_FACILITY, A.CIS_TARGTCUST4DET3 FROM PS_CIS_XPE_IMPORT A, XPE_DCC_CONTRACT_LINE C
--WHERE A.CIS_STAGE='FIN' 
--AND C.XPE_CONTRACT_ID = A.CIS_TARGTCUST3DET1 AND 
--C.XPE_CONTRACT_VERSION = A.CIS_TARGTCUST3DET2 AND
--C.XPE_CONTRACT_LINE = A.CIS_TARGTCUST3DET3 
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_STAGE='F10', (A.CIS_CHARTFIELD_4, A.CIS_CHARTFIELD_5) = 
(
SELECT C.BUSINESS_UNIT_GL, C.XPE_FACILITY FROM XPE_DCC_CONTRACT_LINE C
WHERE 
C.XPE_CONTRACT_ID = A.CIS_TARGTCUST3DET1 AND 
C.XPE_CONTRACT_VERSION = A.CIS_TARGTCUST3DET2 AND
C.XPE_CONTRACT_LINE = A.CIS_TARGTCUST3DET3 )
WHERE A.CIS_STAGE IN ('FIN', 'F01')
/
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_STAGE='F20' WHERE A.CIS_STAGE='F10'
AND EXISTS (
SELECT 'X' FROM XPE_DCC_CFG_BUSINESSUNIT B 
WHERE B.BUSINESS_UNIT=A.CIS_CHARTFIELD_4 AND B.SITE_ID=A.CIS_CHARTFIELD_5
AND B.ACCOUNTING_CLASS=A.CIS_TARGTCUST4DET3
)
/
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_STAGE='F21' WHERE A.CIS_STAGE='F10'
AND EXISTS (
SELECT 'X' FROM XPE_DCC_CFG_BUSINESSUNIT B 
WHERE B.BUSINESS_UNIT=A.CIS_CHARTFIELD_4 AND B.SITE_ID=A.CIS_CHARTFIELD_5
)
/
UPDATE PS_CIS_XPE_IMPORT SET CIS_STAGE='E65' WHERE CIS_STAGE IN ('FIN', 'F01')
/
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_STAGE='F30', (CIS_CHARTFIELD_6, CIS_CHARTFIELD_7, CIS_CHARTFIELD_8, CIS_CHARTFIELD_9, CIS_CHARTFIELD_10) = 
(
SELECT MAX(B.BILLING_BUSINESS_UNIT), MAX(B.BUSINESS_UNIT_REF), MAX(B.GL_BUSINESS_UNIT), MAX(B.AFFLIATE), MAX(B.OPERATING_UNIT)
FROM XPE_DCC_CFG_BUSINESSUNIT B 
WHERE B.BUSINESS_UNIT=A.CIS_CHARTFIELD_4 AND B.SITE_ID=A.CIS_CHARTFIELD_5
AND B.ACCOUNTING_CLASS=A.CIS_TARGTCUST4DET3
) WHERE A.CIS_STAGE='F20' 
/

UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_STAGE='F30', (CIS_CHARTFIELD_6, CIS_CHARTFIELD_7, CIS_CHARTFIELD_8, CIS_CHARTFIELD_9, CIS_CHARTFIELD_10) = 
(
SELECT B.BILLING_BUSINESS_UNIT, B.BUSINESS_UNIT_REF, B.GL_BUSINESS_UNIT, B.AFFLIATE, B.OPERATING_UNIT 
FROM XPE_DCC_CFG_BUSINESSUNIT B 
WHERE B.BUSINESS_UNIT=A.CIS_CHARTFIELD_4 AND B.SITE_ID=A.CIS_CHARTFIELD_5
) WHERE A.CIS_STAGE='F21' 
/
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_STAGE='E62' WHERE A.CIS_STAGE='F30'
AND NOT EXISTS (SELECT MAX(B.ACCOUNT) FROM PS_DST_CODE_TBL B WHERE B.SETID='MASTR'
AND B.DST_ID=A.ATTR_VALUE3 AND B.EFF_STATUS='A' AND B.DST_USE='REV' )
/
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_STAGE='F31', A.CIS_TARGET_VENDOR1=
(SELECT MAX(B.ACCOUNT) FROM PS_DST_CODE_TBL B WHERE B.SETID='MASTR'
AND B.DST_ID=A.ATTR_VALUE3 AND B.EFF_STATUS='A' AND B.DST_USE='REV' )
WHERE A.CIS_STAGE='F30'
/
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_STAGE='STA' WHERE A.CIS_TARGET_VENDOR3='Y' AND A.CIS_STAGE='F31'
/
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_CHARTFIELD_10 = ' ' WHERE A.CIS_STAGE='F31' AND A.CIS_CHARTFIELD_10 IS NULL
/
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_CHARTFIELD_9 = ' ' WHERE A.CIS_STAGE='F31' AND A.CIS_CHARTFIELD_9 IS NULL
/
UPDATE PS_CIS_XPE_IMPORT SET CIS_STAGE='FIN' WHERE CIS_STAGE='F31'
/
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_STAGE='STA' WHERE A.CIS_TARGET_VENDOR3='Y' AND A.CIS_STAGE='F31'
/
--- interface id assignment
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_TRANS_AGGAMT10=(
SELECT MAX(B.MAXINTFC)+98700000 FROM XPE_DCC_CFG_MAXINTF B WHERE B.TYPE='BI_INTFCT'
) WHERE A.CIS_STAGE='FIN'
/
UPDATE XPE_DCC_CFG_MAXINTF B SET B.MAXINTFC=B.MAXINTFC+1 WHERE B.TYPE='BI_INTFCT'
/
---- INTFC_BI insert
INSERT INTO PS_INTFC_BI (INTFC_ID 
 , INTFC_LINE_NUM 
 , TRANS_TYPE_BI 
 , TRANS_TYPE_BI_SEQ 
 , HDR_FIELDS_KEY 
 , HDR_FIELDS_BILL_BY 
 , ADJ_TRANS_TYPE 
 , CREATE_NEW_BILL 
 , TMP_BILL_FLG 
 , ENTRY_TYPE 
 , ENTRY_REASON 
 , ENTRY_EVENT 
 , LOAD_STATUS_BI 
 , ERROR_STATUS_BI 
 , BUSINESS_UNIT 
 , BUSINESS_UNIT_GL 
 , BILL_TO_CUST_ID 
 , ADDRESS_SEQ_NUM 
 , BILL_TO_COPIES 
 , CNTCT_SEQ_NUM 
 , NAME1 
 , INTERUNIT_FLG 
 , BUSINESS_UNIT_TO 
 , DIRECT_INVOICING 
 , RANGE_SELECTION_ID 
 , BILL_SOURCE_ID 
 , BILL_TYPE_ID 
 , BILL_CYCLE_ID 
 , BILL_BY_ID 
 , PAYMENT_METHOD 
 , PYMNT_TERMS_CD 
 , BANK_CD 
 , BANK_ACCT_KEY 
 , BI_CURRENCY_CD 
 , BASE_CURRENCY 
 , CUR_RT_TYPE 
 , RATE_MULT 
 , RATE_DIV 
 , CUR_RT_SOURCE 
 , INVOICE_DT 
 , ACCOUNTING_DT 
 , ACCRUE_UNBILLED 
 , TARGET_INVOICE 
 , INVOICE 
 , DOC_TYPE 
 , CONSOL_SETID 
 , CONSOL_CUST_ID 
 , CONSOL_KEY 
 , INVOICE_TO_ADJ 
 , ADJ_DELTA_ACTION 
 , LINE_SEQ_TO_ADJ 
 , LINE_SEQ_NUM 
 , LINE_DST_SEQ_NUM 
 , LINE_DFR_SEQ_NUM 
 , LINE_UAR_SEQ_NUM 
 , LAST_NOTE_SEQ_NUM 
 , NOTES_SEQ_NUM 
 , LINE_TYPE 
 , IDENTIFIER 
 , DESCR 
 , UNIT_OF_MEASURE 
 , QTY 
 , ORIG_QTY 
 , UNIT_AMT 
 , LIST_PRICE 
 , PPRC_PROMO_CD 
 , MERCH_TYPE 
 , TAX_CD 
 , TAX_EXEMPT_CERT 
 , TAX_EXEMPT_FLG 
 , TAX_EXEMPT_RC 
 , TAX_JOB_NUM 
 , BI_TAX_TIMING 
 , CUSTOMER_GROUP 
 , VAT_TXN_TYPE_CD 
 , TAX_CD_VAT 
 , VAT_APPLICABILITY 
 , VAT_PRODUCT_GROUP 
 , PROD_GRP_SETID 
 , IST_TXN_FLG 
 , IDENTIFIER_TBL 
 , SHIP_FROM_LOC 
 , ORD_ACCEPT_LOC 
 , ORD_ORIGIN_LOC 
 , STORE_LOC 
 , TITLE_PASSAGE 
 , TAX_GROUP 
 , TAX_USER_AREA 
 , TAX_TRANS_TYPE 
 , TAX_TRANS_SUB_TYPE 
 , NET_EXTENDED_AMT 
 , GROSS_EXTENDED_AMT 
 , REV_RECOG_BASIS 
 , PROJECT_ID 
 , BUSINESS_UNIT_OM 
 , ORDER_NO 
 , ORDER_INT_LINE_NO 
 , SCHED_LINE_NBR 
 , DEMAND_SOURCE 
 , DEMAND_LINE_NO 
 , BUSINESS_UNIT_RMA 
 , RMA_ID 
 , RMA_LINE_NBR 
 , PRODUCT_ID 
 , ORDER_DATE 
 , PO_REF 
 , PO_LINE 
 , CONTRACT_NUM 
 , CONTRACT_DT 
 , CONTRACT_TYPE 
 , CONTRACT_LINE_NUM 
 , FREIGHT_TERMS 
 , BILL_OF_LADING 
 , COUNTRY_SHIP_FROM 
 , COUNTRY_SHIP_TO 
 , SHIP_TO_CUST_ID 
 , SHIP_TO_ADDR_NUM 
 , SHIP_ID 
 , SHIP_TYPE_ID 
 , SHIP_FROM_BU 
 , SHIP_DATE 
 , SHIP_TIME 
 , PACKSLIP_NO 
 , LC_ID 
 , LOC_DOC_ID 
 , SEQUENCE_NBR 
 , SOLD_TO_CUST_ID 
 , SOLD_TO_ADDR_NUM 
 , BUSINESS_UNIT_PC 
 , BUSINESS_UNIT_CA 
 , RT_EFFDT 
 , BILL_PLAN_ID 
 , PC_DISTRIB_STATUS 
 , BPLAN_LN_NBR 
 , EVENT_OCCURRENCE 
 , XREF_SEQ_NUM 
 , CONTRACT_PPD_SEQ 
 , ANALYSIS_TYPE 
 , RESOURCE_ID 
 , RESOURCE_TYPE 
 , RESOURCE_CATEGORY 
 , RESOURCE_SUB_CAT 
 , ACTIVITY_ID 
 , ACTIVITY_TYPE 
 , DIST_CFG_FLAG 
 , PRODUCT_KIT_ID 
 , SYSTEM_SOURCE 
 , EMPLID 
 , EMPL_RCD 
 , START_DT 
 , END_DT 
 , FROM_DT 
 , TO_DT 
 , SERVICE_CUST_ID 
 , SERVICE_ADDR_NUM 
 , NOTE_TYPE 
 , STD_NOTE_FLAG 
 , INTERNAL_FLAG 
 , HDR_OR_LINE_NOTE 
 , AR_LVL 
 , AR_DST_OPT 
 , GL_LVL 
 , ENABLE_DFR_REV_FLG 
 , BILLING_SPECIALIST 
 , BILLING_AUTHORITY 
 , BILLING_FREQUENCY 
 , BILL_INQUIRY_PHONE 
 , SALES_PERSON 
 , COLLECTOR 
 , CR_ANALYST 
 , INVOICE_FORM_ID 
 , STD_NOTE_CD 
 , TOT_LINE_DST_AMT 
 , TOT_LINE_DST_PCT 
 , TOT_LINE_DFR_PCT 
 , TOT_LINE_DFR_AMT 
 , TOT_LINE_UAR_AMT 
 , TOT_LINE_UAR_PCT 
 , SSN 
 , CHARGE_FROM_DT 
 , CHARGE_TO_DT 
 , SUBCUST_QUAL1 
 , SUBCUST_QUAL2 
 , REIMB_AGREEMENT 
 , TOT_DISCOUNT_AMT 
 , TOT_SURCHARGE_AMT 
 , ACCUMULATE 
 , VAT_TREATMENT_GRP 
 , COUNTRY_VAT_BILLFR 
 , COUNTRY_VAT_BILLTO 
 , VAT_TREATMENT 
 , PHYSICAL_NATURE 
 , COUNTRY_LOC_BUYER 
 , STATE_LOC_BUYER 
 , COUNTRY_LOC_SELLER 
 , STATE_LOC_SELLER 
 , VAT_SVC_SUPPLY_FLG 
 , VAT_SERVICE_TYPE 
 , COUNTRY_VAT_PERFRM 
 , STATE_VAT_PERFRM 
 , COUNTRY_VAT_SUPPLY 
 , STATE_VAT_SUPPLY 
 , STATE_SHIP_FROM 
 , STATE_SHIP_TO 
 , MAST_CONTR_ID 
 , TAX_CUST_ID 
 , BUSINESS_UNIT_AM 
 , BUSINESS_UNIT_AMTO 
 , ASSET_ID 
 , PROFILE_ID 
 , COST_TYPE 
 , STATE_VAT_DEFAULT 
 , SO_ID 
 , BUSINESS_UNIT_RF 
 , SOURCE_REF_TYPE 
 , SOURCE_REF_NO 
 , SOURCE_REF_KEY 
 , ACCEPTGIRO_IND 
 , CA_PGP_SEQ 
 , SUM_TEMPLATE_ID 
 , SUM_GROUP_TYPE 
 , SUM_GROUP_ID 
 , CUST_DEPOSIT_ID 
 , TAX_DATE 
 , GROUP_CODE 
 , SRV_PERFORM_LOC 
 , TAX_DIVISION 
 , TAX_DEPARTMENT 
 , PT_SALE_FLG 
 , CUST_PICKUP 
 , CUSTOMER_PO_LINE 
 , CUSTOMER_PO_SCHED 
 , PUBLIC_VOUCHER_NBR 
 , PVN_GEN_LVL 
 , USER_AMT1 
 , USER_AMT2 
 , USER_DT1 
 , USER_DT2 
 , USER1 
 , USER2 
 , USER3 
 , USER4 
 , USER5 
 , USER6 
 , USER7 
 , USER8 
 , USER9 
 , SETID 
 , PROCESS_INSTANCE 
 , ADD_DTTM 
 , LAST_UPDATE_DTTM 
 , VAT_RVRSE_CHG_GDS 
 , TAX_CD_VAT_RVC 
 , BI_AP_LVL)  
SELECT
A.CIS_TRANS_AGGAMT10
, A.CIS_TRANS_AGG_AMT9
, 'LINE'
, 1
 , ' ' 
 , ' ' 
 , ' ' 
, 'N'
, 'N'
 , ' ' 
 , ' ' 
 , ' ' 
, 'NEW'
 , ' ' 
, A.CIS_CHARTFIELD_6
 , A.CIS_CHARTFIELD_8
, A.CIS_TARGTCUST4DET1
 , 1
, 1
 , 0 
 , ' ' 
 , 'N' 
 , ' ' 
 , 'N' 
 , ' ' 
 , 'DMS' 
 , A.CIS_TARGTCUST5DET5
 , ' ' 
, ' '
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
, 'USD'
 , ' ' 
 , ' ' 
 , 0 
 , 0 
 , ' ' 
 , SYSDATE
 , NULL 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , 0 
 , 0 
 , 0 
 , 0 
 , 0 
 , 0 
 , 0 
, 'REV'
, A.CIS_TARGTCUST5DET3
, A.ATTR_VALUE1
, A.CIS_TARGTCUST1DET3
, A.CIS_TRANS_BI_AMT3
, A.QTY_3
, A.CIS_TRANS_BI_AMT1
, A.CIS_TRANS_BI_AMT1
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , 'ID' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , 0 
, A.CIS_TRANS_BI_AMT2
 , ' ' 
 , ' ' 
 , ' ' 
 , A.KEY2
 , 0 
 , 0 
 , ' ' 
 , 0 
 , ' ' 
 , ' ' 
 , 0 
 , ' ' 
 , A.CIS_EXEC_DATE
 , ' ' 
 , 0 
 , ' ' 
 , NULL 
 , ' ' 
 , 0 
 , ' ' 
, A.CIS_ORIG_CUSTID1
 , ' ' 
 , ' ' 
, A.CIS_TARGTCUST4DET1
 , A.CIS_TARGTCUST4DET2
 , ' ' 
 , A.KEY3
 , ' ' 
 , NULL 
, A.CIS_TRANS_DT4
 , ' ' 
 , ' ' 
 , ' ' 
 , 0 
, A.CIS_TARGTCUST4DET1
 , A.CIS_TARGTCUST4DET2
 , ' ' 
 , ' ' 
 , NULL 
 , ' ' 
 , ' ' 
 , 0 
 , 0 
 , 0 
 , 0 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , 0 
 , NULL 
 , NULL 
 , NULL 
 , NULL 
 , ' ' 
 , 0 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
, ' '
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , 0 
 , 0 
 , 0 
 , 0 
 , 0 
 , 0 
 , ' ' 
, A.CIS_TRANS_DT3
, A.CIS_TRANS_DT4
 , ' ' 
 , ' ' 
 , ' ' 
 , 0 
 , 0 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , A.CIS_CHARTFIELD_7
 , 'ORG' 
 , A.CIS_TARGTCUST1DET1
 , ' ' 
 , ' ' 
 , 0 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , NULL 
 , 0 
 , ' ' 
 , ' ' 
 , ' ' 
 , 'N' 
 , ' ' 
 , ' ' 
 , ' ' 
 , 0 
 , ' ' 
 , 0 
 , 0 
 , NULL 
 , NULL 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , 0 
 , SYSDATE
 , SYSDATE
 , ' ' 
 , ' ' 
 , ' '  
FROM PS_CIS_XPE_IMPORT A WHERE A.CIS_STAGE='FIN' AND A.CIS_TRANS_AGG_AMT9 IS NOT NULL
/
--- UPDATE PS_CIS_XPE_IMPORT SET CIS_TARGET_CUSTID2  = 'X' WHERE CIS_TARGET_CUSTID2  IS NULL AND CIS_STAGE='FIN'
--- insert into INTFC_BI_AEDS
INSERT INTO PS_INTFC_BI_AEDS (INTFC_ID 
 , INTFC_LINE_NUM 
 , TRANS_TYPE_BI 
 , TRANS_TYPE_BI_SEQ 
 , ACCT_ENTRY_TYPE 
 , LOAD_STATUS_BI 
 , ERROR_STATUS_BI 
 , BUSINESS_UNIT 
 , INVOICE 
 , LINE_SEQ_NUM 
 , LINE_DST_SEQ_NUM 
 , DST_ID 
 , DST_ID_DFR 
 , DISC_SUR_LVL 
 , DISC_SUR_INDICATOR 
 , DISC_SUR_ID 
 , DESCR 
 , AMOUNT 
 , PERCENTAGE 
 , BI_CURRENCY_CD 
 , BASE_CURRENCY 
 , BUSINESS_UNIT_GL 
 , BUSINESS_UNIT_TO 
 , TARGET_INVOICE 
 , ACCOUNT 
 , ALTACCT 
 , DEPTID 
 , OPERATING_UNIT 
 , PRODUCT 
 , FUND_CODE 
 , CLASS_FLD 
 , PROGRAM_CODE 
 , BUDGET_REF 
 , AFFILIATE 
 , AFFILIATE_INTRA1 
 , AFFILIATE_INTRA2 
 , CHARTFIELD1 
 , CHARTFIELD2 
 , CHARTFIELD3 
 , PROJECT_ID 
 , STATISTICS_CODE 
 , STATISTIC_AMOUNT 
 , BUDGET_DT 
 , PPRC_PROMO_CD 
 , MERCH_TYPE 
 , SETID 
 , OPEN_ITEM_KEY 
 , JRNL_LN_REF 
 , PROCESS_INSTANCE 
 , ADD_DTTM 
 , LAST_UPDATE_DTTM
 , BUSINESS_UNIT_PC
 , ACTIVITY_ID
 , RESOURCE_TYPE
 , RESOURCE_CATEGORY
 , RESOURCE_SUB_CAT
 , ANALYSIS_TYPE)  
SELECT
A.CIS_TRANS_AGGAMT10
, A.CIS_TRANS_AGG_AMT9
, 'AE'
, 1
, 'RR'
, 'NEW'
 , ' ' 
, A.CIS_CHARTFIELD_6
 , ' ' 
 , 0 
 , 0 
, ' '-- A.ATTR_VALUE3
 , ' ' 
 , 0 
 , ' ' 
 , ' ' 
 , ' ' 
, A.CIS_TRANS_BI_AMT2
, 100
, 'USD'
 , ' ' 
 , A.CIS_CHARTFIELD_8
 , ' ' 
 , ' ' 
 , A.CIS_TARGET_VENDOR1
 , ' ' 
 , ' ' 
 , A.CIS_CHARTFIELD_10
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , A.CIS_CHARTFIELD_9
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' '
 , 0
 , NULL
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , ' ' 
 , 0 
, SYSDATE
, SYSDATE
, ' ' 
, ' ' 
, ' ' 
, ' '
, ' '
, ' '
FROM PS_CIS_XPE_IMPORT A WHERE A.CIS_STAGE='FIN'  AND A.CIS_TRANS_AGG_AMT9 IS NOT NULL
/
---SELECT  max(a.CIS_TRANS_AGGAMT10) FROM PS_CIS_XPE_IMPORT A WHERE A.CIS_STAGE='FIN'
--- mark as complete
UPDATE PS_CIS_XPE_IMPORT A SET A.CIS_STAGE='BIL' WHERE A.CIS_STAGE='FIN'
/

