SET SQLBLANKLINES ON
CREATE TABLE XPE_DCC_CARRIERS 
(
  XPE_CARRIER_ID VARCHAR2(20 BYTE) NOT NULL 
, XPE_CARRIER_DESC VARCHAR2(50 BYTE) NOT NULL 
, CONSTRAINT XPE_DCC_CARRIERS_PK PRIMARY KEY 
  (
    XPE_CARRIER_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX XPE_DCC_CARRIERS_PK ON XPE_DCC_CARRIERS (XPE_CARRIER_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE XPE_DCC_CFG_ACCOUNTING 
(
  SITE_ID VARCHAR2(20 BYTE) 
, ACCOUNTING_CLASS VARCHAR2(40 BYTE) 
, DEAL_CLASS VARCHAR2(40 BYTE) 
, MATERIAL_CATEGORY VARCHAR2(40 BYTE) 
, PRODUCT_SERVICE_ID VARCHAR2(3 BYTE) 
, CHARGE_ID VARCHAR2(20 BYTE) 
, STAT_ACCOUNT VARCHAR2(20 BYTE) 
, ENTRY_TYPE VARCHAR2(20 BYTE) 
, OPERATING_UNIT VARCHAR2(20 BYTE) 
, ACCOUNT_ID VARCHAR2(20 BYTE) NOT NULL 
, CREATED_BY VARCHAR2(20 BYTE) 
, CREATED_DATE TIMESTAMP(6) 
, LAST_UPDATED_BY VARCHAR2(20 BYTE) 
, LAST_UPDATED_DATE TIMESTAMP(6) 
, CONSTRAINT XPE_DCC_CFG_ACCOUNTING_PK PRIMARY KEY 
  (
    ACCOUNT_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX XPE_DCC_CFG_ACCOUNTING_PK ON XPE_DCC_CFG_ACCOUNTING (ACCOUNT_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE XPE_DCC_CFG_BUSINESSUNIT 
(
  BUSINESS_UNIT VARCHAR2(20 BYTE) NOT NULL 
, TERMINAL_ID VARCHAR2(20 BYTE) NOT NULL 
, SITE_ID VARCHAR2(20 BYTE) 
, SITE_DESC VARCHAR2(45 BYTE) 
, ACCOUNTING_CLASS VARCHAR2(40 BYTE) 
, STATS_ONLY VARCHAR2(1 BYTE) 
, INACTIVE VARCHAR2(1 BYTE) 
, INACTIVE_DATE TIMESTAMP(6) 
, BILLING_BUSINESS_UNIT VARCHAR2(20 BYTE) 
, BUSINESS_UNIT_REF VARCHAR2(20 BYTE) 
, GL_BUSINESS_UNIT VARCHAR2(20 BYTE) 
, AFFLIATE VARCHAR2(20 BYTE) 
, OPERATING_UNIT VARCHAR2(20 BYTE) 
, CREATED_BY VARCHAR2(20 BYTE) 
, CREATED_DATE TIMESTAMP(6) 
, LAST_UPDATED_BY VARCHAR2(20 BYTE) 
, LAST_UPDATED_DATE TIMESTAMP(6) 
, CONSTRAINT XPE_DCC_CFG_BUSINESSUNIT_PK PRIMARY KEY 
  (
    BUSINESS_UNIT 
  , TERMINAL_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX XPE_DCC_CFG_BUSINESSUNIT_PK ON XPE_DCC_CFG_BUSINESSUNIT (BUSINESS_UNIT ASC, TERMINAL_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE XPE_DCC_CFG_CARRIERS 
(
  CARRIER_ID VARCHAR2(20 BYTE) NOT NULL 
, CARRIER_NAME VARCHAR2(45 BYTE) 
, STATE VARCHAR2(5 BYTE) 
, INACTIVE VARCHAR2(1 BYTE) 
, INACTIVE_DATE TIMESTAMP(6) 
, CREATED_BY VARCHAR2(20 BYTE) 
, CREATED_DATE TIMESTAMP(6) 
, LAST_UPDATED_BY VARCHAR2(20 BYTE) 
, LAST_UPDATED_DATE TIMESTAMP(6) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE XPE_DCC_CFG_COUNTIES 
(
  COUNTY_ID VARCHAR2(5 BYTE) NOT NULL 
, COUNTY_NAME VARCHAR2(45 BYTE) 
, STATE VARCHAR2(5 BYTE) NOT NULL 
, INACTIVE VARCHAR2(1 BYTE) 
, INACTIVE_DATE TIMESTAMP(6) 
, CREATED_BY VARCHAR2(20 BYTE) 
, CREATED_DATE TIMESTAMP(6) 
, LAST_UPDATED_BY VARCHAR2(20 BYTE) 
, LAST_UPDATED_DATE TIMESTAMP(6) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE XPE_DCC_CFG_DESTINATIONS 
(
  DESTINATION_ID VARCHAR2(20 BYTE) NOT NULL 
, DESTINATION_DESC VARCHAR2(45 BYTE) 
, STATE VARCHAR2(5 BYTE) 
, INACTIVE VARCHAR2(1 BYTE) 
, INACTIVE_DATE TIMESTAMP(6) 
, CREATED_BY VARCHAR2(20 BYTE) 
, CREATED_DATE TIMESTAMP(6) 
, LAST_UPDATED_BY VARCHAR2(20 BYTE) 
, LAST_UPDATED_DATE TIMESTAMP(6) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE XPE_DCC_CFG_GENERAL 
(
  ITEM_ID VARCHAR2(40 BYTE) NOT NULL 
, ITEM_LIST_TYPE VARCHAR2(3 BYTE) NOT NULL 
, VALID_VALUE VARCHAR2(45 BYTE) 
, CREATED_BY VARCHAR2(20 BYTE) 
, CREATED_DATE TIMESTAMP(6) 
, LAST_UPDATED_BY VARCHAR2(20 BYTE) 
, LAST_UPDATED_DATE TIMESTAMP(6) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE XPE_DCC_CFG_GENERAL_CNV 
(
  GENERAL_CNV_ID VARCHAR2(20 BYTE) NOT NULL 
, CARRIER_ID VARCHAR2(20 BYTE) 
, ORIGIN_ID VARCHAR2(20 BYTE) 
, DESTINATION_ID VARCHAR2(20 BYTE) 
, MATERIAL_ID VARCHAR2(3 BYTE) 
, PCS_SHORT_NAME_ID VARCHAR2(20 BYTE) 
, TRANSLATION_CONSUMER VARCHAR2(3 BYTE) 
, CONVERSION_VALUE VARCHAR2(20 BYTE) 
, CREATED_BY VARCHAR2(20 BYTE) 
, CREATED_DATE TIMESTAMP(6) 
, LAST_UPDATED_BY VARCHAR2(20 BYTE) 
, LAST_UPDATED_DATE TIMESTAMP(6) 
, CONSTRAINT XPE_DCC_CFG_GENERAL_CNV_PK PRIMARY KEY 
  (
    GENERAL_CNV_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX XPE_DCC_CFG_GENERAL_CNV_PK ON XPE_DCC_CFG_GENERAL_CNV (GENERAL_CNV_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE XPE_DCC_CFG_PCS 
(
  SITE_ID VARCHAR2(20 BYTE) NOT NULL 
, SITE_DESC VARCHAR2(45 BYTE) 
, DB_LINK VARCHAR2(20 BYTE) 
, PRINT_STAGE VARCHAR2(1 BYTE) 
, INACTIVE VARCHAR2(1 BYTE) 
, INACTIVE_DATE TIMESTAMP(6) 
, ACTIVATE VARCHAR2(1 BYTE) 
, DIRECT_TO_CUSTOMER VARCHAR2(1 BYTE) 
, EMAIL_NOTIFICATION_GROUP VARCHAR2(45 BYTE) 
, CREATED_BY VARCHAR2(20 BYTE) 
, CREATED_DATE TIMESTAMP(6) 
, LAST_UPDATED_BY VARCHAR2(20 BYTE) 
, LAST_UPDATED_DATE TIMESTAMP(6) 
, FACILITY_ID VARCHAR2(20 BYTE) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE XPE_DCC_CFG_PCSSHORTNAMES 
(
  PCSSHORTNAME_ID VARCHAR2(20 BYTE) NOT NULL 
, PCSSHORT_NAME VARCHAR2(45 BYTE) 
, ACCOUNT_CLASS VARCHAR2(1 BYTE) 
, INACTIVE VARCHAR2(1 BYTE) 
, INACTIVE_DATE TIMESTAMP(6) 
, CREATED_BY VARCHAR2(20 BYTE) 
, CREATED_DATE TIMESTAMP(6) 
, LAST_UPDATED_BY VARCHAR2(20 BYTE) 
, LAST_UPDATED_DATE TIMESTAMP(6) 
, COV_ID VARCHAR2(15 BYTE) NOT NULL 
, COV_SOLD_ID VARCHAR2(15 BYTE) 
, COV_BILL_ID VARCHAR2(15 BYTE) 
, COV_SOLD_LOC_NUM NUMBER(38, 0) 
, COV_BILL_LOC_NUM NUMBER(38, 0) 
, BILL_CYCLE_ID VARCHAR2(15 BYTE) 
, INV_SUPRESS VARCHAR2(1 BYTE) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE XPE_DCC_CFG_PRODUCTSERVICE 
(
  ITEM_ID VARCHAR2(3 BYTE) NOT NULL 
, ITEM_TYPE VARCHAR2(3 BYTE) 
, INOUTBOUND VARCHAR2(3 BYTE) 
, DESCRIPTION VARCHAR2(45 BYTE) 
, CATEGORY VARCHAR2(40 BYTE) 
, CLASS_TYPE VARCHAR2(3 BYTE) 
, CLASS_ID VARCHAR2(40 BYTE) 
, INACTIVE VARCHAR2(1 BYTE) 
, INACTIVE_DATE TIMESTAMP(6) 
, CREATED_BY VARCHAR2(20 BYTE) 
, CREATED_DATE TIMESTAMP(6) 
, LAST_UPDATED_BY VARCHAR2(20 BYTE) 
, LAST_UPDATED_DATE TIMESTAMP(6) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE XPE_DCC_CFG_TERMINALS 
(
  TERMINAL_ID VARCHAR2(20 BYTE) NOT NULL 
, TERMINAL_DESC VARCHAR2(45 BYTE) 
, TERMINAL_TYPE VARCHAR2(3 BYTE) 
, STATE VARCHAR2(5 BYTE) 
, COUNTY VARCHAR2(5 BYTE) 
, INACTIVE VARCHAR2(1 BYTE) 
, INACTIVE_DATE TIMESTAMP(6) 
, CREATED_BY VARCHAR2(20 BYTE) 
, CREATED_DATE TIMESTAMP(6) 
, LAST_UPDATED_BY VARCHAR2(20 BYTE) 
, LAST_UPDATED_DATE TIMESTAMP(6) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE XPE_DCC_CFG_VEHICLES 
(
  VEHICLE_ID VARCHAR2(20 BYTE) NOT NULL 
, VEHICLE_TYPE VARCHAR2(45 BYTE) 
, VEHICLE_DESC VARCHAR2(45 BYTE) 
, REQUIRE_TRAILER VARCHAR2(1 BYTE) 
, INACTIVE VARCHAR2(1 BYTE) 
, INACTIVE_DATE TIMESTAMP(6) 
, CREATED_BY VARCHAR2(20 BYTE) 
, CREATED_DATE TIMESTAMP(6) 
, LAST_UPDATED_BY VARCHAR2(20 BYTE) 
, LAST_UPDATED_DATE TIMESTAMP(6) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE XPE_DCC_CONTRACTS 
(
  XPE_CONTRACT_ID VARCHAR2(20 BYTE) NOT NULL 
, XPE_CONTRACT_DESC VARCHAR2(120 BYTE) 
, SETID VARCHAR2(5 BYTE) 
, CUST_ID VARCHAR2(15 BYTE) 
, CREATED_BY VARCHAR2(20 BYTE) 
, CURRENCY_CD VARCHAR2(20 BYTE) 
, XPE_DCC_PCSNAME VARCHAR2(50 BYTE) 
, CONSTRAINT XPE_DCC_CONTRACTS_PK PRIMARY KEY 
  (
    XPE_CONTRACT_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX XPE_DCC_CONTRACTS_PK ON XPE_DCC_CONTRACTS (XPE_CONTRACT_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE XPE_DCC_CONTRACT_LINE 
(
  XPE_CONTRACT_ID VARCHAR2(20 BYTE) NOT NULL 
, XPE_CONTRACT_VERSION VARCHAR2(20 BYTE) NOT NULL 
, XPE_CONTRACT_LINE VARCHAR2(20 BYTE) NOT NULL 
, XPE_FACILITY VARCHAR2(20 BYTE) 
, XPE_PRODUCT_ID VARCHAR2(20 BYTE) 
, XPE_PRODUCT_UOM VARCHAR2(20 BYTE) 
, XPE_QTY_MIN NUMBER(20, 5) 
, XPE_QTY_MAX NUMBER(20, 5) 
, XPE_PERIOD_TYPE VARCHAR2(20 BYTE) 
, XPE_ICON VARCHAR2(20 BYTE) 
, XPE_SW_APPR_NBR VARCHAR2(40 BYTE) 
, CURRENCY_CD VARCHAR2(3 BYTE) 
, BUSINESS_UNIT_GL VARCHAR2(5 BYTE) 
, CONSTRAINT XPE_DCC_CONTRACT_LINE_PK PRIMARY KEY 
  (
    XPE_CONTRACT_ID 
  , XPE_CONTRACT_VERSION 
  , XPE_CONTRACT_LINE 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX XPE_DCC_CONTRACT_LINE_PK ON XPE_DCC_CONTRACT_LINE (XPE_CONTRACT_ID ASC, XPE_CONTRACT_VERSION ASC, XPE_CONTRACT_LINE ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE XPE_DCC_CONTRACT_PRICING_OVER 
(
  XPE_CONTRACT_ID VARCHAR2(20 BYTE) NOT NULL 
, XPE_CONTRACT_LINE VARCHAR2(20 BYTE) NOT NULL 
, XPE_CONTRACT_VERSION VARCHAR2(20 BYTE) NOT NULL 
, XPE_CONTRACT_OVER_NBR NUMBER NOT NULL 
, XPE_OVER_TYPE VARCHAR2(3 BYTE) 
, XPE_OVER_START TIMESTAMP(6) 
, XPE_OVER_END TIMESTAMP(6) 
, XPE_SOURCE_FLD VARCHAR2(20 BYTE) 
, XPE_CONDITION VARCHAR2(3 BYTE) 
, XPE_CHECK VARCHAR2(20 BYTE) 
, XPE_TARGET_FLD VARCHAR2(20 BYTE) 
, XPE_OVER_MSG VARCHAR2(50 BYTE) 
, XPE_OVER_DESC VARCHAR2(50 BYTE) 
, CONSTRAINT XPE_DCC_CNTRCT_PRNG_OVER_PK PRIMARY KEY 
  (
    XPE_CONTRACT_ID 
  , XPE_CONTRACT_VERSION 
  , XPE_CONTRACT_LINE 
  , XPE_CONTRACT_OVER_NBR 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX XPE_DCC_CNTRCT_PRNG_OVER_PK ON XPE_DCC_CONTRACT_PRICING_OVER (XPE_CONTRACT_ID ASC, XPE_CONTRACT_VERSION ASC, XPE_CONTRACT_LINE ASC, XPE_CONTRACT_OVER_NBR ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE XPE_DCC_CONTRACT_PRICING_TERM 
(
  XPE_CONTRACT_ID VARCHAR2(20 BYTE) NOT NULL 
, XPE_CONTRACT_VERSION VARCHAR2(20 BYTE) NOT NULL 
, XPE_CONTRACT_LINE VARCHAR2(20 BYTE) NOT NULL 
, XPE_PRICING_TERM_LINE NUMBER NOT NULL 
, XPE_PRICING_TERM_TYPE VARCHAR2(3 BYTE) 
, XPE_QTY_MAX NUMBER(20, 5) 
, XPE_RATE NUMBER(20, 5) 
, XPE_CHARGE_OVER_MIN NUMBER(20, 5) 
, XPE_CHARGE_OVER_MAX NUMBER(20, 5) 
, XPE_CHARGE_DESC VARCHAR2(50 BYTE) 
, XPE_ROLLOVER_TYPE VARCHAR2(3 BYTE) 
, XPE_RESET_TYPE VARCHAR2(3 BYTE) 
, XPE_PERIOD_TYPE VARCHAR2(3 BYTE) 
, XPE_PERIOD_NBR NUMBER(1, 0) 
, XPE_ICON VARCHAR2(20 BYTE) 
, XPE_INDEX_CHANGE_TYPE VARCHAR2(3 BYTE) 
, XPE_INDEX_CHANGE_ID VARCHAR2(20 BYTE) 
, XPE_METALS_INDEX_VAL NUMBER(20, 5) DEFAULT 0 
, XPE_METALS_INDEX_PRC1 NUMBER(20, 5) DEFAULT 1.00 
, XPE_METALS_INDEX_PRC2 NUMBER(20, 5) DEFAULT 1.00 
, XPE_METALS_UOM_MLT NUMBER(20, 5) DEFAULT 2000 
, XPE_METALS_UOM_DEN NUMBER(20, 5) DEFAULT 2400 
, CONSTRAINT XPE_DCC_CONTRACT_PRICING_T_PK PRIMARY KEY 
  (
    XPE_CONTRACT_ID 
  , XPE_PRICING_TERM_LINE 
  , XPE_CONTRACT_LINE 
  , XPE_CONTRACT_VERSION 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX XPE_DCC_CONTRACT_PRICING_T_PK ON XPE_DCC_CONTRACT_PRICING_TERM (XPE_CONTRACT_ID ASC, XPE_PRICING_TERM_LINE ASC, XPE_CONTRACT_LINE ASC, XPE_CONTRACT_VERSION ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE XPE_DCC_LOOKUP_MASTER 
(
  XPE_LOOKUP_TYPE VARCHAR2(5 BYTE) NOT NULL 
, XPE_LOOKUP_ID VARCHAR2(3 BYTE) NOT NULL 
, XPE_LOOKUP_DESC VARCHAR2(20 BYTE) 
, CONSTRAINT XPE_DCC_LOOKUP_MASTER_PK PRIMARY KEY 
  (
    XPE_LOOKUP_TYPE 
  , XPE_LOOKUP_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX XPE_DCC_LOOKUP_MASTER_PK ON XPE_DCC_LOOKUP_MASTER (XPE_LOOKUP_TYPE ASC, XPE_LOOKUP_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE XPE_DCC_TERM_MASTER 
(
  XPE_DCC_TERM VARCHAR2(50 BYTE) NOT NULL 
, XPE_DCC_STATUS VARCHAR2(3 BYTE) 
, XPE_DCC_TERM_DESC VARCHAR2(100 BYTE) 
, XPE_CONTRACT_SUB_TYPE VARCHAR2(3 BYTE) 
, XPE_WASTE_TYPE VARCHAR2(3 BYTE) 
, XPE_AGREEMENT_TYPE VARCHAR2(3 BYTE) 
, CONSTRAINT XPE_DCC_TERM_MASTER_PK PRIMARY KEY 
  (
    XPE_DCC_TERM 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX XPE_DCC_TERM_MASTER_PK ON XPE_DCC_TERM_MASTER (XPE_DCC_TERM ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE XPE_DCC_WF_EVENT 
(
  XPE_CONTRACT_ID VARCHAR2(20 BYTE) NOT NULL 
, XPE_CONTRACT_VERSION VARCHAR2(20 BYTE) NOT NULL 
, XPE_EVENT_NUMBER VARCHAR2(20 BYTE) NOT NULL 
, XPE_EVENT_STATUS VARCHAR2(1 BYTE) 
, XPE_EVENT_TYPE VARCHAR2(1 BYTE) 
, CREATED_BY VARCHAR2(20 BYTE) NOT NULL 
, CREATED_DATE TIMESTAMP(6) NOT NULL 
, LAST_UPDATED_BY VARCHAR2(20 BYTE) NOT NULL 
, LAST_UPDATED_DATE TIMESTAMP(6) NOT NULL 
, CONSTRAINT XPE_DCC_WF_EVENT_PK PRIMARY KEY 
  (
    XPE_EVENT_NUMBER 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX XPE_DCC_WF_EVENT_PK ON XPE_DCC_WF_EVENT (XPE_EVENT_NUMBER ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE XPE_DMS_CUSTOMER 
(
  CUST_ID VARCHAR2(15 BYTE) NOT NULL 
, SET_ID VARCHAR2(5 BYTE) 
, COMPANY_NAME VARCHAR2(40 BYTE) 
, BILLING_ADDRESS1 VARCHAR2(55 BYTE) 
, BILLING_ADDRESS2 VARCHAR2(55 BYTE) 
, CITY VARCHAR2(30 BYTE) 
, STATE VARCHAR2(6 BYTE) 
, COUNTRY VARCHAR2(3 BYTE) 
, POSTAL VARCHAR2(12 BYTE) 
, MAILING_ADDRESS1 VARCHAR2(55 BYTE) 
, MAILING_ADDRESS2 VARCHAR2(55 BYTE) 
, MAILING_CITY VARCHAR2(30 BYTE) 
, MAILING_STATE VARCHAR2(6 BYTE) 
, MAILING_COUNTRY VARCHAR2(3 BYTE) 
, MAILING_POSTAL VARCHAR2(12 BYTE) 
, EMAIL VARCHAR2(40 BYTE) 
, PHONE_NUM VARCHAR2(40 BYTE) 
, CONTACT_TYPE VARCHAR2(40 BYTE) 
, CONTACT_NAME VARCHAR2(55 BYTE) 
, TITLE VARCHAR2(40 BYTE) 
, BUSINESS_TYPE VARCHAR2(4 BYTE) 
, PRODUCT_TIER VARCHAR2(40 BYTE) 
, CUSTOMER_TIER VARCHAR2(40 BYTE) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE XPE_LINKING_GROUPS 
(
  XPE_GROUP_NAME VARCHAR2(30 BYTE) 
, XPE_GROUP_ID NUMBER(38, 0) NOT NULL 
, XPE_EXCLUSIVE_SET_FLAG NUMBER(1, 0) 
, XPE_EXCLUSIVE_SET_NAME VARCHAR2(30 BYTE) 
, CREATED_BY NUMBER(15, 0) 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER(15, 0) 
, LAST_UPDATE_DATE DATE 
, CONSTRAINT PK_GROUP_ID PRIMARY KEY 
  (
    XPE_GROUP_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_GROUP_ID ON XPE_LINKING_GROUPS (XPE_GROUP_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE XPE_DCC_CFG_ORIGINS 
(
  ORIGIN_ID VARCHAR2(20 BYTE) NOT NULL 
, ORIGIN_DESC VARCHAR2(45 BYTE) 
, STATE VARCHAR2(5 BYTE) 
, INACTIVE VARCHAR2(1 BYTE) 
, INACTIVE_DATE TIMESTAMP(6) 
, CREATED_BY VARCHAR2(20 BYTE) 
, CREATED_DATE TIMESTAMP(6) 
, LAST_UPDATED_BY VARCHAR2(20 BYTE) 
, LAST_UPDATED_DATE TIMESTAMP(6) 
, COUNTY VARCHAR2(5 BYTE) 
, XPE_DCC_NYC_DOS_DISTRICT VARCHAR2(50 BYTE) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE XPE_DCC_CFG_UOM 
(
  ITEM_ID VARCHAR2(3 BYTE) NOT NULL 
, UOM VARCHAR2(40 BYTE) NOT NULL 
, UOM_DESC VARCHAR2(45 BYTE) 
, FEED_METHOD VARCHAR2(3 BYTE) NOT NULL 
, INACTIVE VARCHAR2(1 BYTE) 
, INACTIVE_DATE TIMESTAMP(6) 
, CREATED_BY VARCHAR2(20 BYTE) 
, CREATED_DATE TIMESTAMP(6) 
, LAST_UPDATED_BY VARCHAR2(20 BYTE) 
, LAST_UPDATED_DATE TIMESTAMP(6) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE XPE_DCC_CFG_DST_ASS_TERMINALS 
(
  TERMINAL_ID VARCHAR2(20 BYTE) NOT NULL 
, DESTINATION_ID VARCHAR2(20 BYTE) NOT NULL 
, TERMINAL_DESC VARCHAR2(45 BYTE) 
, INACTIVE VARCHAR2(1 BYTE) 
, INACTIVE_DATE TIMESTAMP(6) 
, CREATED_BY VARCHAR2(20 BYTE) 
, CREATED_DATE TIMESTAMP(6) 
, LAST_UPDATED_BY VARCHAR2(20 BYTE) 
, LAST_UPDATED_DATE TIMESTAMP(6) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE XPE_DCC_CFG_PCS_ASS_TERMINALS 
(
  TERMINAL_ID VARCHAR2(20 BYTE) NOT NULL 
, SITE_ID VARCHAR2(20 BYTE) NOT NULL 
, TERMINAL_DESC VARCHAR2(45 BYTE) 
, INACTIVE VARCHAR2(1 BYTE) 
, INACTIVE_DATE TIMESTAMP(6) 
, CREATED_BY VARCHAR2(20 BYTE) 
, CREATED_DATE TIMESTAMP(6) 
, LAST_UPDATED_BY VARCHAR2(20 BYTE) 
, LAST_UPDATED_DATE TIMESTAMP(6) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE XPE_DCC_CONTRACT_PARTY 
(
  XPE_CONTRACT_ID VARCHAR2(20 BYTE) NOT NULL 
, SETID VARCHAR2(5 BYTE) NOT NULL 
, CUST_ID VARCHAR2(15 BYTE) NOT NULL 
, XPE_PRIMARY VARCHAR2(1 BYTE) DEFAULT 'Y' 
, XPE_PARTY_TYPE VARCHAR2(3 BYTE) DEFAULT 'CUS' 
, CONSTRAINT XPE_DCC_CONTRACT_PARTY_PK PRIMARY KEY 
  (
    XPE_CONTRACT_ID 
  , SETID 
  , CUST_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX XPE_DCC_CONTRACT_PARTY_PK ON XPE_DCC_CONTRACT_PARTY (XPE_CONTRACT_ID ASC, SETID ASC, CUST_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE XPE_DCC_CONTRACT_VERSION 
(
  XPE_CONTRACT_ID VARCHAR2(20 BYTE) NOT NULL 
, XPE_CONTRACT_VERSION VARCHAR2(20 BYTE) NOT NULL 
, XPE_CONTRACT_STATUS VARCHAR2(3 BYTE) 
, XPE_START_DATE TIMESTAMP(6) 
, XPE_END_DATE TIMESTAMP(6) 
, XPE_NEW_TERM_MODE VARCHAR2(3 BYTE) DEFAULT 'REM' 
, CREATED_BY VARCHAR2(20 BYTE) 
, UPDATED_BY VARCHAR2(20 BYTE) 
, XPE_BILL_OPTIONS_SET VARCHAR2(10 BYTE) 
, XPE_ACCTG_OPTIONS_SET VARCHAR2(10 BYTE) 
, XPE_CONTRACT_TEMPLATE VARCHAR2(20 BYTE) 
, BUSINESS_UNIT_GL VARCHAR2(5 BYTE) 
, CURRENCY_CD VARCHAR2(3 BYTE) 
, XPE_WASTE_TYPE VARCHAR2(3 BYTE) 
, XPE_CONTRACT_SUB_TYPE VARCHAR2(3 BYTE) 
, XPE_AGREEMENT_TYPE VARCHAR2(3 BYTE) 
, XPE_AS_OF_DATE TIMESTAMP(6) 
, SALES_PERSON VARCHAR2(40 BYTE) 
, CONSTRAINT XPE_DCC_CONTRACT_VERSION_PK PRIMARY KEY 
  (
    XPE_CONTRACT_ID 
  , XPE_CONTRACT_VERSION 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX XPE_DCC_CONTRACT_VERSION_PK ON XPE_DCC_CONTRACT_VERSION (XPE_CONTRACT_ID ASC, XPE_CONTRACT_VERSION ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE XPE_DCC_PLATFORM_EVENT 
(
  XPE_CONTRACT_ID VARCHAR2(20 BYTE) NOT NULL 
, XPE_PRICING_TERM_LINE NUMBER NOT NULL 
, XPE_CONTRACT_LINE VARCHAR2(20 BYTE) NOT NULL 
, XPE_CONTRACT_VERSION VARCHAR2(20 BYTE) NOT NULL 
, XPE_CARRIER_ID VARCHAR2(20 BYTE) NOT NULL 
, XPE_VEHICLE_TYPE VARCHAR2(3 BYTE) NOT NULL 
, XPE_SUB_NBR NUMBER(2, 0) NOT NULL 
, XPE_VEHICLE_NBR VARCHAR2(20 BYTE) NOT NULL 
, XPE_EVENT_DTTM TIMESTAMP(6) NOT NULL 
, XPE_EVENT_NBR VARCHAR2(10 BYTE) NOT NULL 
, COLUMN1 VARCHAR2(5 BYTE) NOT NULL 
, XPE_EVENT_TYPE VARCHAR2(3 BYTE) 
, XPE_EVENT_REF VARCHAR2(20 BYTE) 
, XPE_EVENT_UOM VARCHAR2(3 BYTE) 
, XPE_EVENT_QTY NUMBER(5, 5) 
, XPE_RESULT_UOM VARCHAR2(3 BYTE) 
, XPE_RESULT_QTY NUMBER(5, 2) 
, XPE_RESULT_TYPE VARCHAR2(10 BYTE) 
, XPE_RESULT_REF VARCHAR2(20 BYTE) 
, XPE_SYSTEM_MSG VARCHAR2(50 BYTE) 
, XPE_ICON VARCHAR2(20 BYTE) 
, CONSTRAINT XPE_DCC_PLATFORM_EVENT_PK PRIMARY KEY 
  (
    COLUMN1 
  , XPE_EVENT_NBR 
  , XPE_EVENT_DTTM 
  , XPE_VEHICLE_NBR 
  , XPE_VEHICLE_TYPE 
  , XPE_SUB_NBR 
  , XPE_CARRIER_ID 
  , XPE_CONTRACT_VERSION 
  , XPE_CONTRACT_LINE 
  , XPE_PRICING_TERM_LINE 
  , XPE_CONTRACT_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX XPE_DCC_PLATFORM_EVENT_PK ON XPE_DCC_PLATFORM_EVENT (COLUMN1 ASC, XPE_EVENT_NBR ASC, XPE_EVENT_DTTM ASC, XPE_VEHICLE_NBR ASC, XPE_VEHICLE_TYPE ASC, XPE_SUB_NBR ASC, XPE_CARRIER_ID ASC, XPE_CONTRACT_VERSION ASC, XPE_CONTRACT_LINE ASC, XPE_PRICING_TERM_LINE ASC, XPE_CONTRACT_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE XPE_DCC_CONTRACT_DOC_TERM 
(
  XPE_CONTRACT_ID VARCHAR2(20 BYTE) NOT NULL 
, XPE_CONTRACT_VERSION VARCHAR2(20 BYTE) NOT NULL 
, XPE_CONTRACT_LINE VARCHAR2(20 BYTE) NOT NULL 
, XPE_CONTRACT_DOC_TERM_ID NUMBER NOT NULL 
, CONSTRAINT XPE_DCC_CONTRACT_DOC_TERM_PK PRIMARY KEY 
  (
    XPE_CONTRACT_ID 
  , XPE_CONTRACT_VERSION 
  , XPE_CONTRACT_LINE 
  , XPE_CONTRACT_DOC_TERM_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX XPE_DCC_CONTRACT_DOC_TERM_PK ON XPE_DCC_CONTRACT_DOC_TERM (XPE_CONTRACT_ID ASC, XPE_CONTRACT_VERSION ASC, XPE_CONTRACT_LINE ASC, XPE_CONTRACT_DOC_TERM_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE XPE_DCC_CONTRACT_CARRIER 
(
  XPE_CONTRACT_ID VARCHAR2(20 BYTE) NOT NULL 
, XPE_PRICING_TERM_LINE NUMBER NOT NULL 
, XPE_CONTRACT_LINE VARCHAR2(20 BYTE) NOT NULL 
, XPE_CONTRACT_VERSION VARCHAR2(20 BYTE) NOT NULL 
, XPE_CARRIER_ID VARCHAR2(20 BYTE) NOT NULL 
, XPE_VEHICLE_TYPE VARCHAR2(3 BYTE) NOT NULL 
, XPE_SUB_NBR NUMBER(2, 0) NOT NULL 
, XPE_VEHICLE_NBR VARCHAR2(20 BYTE) NOT NULL 
, XPE_RATE_OVERRIDE NUMBER(5, 5) 
, XPE_SURCHARGE NUMBER(5, 5) 
, CONSTRAINT XPE_DCC_CONTRACT_CARRIER_PK PRIMARY KEY 
  (
    XPE_CONTRACT_ID 
  , XPE_PRICING_TERM_LINE 
  , XPE_CONTRACT_LINE 
  , XPE_CONTRACT_VERSION 
  , XPE_CARRIER_ID 
  , XPE_VEHICLE_TYPE 
  , XPE_SUB_NBR 
  , XPE_VEHICLE_NBR 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX XPE_DCC_CONTRACT_CARRIER_PK ON XPE_DCC_CONTRACT_CARRIER (XPE_CONTRACT_ID ASC, XPE_PRICING_TERM_LINE ASC, XPE_CONTRACT_LINE ASC, XPE_CONTRACT_VERSION ASC, XPE_CARRIER_ID ASC, XPE_VEHICLE_TYPE ASC, XPE_SUB_NBR ASC, XPE_VEHICLE_NBR ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE XPE_DCC_TERMS 
(
  XPE_DCC_TERM VARCHAR2(50 BYTE) NOT NULL 
, XPE_DCC_CLAUSE VARCHAR2(30 BYTE) NOT NULL 
, XPE_DCC_SEQ NUMBER(5, 0) 
, XPE_DCC_TERM_TEMPLATE CLOB 
, CONSTRAINT XPE_DCC_TERMS_PK PRIMARY KEY 
  (
    XPE_DCC_CLAUSE 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX XPE_DCC_TERMS_PK ON XPE_DCC_TERMS (XPE_DCC_CLAUSE ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL 
LOB (XPE_DCC_TERM_TEMPLATE) STORE AS SYS_LOB0000117660C00004$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  NOCACHE 
  LOGGING 
  TABLESPACE USERS 
  STORAGE 
  ( 
    INITIAL 106496 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    BUFFER_POOL DEFAULT 
  )  
);

CREATE TABLE XPE_DCC_WF_ACTION 
(
  XPE_CONTRACT_ID VARCHAR2(20 BYTE) NOT NULL 
, XPE_CONTRACT_VERSION VARCHAR2(20 BYTE) NOT NULL 
, XPE_EVENT_NUMBER VARCHAR2(20 BYTE) NOT NULL 
, XPE_APPROVER_SEQUENCE VARCHAR2(20 BYTE) NOT NULL 
, XPE_UUID VARCHAR2(40 BYTE) NOT NULL 
, XPE_APPROVER_EMAIL VARCHAR2(40 BYTE) 
, XPE_ACTION_STATUS VARCHAR2(1 BYTE) 
, CREATED_BY VARCHAR2(20 BYTE) NOT NULL 
, CREATED_DATE TIMESTAMP(6) NOT NULL 
, LAST_UPDATED_BY VARCHAR2(20 BYTE) NOT NULL 
, LAST_UPDATED_DATE TIMESTAMP(6) NOT NULL 
, CONSTRAINT XPE_DCC_WF_ACTION_PK PRIMARY KEY 
  (
    XPE_APPROVER_SEQUENCE 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX XPE_DCC_WF_ACTION_PK ON XPE_DCC_WF_ACTION (XPE_APPROVER_SEQUENCE ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE XPE_LINKED_DEALS 
(
  XPE_GROUP_ID NUMBER(38, 0) NOT NULL 
, CREATED_BY NUMBER(15, 0) 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER(15, 0) 
, LAST_UPDATE_DATE DATE 
, XPE_CONTRACT_ID VARCHAR2(20 BYTE) NOT NULL 
, CONSTRAINT PK_CONTRACT_GROUP PRIMARY KEY 
  (
    XPE_GROUP_ID 
  , XPE_CONTRACT_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CONTRACT_GROUP ON XPE_LINKED_DEALS (XPE_GROUP_ID ASC, XPE_CONTRACT_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE XPE_DCC_CFG_OGN_ASS_TERMINALS 
(
  TERMINAL_ID VARCHAR2(20 BYTE) NOT NULL 
, ORIGIN_ID VARCHAR2(20 BYTE) NOT NULL 
, TERMINAL_DESC VARCHAR2(45 BYTE) 
, INACTIVE VARCHAR2(1 BYTE) 
, INACTIVE_DATE TIMESTAMP(6) 
, CREATED_BY VARCHAR2(20 BYTE) 
, CREATED_DATE TIMESTAMP(6) 
, LAST_UPDATED_BY VARCHAR2(20 BYTE) 
, LAST_UPDATED_DATE TIMESTAMP(6) 
, PCSSHORTNAME_ID VARCHAR2(20 BYTE) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE XPE_DCC_CONTRACT_NOTES 
(
  XPE_CONTRACT_ID VARCHAR2(20 BYTE) NOT NULL 
, XPE_CONTRACT_VERSION VARCHAR2(20 BYTE) NOT NULL 
, XPE_NOTE_DTTM TIMESTAMP(6) NOT NULL 
, XPE_NOTE VARCHAR2(255 BYTE) 
, XPE_USER VARCHAR2(20 BYTE) DEFAULT 'admin' NOT NULL 
, XPE_NOTE_LONG CLOB 
, XPE_NOTE_TYPE VARCHAR2(3 BYTE) DEFAULT 'int' NOT NULL 
, CONSTRAINT XPE_DCC_CONTRACT_NOTES_PK PRIMARY KEY 
  (
    XPE_CONTRACT_ID 
  , XPE_CONTRACT_VERSION 
  , XPE_NOTE_DTTM 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX XPE_DCC_CONTRACT_NOTES_PK ON XPE_DCC_CONTRACT_NOTES (XPE_CONTRACT_ID ASC, XPE_CONTRACT_VERSION ASC, XPE_NOTE_DTTM ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL 
LOB (XPE_NOTE_LONG) STORE AS SYS_LOB0000112946C00006$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  NOCACHE 
  LOGGING 
  TABLESPACE USERS 
  STORAGE 
  ( 
    INITIAL 106496 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    BUFFER_POOL DEFAULT 
  )  
);

CREATE TABLE XPE_DCC_TERMS_CONTRACT 
(
  XPE_DCC_TERM VARCHAR2(50 BYTE) NOT NULL 
, XPE_DCC_CLAUSE VARCHAR2(30 BYTE) NOT NULL 
, XPE_DCC_SEQ NUMBER(5, 0) 
, XPE_DCC_TERM_TEMPLATE CLOB 
, XPE_DCC_CONTRACT_ID VARCHAR2(20 BYTE) NOT NULL 
, XPE_DCC_CONTRACT_VERSION VARCHAR2(20 BYTE) NOT NULL 
, CONSTRAINT XPE_DCC_TERMS_CONTRACT_PK PRIMARY KEY 
  (
    XPE_DCC_CLAUSE 
  , XPE_DCC_CONTRACT_ID 
  , XPE_DCC_CONTRACT_VERSION 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX XPE_DCC_TERMS_CONTRACT_PK ON XPE_DCC_TERMS_CONTRACT (XPE_DCC_CLAUSE ASC, XPE_DCC_CONTRACT_ID ASC, XPE_DCC_CONTRACT_VERSION ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL 
LOB (XPE_DCC_TERM_TEMPLATE) STORE AS SYS_LOB0000119839C00004$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  NOCACHE 
  LOGGING 
  TABLESPACE USERS 
  STORAGE 
  ( 
    INITIAL 106496 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    BUFFER_POOL DEFAULT 
  )  
);

CREATE TABLE XPE_DCC_WORKFLOW 
(
  XPE_CONTRACT_ID VARCHAR2(20 BYTE) NOT NULL 
, XPE_CONTRACT_VERSION VARCHAR2(20 BYTE) NOT NULL 
, XPE_WF_TYPE VARCHAR2(3 BYTE) NOT NULL 
, XPE_WF_DTTM TIMESTAMP(6) NOT NULL 
, XPE_WF_NBR VARCHAR2(20 BYTE) NOT NULL 
, XPE_WF_USER VARCHAR2(20 BYTE) 
, XPE_WF_COMMENT VARCHAR2(50 BYTE) 
, XPE_ICON VARCHAR2(20 BYTE) 
, CONSTRAINT XPE_DCC_WORKFLOW_PK PRIMARY KEY 
  (
    XPE_CONTRACT_ID 
  , XPE_CONTRACT_VERSION 
  , XPE_WF_DTTM 
  , XPE_WF_TYPE 
  , XPE_WF_NBR 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX XPE_DCC_WORKFLOW_PK ON XPE_DCC_WORKFLOW (XPE_CONTRACT_ID ASC, XPE_CONTRACT_VERSION ASC, XPE_WF_DTTM ASC, XPE_WF_TYPE ASC, XPE_WF_NBR ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE XPE_DCC_CONTRACT_CARRIER_OVER 
(
  XPE_CONTRACT_ID VARCHAR2(20 BYTE) NOT NULL 
, XPE_PRICING_TERM_LINE NUMBER NOT NULL 
, XPE_CONTRACT_LINE VARCHAR2(20 BYTE) NOT NULL 
, XPE_CONTRACT_VERSION VARCHAR2(20 BYTE) NOT NULL 
, XPE_CARRIER_ID VARCHAR2(20 BYTE) NOT NULL 
, XPE_CARRIER_OVER_ID NUMBER NOT NULL 
, XPE_VEHICLE_TYPE VARCHAR2(3 BYTE) NOT NULL 
, XPE_SUB_NBR NUMBER(2, 0) NOT NULL 
, XPE_VEHICLE_NBR VARCHAR2(20 BYTE) NOT NULL 
, XPE_OVER_TYPE VARCHAR2(3 BYTE) 
, XPE_OVER_START TIMESTAMP(6) 
, XPE_OVER_END TIMESTAMP(6) 
, XPE_SOURCE_FLD VARCHAR2(20 BYTE) 
, XPE_CONDITION VARCHAR2(3 BYTE) 
, XPE_CHECK VARCHAR2(20 BYTE) 
, XPE_TARGET_FLD VARCHAR2(20 BYTE) 
, XPE_OVER_MSG VARCHAR2(50 BYTE) 
, XPE_OVER_DESC VARCHAR2(50 BYTE) 
, CONSTRAINT XPE_DCC_CONTRACT_CARRIER_O_PK PRIMARY KEY 
  (
    XPE_CONTRACT_ID 
  , XPE_PRICING_TERM_LINE 
  , XPE_CONTRACT_LINE 
  , XPE_CONTRACT_VERSION 
  , XPE_CARRIER_OVER_ID 
  , XPE_CARRIER_ID 
  , XPE_VEHICLE_TYPE 
  , XPE_SUB_NBR 
  , XPE_VEHICLE_NBR 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX XPE_DCC_CONTRACT_CARRIER_O_PK ON XPE_DCC_CONTRACT_CARRIER_OVER (XPE_CONTRACT_ID ASC, XPE_PRICING_TERM_LINE ASC, XPE_CONTRACT_LINE ASC, XPE_CONTRACT_VERSION ASC, XPE_CARRIER_OVER_ID ASC, XPE_CARRIER_ID ASC, XPE_VEHICLE_TYPE ASC, XPE_SUB_NBR ASC, XPE_VEHICLE_NBR ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE UNIQUE INDEX XPE_DCC_CFG_CARRIERS_PK ON XPE_DCC_CFG_CARRIERS (CARRIER_ID ASC) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX XPE_DCC_CFG_COUNTIES_PK ON XPE_DCC_CFG_COUNTIES (COUNTY_ID ASC) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX XPE_DCC_CFG_DESTINATIONS_PK ON XPE_DCC_CFG_DESTINATIONS (DESTINATION_ID ASC) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX XPE_DCC_CFG_DST_ASS_TMS_PK ON XPE_DCC_CFG_DST_ASS_TERMINALS (TERMINAL_ID ASC, DESTINATION_ID ASC) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX XPE_DCC_CFG_GENERAL_PK ON XPE_DCC_CFG_GENERAL (ITEM_ID ASC, ITEM_LIST_TYPE ASC) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX XPE_DCC_CFG_OGN_ASS_TMS_PK ON XPE_DCC_CFG_OGN_ASS_TERMINALS (TERMINAL_ID ASC, ORIGIN_ID ASC) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX XPE_DCC_CFG_ORIGINS_PK ON XPE_DCC_CFG_ORIGINS (ORIGIN_ID ASC) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX XPE_DCC_CFG_PCS_PK ON XPE_DCC_CFG_PCS (SITE_ID ASC) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX XPE_DCC_CFG_PCSSHORTNAMES_PK ON XPE_DCC_CFG_PCSSHORTNAMES (PCSSHORTNAME_ID ASC) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX XPE_DCC_CFG_PCS_ASS_TMS_PK ON XPE_DCC_CFG_PCS_ASS_TERMINALS (TERMINAL_ID ASC, SITE_ID ASC) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX XPE_DCC_CFG_PRODUCTSERVICE_PK ON XPE_DCC_CFG_PRODUCTSERVICE (ITEM_ID ASC) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX XPE_DCC_CFG_TERMINALS_PK ON XPE_DCC_CFG_TERMINALS (TERMINAL_ID ASC) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX XPE_DCC_CFG_UOM_PK ON XPE_DCC_CFG_UOM (ITEM_ID ASC, UOM ASC, FEED_METHOD ASC) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX XPE_DCC_CFG_VEHICLES_PK ON XPE_DCC_CFG_VEHICLES (VEHICLE_ID ASC) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX XPE_DMS_CUSTOMER_PK ON XPE_DMS_CUSTOMER (CUST_ID ASC) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE XPE_DCC_CFG_CARRIERS
ADD CONSTRAINT XPE_DCC_CFG_CARRIERS_PK PRIMARY KEY 
(
  CARRIER_ID 
)
USING INDEX XPE_DCC_CFG_CARRIERS_PK
ENABLE;

ALTER TABLE XPE_DCC_CFG_COUNTIES
ADD CONSTRAINT XPE_DCC_CFG_COUNTIES_PK PRIMARY KEY 
(
  COUNTY_ID 
)
USING INDEX XPE_DCC_CFG_COUNTIES_PK
ENABLE;

ALTER TABLE XPE_DCC_CFG_DESTINATIONS
ADD CONSTRAINT XPE_DCC_CFG_DESTINATIONS_PK PRIMARY KEY 
(
  DESTINATION_ID 
)
USING INDEX XPE_DCC_CFG_DESTINATIONS_PK
ENABLE;

ALTER TABLE XPE_DCC_CFG_DST_ASS_TERMINALS
ADD CONSTRAINT XPE_DCC_CFG_DST_ASS_TMS_PK PRIMARY KEY 
(
  TERMINAL_ID 
, DESTINATION_ID 
)
USING INDEX XPE_DCC_CFG_DST_ASS_TMS_PK
ENABLE;

ALTER TABLE XPE_DCC_CFG_GENERAL
ADD CONSTRAINT XPE_DCC_CFG_GENERAL_PK PRIMARY KEY 
(
  ITEM_ID 
, ITEM_LIST_TYPE 
)
USING INDEX XPE_DCC_CFG_GENERAL_PK
ENABLE;

ALTER TABLE XPE_DCC_CFG_OGN_ASS_TERMINALS
ADD CONSTRAINT XPE_DCC_CFG_OGN_ASS_TMS_PK PRIMARY KEY 
(
  TERMINAL_ID 
, ORIGIN_ID 
)
USING INDEX XPE_DCC_CFG_OGN_ASS_TMS_PK
ENABLE;

ALTER TABLE XPE_DCC_CFG_ORIGINS
ADD CONSTRAINT XPE_DCC_CFG_ORIGINS_PK PRIMARY KEY 
(
  ORIGIN_ID 
)
USING INDEX XPE_DCC_CFG_ORIGINS_PK
ENABLE;

ALTER TABLE XPE_DCC_CFG_PCS
ADD CONSTRAINT XPE_DCC_CFG_PCS_PK PRIMARY KEY 
(
  SITE_ID 
)
USING INDEX XPE_DCC_CFG_PCS_PK
ENABLE;

ALTER TABLE XPE_DCC_CFG_PCSSHORTNAMES
ADD CONSTRAINT XPE_DCC_CFG_PCSSHORTNAMES_PK PRIMARY KEY 
(
  PCSSHORTNAME_ID 
)
USING INDEX XPE_DCC_CFG_PCSSHORTNAMES_PK
ENABLE;

ALTER TABLE XPE_DCC_CFG_PCS_ASS_TERMINALS
ADD CONSTRAINT XPE_DCC_CFG_PCS_ASS_TMS_PK PRIMARY KEY 
(
  TERMINAL_ID 
, SITE_ID 
)
USING INDEX XPE_DCC_CFG_PCS_ASS_TMS_PK
ENABLE;

ALTER TABLE XPE_DCC_CFG_PRODUCTSERVICE
ADD CONSTRAINT XPE_DCC_CFG_PRODUCTSERVICE_PK PRIMARY KEY 
(
  ITEM_ID 
)
USING INDEX XPE_DCC_CFG_PRODUCTSERVICE_PK
ENABLE;

ALTER TABLE XPE_DCC_CFG_TERMINALS
ADD CONSTRAINT XPE_DCC_CFG_TERMINALS_PK PRIMARY KEY 
(
  TERMINAL_ID 
)
USING INDEX XPE_DCC_CFG_TERMINALS_PK
ENABLE;

ALTER TABLE XPE_DCC_CFG_UOM
ADD CONSTRAINT XPE_DCC_CFG_UOM_PK PRIMARY KEY 
(
  ITEM_ID 
, UOM 
, FEED_METHOD 
)
USING INDEX XPE_DCC_CFG_UOM_PK
ENABLE;

ALTER TABLE XPE_DCC_CFG_VEHICLES
ADD CONSTRAINT XPE_DCC_CFG_VEHICLES_PK PRIMARY KEY 
(
  VEHICLE_ID 
)
USING INDEX XPE_DCC_CFG_VEHICLES_PK
ENABLE;

ALTER TABLE XPE_DMS_CUSTOMER
ADD CONSTRAINT XPE_DMS_CUSTOMER_PK PRIMARY KEY 
(
  CUST_ID 
)
USING INDEX XPE_DMS_CUSTOMER_PK
ENABLE;

ALTER TABLE XPE_DCC_CFG_DST_ASS_TERMINALS
ADD CONSTRAINT XPE_DCC_CFG_DESTINATIONS_FK FOREIGN KEY
(
  DESTINATION_ID 
)
REFERENCES XPE_DCC_CFG_DESTINATIONS
(
  DESTINATION_ID 
)
ENABLE;

ALTER TABLE XPE_DCC_CFG_DST_ASS_TERMINALS
ADD CONSTRAINT XPE_DCC_CFG_TERMINALS_FK FOREIGN KEY
(
  TERMINAL_ID 
)
REFERENCES XPE_DCC_CFG_TERMINALS
(
  TERMINAL_ID 
)
ENABLE;

ALTER TABLE XPE_DCC_CFG_OGN_ASS_TERMINALS
ADD CONSTRAINT XPE_DCC_CFG_ORIGINS_FK FOREIGN KEY
(
  ORIGIN_ID 
)
REFERENCES XPE_DCC_CFG_ORIGINS
(
  ORIGIN_ID 
)
ENABLE;

ALTER TABLE XPE_DCC_CFG_OGN_ASS_TERMINALS
ADD CONSTRAINT XPE_DCC_CFG_TERMINALS_FK2 FOREIGN KEY
(
  TERMINAL_ID 
)
REFERENCES XPE_DCC_CFG_TERMINALS
(
  TERMINAL_ID 
)
ENABLE;

ALTER TABLE XPE_DCC_CFG_ORIGINS
ADD CONSTRAINT FK_COUNTIES FOREIGN KEY
(
  COUNTY 
)
REFERENCES XPE_DCC_CFG_COUNTIES
(
  COUNTY_ID 
)
ENABLE;

ALTER TABLE XPE_DCC_CFG_PCS_ASS_TERMINALS
ADD CONSTRAINT XPE_DCC_CFG_PCS_FK FOREIGN KEY
(
  SITE_ID 
)
REFERENCES XPE_DCC_CFG_PCS
(
  SITE_ID 
)
ENABLE;

ALTER TABLE XPE_DCC_CFG_PCS_ASS_TERMINALS
ADD CONSTRAINT XPE_DCC_CFG_TERMINALS_FK1 FOREIGN KEY
(
  TERMINAL_ID 
)
REFERENCES XPE_DCC_CFG_TERMINALS
(
  TERMINAL_ID 
)
ENABLE;

ALTER TABLE XPE_DCC_CFG_UOM
ADD CONSTRAINT XPE_DCC_CFG_PRODUCTSERVICE_FK FOREIGN KEY
(
  ITEM_ID 
)
REFERENCES XPE_DCC_CFG_PRODUCTSERVICE
(
  ITEM_ID 
)
ENABLE;

ALTER TABLE XPE_DCC_CONTRACT_CARRIER
ADD CONSTRAINT XPE_DCC_CONTRACT_CARRIER_FK1 FOREIGN KEY
(
  XPE_CONTRACT_ID 
, XPE_PRICING_TERM_LINE 
, XPE_CONTRACT_LINE 
, XPE_CONTRACT_VERSION 
)
REFERENCES XPE_DCC_CONTRACT_PRICING_TERM
(
  XPE_CONTRACT_ID 
, XPE_PRICING_TERM_LINE 
, XPE_CONTRACT_LINE 
, XPE_CONTRACT_VERSION 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE XPE_DCC_CONTRACT_CARRIER
ADD CONSTRAINT XPE_DCC_CONTRACT_CARRIER_FK2 FOREIGN KEY
(
  XPE_CARRIER_ID 
)
REFERENCES XPE_DCC_CARRIERS
(
  XPE_CARRIER_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE XPE_DCC_CONTRACT_CARRIER_OVER
ADD CONSTRAINT XPE_DCC_CONTRACT_CARRIER__FK2 FOREIGN KEY
(
  XPE_CONTRACT_ID 
, XPE_PRICING_TERM_LINE 
, XPE_CONTRACT_LINE 
, XPE_CONTRACT_VERSION 
, XPE_CARRIER_ID 
, XPE_VEHICLE_TYPE 
, XPE_SUB_NBR 
, XPE_VEHICLE_NBR 
)
REFERENCES XPE_DCC_CONTRACT_CARRIER
(
  XPE_CONTRACT_ID 
, XPE_PRICING_TERM_LINE 
, XPE_CONTRACT_LINE 
, XPE_CONTRACT_VERSION 
, XPE_CARRIER_ID 
, XPE_VEHICLE_TYPE 
, XPE_SUB_NBR 
, XPE_VEHICLE_NBR 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE XPE_DCC_CONTRACT_DOC_TERM
ADD CONSTRAINT XPE_DCC_CONTRACT_DOC_TERM_FK1 FOREIGN KEY
(
  XPE_CONTRACT_ID 
, XPE_CONTRACT_VERSION 
, XPE_CONTRACT_LINE 
)
REFERENCES XPE_DCC_CONTRACT_LINE
(
  XPE_CONTRACT_ID 
, XPE_CONTRACT_VERSION 
, XPE_CONTRACT_LINE 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE XPE_DCC_CONTRACT_NOTES
ADD CONSTRAINT XPE_DCC_CONTRACT_NOTES_FK1 FOREIGN KEY
(
  XPE_CONTRACT_ID 
, XPE_CONTRACT_VERSION 
)
REFERENCES XPE_DCC_CONTRACT_VERSION
(
  XPE_CONTRACT_ID 
, XPE_CONTRACT_VERSION 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE XPE_DCC_CONTRACT_PARTY
ADD CONSTRAINT XPE_DCC_CONTRACT_PARTY_FK1 FOREIGN KEY
(
  XPE_CONTRACT_ID 
)
REFERENCES XPE_DCC_CONTRACTS
(
  XPE_CONTRACT_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE XPE_DCC_CONTRACT_VERSION
ADD CONSTRAINT XPE_DCC_CONTRACT_VERSION_FK1 FOREIGN KEY
(
  XPE_CONTRACT_ID 
)
REFERENCES XPE_DCC_CONTRACTS
(
  XPE_CONTRACT_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE XPE_DCC_PLATFORM_EVENT
ADD CONSTRAINT XPE_DCC_PLATFORM_EVENT_FK1 FOREIGN KEY
(
  XPE_CONTRACT_ID 
)
REFERENCES XPE_DCC_CONTRACTS
(
  XPE_CONTRACT_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE XPE_DCC_TERMS
ADD CONSTRAINT XPE_DCC_TERMS_FK FOREIGN KEY
(
  XPE_DCC_TERM 
)
REFERENCES XPE_DCC_TERM_MASTER
(
  XPE_DCC_TERM 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE XPE_DCC_TERMS_CONTRACT
ADD CONSTRAINT XPE_DCC_TERMS_CONTRACT_FK FOREIGN KEY
(
  XPE_DCC_CONTRACT_ID 
, XPE_DCC_CONTRACT_VERSION 
)
REFERENCES XPE_DCC_CONTRACT_VERSION
(
  XPE_CONTRACT_ID 
, XPE_CONTRACT_VERSION 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE XPE_DCC_WF_ACTION
ADD CONSTRAINT XPE_DCC_WF_ACTION_FK1 FOREIGN KEY
(
  XPE_EVENT_NUMBER 
)
REFERENCES XPE_DCC_WF_EVENT
(
  XPE_EVENT_NUMBER 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE XPE_DCC_WORKFLOW
ADD CONSTRAINT XPE_DCC_WORKFLOW_FK1 FOREIGN KEY
(
  XPE_CONTRACT_ID 
, XPE_CONTRACT_VERSION 
)
REFERENCES XPE_DCC_CONTRACT_VERSION
(
  XPE_CONTRACT_ID 
, XPE_CONTRACT_VERSION 
)
ENABLE;

ALTER TABLE XPE_LINKED_DEALS
ADD CONSTRAINT FK_CONTRACTS FOREIGN KEY
(
  XPE_CONTRACT_ID 
)
REFERENCES XPE_DCC_CONTRACTS
(
  XPE_CONTRACT_ID 
)
ENABLE;

ALTER TABLE XPE_LINKED_DEALS
ADD CONSTRAINT FK_LINKING_GROUPS FOREIGN KEY
(
  XPE_GROUP_ID 
)
REFERENCES XPE_LINKING_GROUPS
(
  XPE_GROUP_ID 
)
ENABLE;

COMMENT ON COLUMN XPE_DCC_CARRIERS.XPE_CARRIER_ID IS 'Carrier Id';

COMMENT ON COLUMN XPE_DCC_CARRIERS.XPE_CARRIER_DESC IS 'Carrier Name';

COMMENT ON COLUMN XPE_DCC_CONTRACTS.XPE_CONTRACT_DESC IS 'Contract Description';

COMMENT ON COLUMN XPE_DCC_LOOKUP_MASTER.XPE_LOOKUP_TYPE IS 'Lookup type';

COMMENT ON COLUMN XPE_DCC_LOOKUP_MASTER.XPE_LOOKUP_ID IS 'Lookup code';

COMMENT ON COLUMN XPE_DCC_LOOKUP_MASTER.XPE_LOOKUP_DESC IS 'Description';

CREATE SEQUENCE XPE_DCC_CFG_ACCOUNTING_SEQ INCREMENT BY 1 MAXVALUE 9999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE XPE_DCC_CFG_CARRIERS_SEQ INCREMENT BY 1 MAXVALUE 9999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE XPE_DCC_CFG_DESTINATIONS_SEQ INCREMENT BY 1 MAXVALUE 9999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE XPE_DCC_CFG_GENERAL_CNV_SEQ INCREMENT BY 1 MAXVALUE 9999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE XPE_DCC_CFG_ORIGINS_SEQ INCREMENT BY 1 MAXVALUE 9999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE XPE_DCC_CFG_PCSSHORTNAMES_SEQ INCREMENT BY 1 MAXVALUE 9999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE XPE_DCC_CFG_PCS_SEQ INCREMENT BY 1 MAXVALUE 9999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE XPE_DCC_CFG_TERMINALS_SEQ INCREMENT BY 1 MAXVALUE 9999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE XPE_DCC_CFG_VEHICLES_SEQ INCREMENT BY 1 MAXVALUE 9999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE XPE_DCC_CONTRACT_SEQ INCREMENT BY 1 MAXVALUE 9999999999 MINVALUE 100 CACHE 20;

CREATE SEQUENCE XPE_DCC_CONTRACT_VERSION_SEQ INCREMENT BY 1 MAXVALUE 999999999 MINVALUE 100 CACHE 20;

CREATE SEQUENCE XPE_DCC_WF_ACTION_SEQ INCREMENT BY 1 MAXVALUE 9999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE XPE_DCC_WF_EVENT_SEQ INCREMENT BY 1 MAXVALUE 9999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE XPE_DMS_CUSTOMER_SEQ INCREMENT BY 1 MAXVALUE 9999999999 MINVALUE 1 CACHE 20;
