package model.views.entitybased;

import model.entities.XpeDmsCustomerEOImpl;

import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 07 22:11:43 EDT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XpeDmsCustomerEOVORowImpl extends ViewRowImpl {

    public static final int ENTITY_XPEDMSCUSTOMEREO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        BillingAddress1,
        BillingAddress2,
        BusinessType,
        City,
        CompanyName,
        ContactName,
        ContactType,
        Country,
        CustId,
        Email,
        MailingAddress1,
        MailingAddress2,
        MailingCity,
        MailingCountry,
        MailingPostal,
        MailingState,
        PhoneNum,
        Postal,
        SetId,
        State,
        Title,
        ProductTier,
        CustomerTier;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int BILLINGADDRESS1 = AttributesEnum.BillingAddress1.index();
    public static final int BILLINGADDRESS2 = AttributesEnum.BillingAddress2.index();
    public static final int BUSINESSTYPE = AttributesEnum.BusinessType.index();
    public static final int CITY = AttributesEnum.City.index();
    public static final int COMPANYNAME = AttributesEnum.CompanyName.index();
    public static final int CONTACTNAME = AttributesEnum.ContactName.index();
    public static final int CONTACTTYPE = AttributesEnum.ContactType.index();
    public static final int COUNTRY = AttributesEnum.Country.index();
    public static final int CUSTID = AttributesEnum.CustId.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int MAILINGADDRESS1 = AttributesEnum.MailingAddress1.index();
    public static final int MAILINGADDRESS2 = AttributesEnum.MailingAddress2.index();
    public static final int MAILINGCITY = AttributesEnum.MailingCity.index();
    public static final int MAILINGCOUNTRY = AttributesEnum.MailingCountry.index();
    public static final int MAILINGPOSTAL = AttributesEnum.MailingPostal.index();
    public static final int MAILINGSTATE = AttributesEnum.MailingState.index();
    public static final int PHONENUM = AttributesEnum.PhoneNum.index();
    public static final int POSTAL = AttributesEnum.Postal.index();
    public static final int SETID = AttributesEnum.SetId.index();
    public static final int STATE = AttributesEnum.State.index();
    public static final int TITLE = AttributesEnum.Title.index();
    public static final int PRODUCTTIER = AttributesEnum.ProductTier.index();
    public static final int CUSTOMERTIER = AttributesEnum.CustomerTier.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XpeDmsCustomerEOVORowImpl() {
    }

    /**
     * Gets XpeDmsCustomerEO entity object.
     * @return the XpeDmsCustomerEO
     */
    public XpeDmsCustomerEOImpl getXpeDmsCustomerEO() {
        return (XpeDmsCustomerEOImpl) getEntity(ENTITY_XPEDMSCUSTOMEREO);
    }

    /**
     * Gets the attribute value for BILLING_ADDRESS1 using the alias name BillingAddress1.
     * @return the BILLING_ADDRESS1
     */
    public String getBillingAddress1() {
        return (String) getAttributeInternal(BILLINGADDRESS1);
    }

    /**
     * Sets <code>value</code> as attribute value for BILLING_ADDRESS1 using the alias name BillingAddress1.
     * @param value value to set the BILLING_ADDRESS1
     */
    public void setBillingAddress1(String value) {
        setAttributeInternal(BILLINGADDRESS1, value);
    }

    /**
     * Gets the attribute value for BILLING_ADDRESS2 using the alias name BillingAddress2.
     * @return the BILLING_ADDRESS2
     */
    public String getBillingAddress2() {
        return (String) getAttributeInternal(BILLINGADDRESS2);
    }

    /**
     * Sets <code>value</code> as attribute value for BILLING_ADDRESS2 using the alias name BillingAddress2.
     * @param value value to set the BILLING_ADDRESS2
     */
    public void setBillingAddress2(String value) {
        setAttributeInternal(BILLINGADDRESS2, value);
    }

    /**
     * Gets the attribute value for BUSINESS_TYPE using the alias name BusinessType.
     * @return the BUSINESS_TYPE
     */
    public String getBusinessType() {
        return (String) getAttributeInternal(BUSINESSTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for BUSINESS_TYPE using the alias name BusinessType.
     * @param value value to set the BUSINESS_TYPE
     */
    public void setBusinessType(String value) {
        setAttributeInternal(BUSINESSTYPE, value);
    }

    /**
     * Gets the attribute value for CITY using the alias name City.
     * @return the CITY
     */
    public String getCity() {
        return (String) getAttributeInternal(CITY);
    }

    /**
     * Sets <code>value</code> as attribute value for CITY using the alias name City.
     * @param value value to set the CITY
     */
    public void setCity(String value) {
        setAttributeInternal(CITY, value);
    }

    /**
     * Gets the attribute value for COMPANY_NAME using the alias name CompanyName.
     * @return the COMPANY_NAME
     */
    public String getCompanyName() {
        return (String) getAttributeInternal(COMPANYNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY_NAME using the alias name CompanyName.
     * @param value value to set the COMPANY_NAME
     */
    public void setCompanyName(String value) {
        setAttributeInternal(COMPANYNAME, value);
    }

    /**
     * Gets the attribute value for CONTACT_NAME using the alias name ContactName.
     * @return the CONTACT_NAME
     */
    public String getContactName() {
        return (String) getAttributeInternal(CONTACTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTACT_NAME using the alias name ContactName.
     * @param value value to set the CONTACT_NAME
     */
    public void setContactName(String value) {
        setAttributeInternal(CONTACTNAME, value);
    }

    /**
     * Gets the attribute value for CONTACT_TYPE using the alias name ContactType.
     * @return the CONTACT_TYPE
     */
    public String getContactType() {
        return (String) getAttributeInternal(CONTACTTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTACT_TYPE using the alias name ContactType.
     * @param value value to set the CONTACT_TYPE
     */
    public void setContactType(String value) {
        setAttributeInternal(CONTACTTYPE, value);
    }

    /**
     * Gets the attribute value for COUNTRY using the alias name Country.
     * @return the COUNTRY
     */
    public String getCountry() {
        return (String) getAttributeInternal(COUNTRY);
    }

    /**
     * Sets <code>value</code> as attribute value for COUNTRY using the alias name Country.
     * @param value value to set the COUNTRY
     */
    public void setCountry(String value) {
        setAttributeInternal(COUNTRY, value);
    }

    /**
     * Gets the attribute value for CUST_ID using the alias name CustId.
     * @return the CUST_ID
     */
    public String getCustId() {
        return (String) getAttributeInternal(CUSTID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUST_ID using the alias name CustId.
     * @param value value to set the CUST_ID
     */
    public void setCustId(String value) {
        setAttributeInternal(CUSTID, value);
    }

    /**
     * Gets the attribute value for EMAIL using the alias name Email.
     * @return the EMAIL
     */
    public String getEmail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**
     * Sets <code>value</code> as attribute value for EMAIL using the alias name Email.
     * @param value value to set the EMAIL
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**
     * Gets the attribute value for MAILING_ADDRESS1 using the alias name MailingAddress1.
     * @return the MAILING_ADDRESS1
     */
    public String getMailingAddress1() {
        return (String) getAttributeInternal(MAILINGADDRESS1);
    }

    /**
     * Sets <code>value</code> as attribute value for MAILING_ADDRESS1 using the alias name MailingAddress1.
     * @param value value to set the MAILING_ADDRESS1
     */
    public void setMailingAddress1(String value) {
        setAttributeInternal(MAILINGADDRESS1, value);
    }

    /**
     * Gets the attribute value for MAILING_ADDRESS2 using the alias name MailingAddress2.
     * @return the MAILING_ADDRESS2
     */
    public String getMailingAddress2() {
        return (String) getAttributeInternal(MAILINGADDRESS2);
    }

    /**
     * Sets <code>value</code> as attribute value for MAILING_ADDRESS2 using the alias name MailingAddress2.
     * @param value value to set the MAILING_ADDRESS2
     */
    public void setMailingAddress2(String value) {
        setAttributeInternal(MAILINGADDRESS2, value);
    }

    /**
     * Gets the attribute value for MAILING_CITY using the alias name MailingCity.
     * @return the MAILING_CITY
     */
    public String getMailingCity() {
        return (String) getAttributeInternal(MAILINGCITY);
    }

    /**
     * Sets <code>value</code> as attribute value for MAILING_CITY using the alias name MailingCity.
     * @param value value to set the MAILING_CITY
     */
    public void setMailingCity(String value) {
        setAttributeInternal(MAILINGCITY, value);
    }

    /**
     * Gets the attribute value for MAILING_COUNTRY using the alias name MailingCountry.
     * @return the MAILING_COUNTRY
     */
    public String getMailingCountry() {
        return (String) getAttributeInternal(MAILINGCOUNTRY);
    }

    /**
     * Sets <code>value</code> as attribute value for MAILING_COUNTRY using the alias name MailingCountry.
     * @param value value to set the MAILING_COUNTRY
     */
    public void setMailingCountry(String value) {
        setAttributeInternal(MAILINGCOUNTRY, value);
    }

    /**
     * Gets the attribute value for MAILING_POSTAL using the alias name MailingPostal.
     * @return the MAILING_POSTAL
     */
    public String getMailingPostal() {
        return (String) getAttributeInternal(MAILINGPOSTAL);
    }

    /**
     * Sets <code>value</code> as attribute value for MAILING_POSTAL using the alias name MailingPostal.
     * @param value value to set the MAILING_POSTAL
     */
    public void setMailingPostal(String value) {
        setAttributeInternal(MAILINGPOSTAL, value);
    }

    /**
     * Gets the attribute value for MAILING_STATE using the alias name MailingState.
     * @return the MAILING_STATE
     */
    public String getMailingState() {
        return (String) getAttributeInternal(MAILINGSTATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MAILING_STATE using the alias name MailingState.
     * @param value value to set the MAILING_STATE
     */
    public void setMailingState(String value) {
        setAttributeInternal(MAILINGSTATE, value);
    }

    /**
     * Gets the attribute value for PHONE_NUM using the alias name PhoneNum.
     * @return the PHONE_NUM
     */
    public String getPhoneNum() {
        return (String) getAttributeInternal(PHONENUM);
    }

    /**
     * Sets <code>value</code> as attribute value for PHONE_NUM using the alias name PhoneNum.
     * @param value value to set the PHONE_NUM
     */
    public void setPhoneNum(String value) {
        setAttributeInternal(PHONENUM, value);
    }

    /**
     * Gets the attribute value for POSTAL using the alias name Postal.
     * @return the POSTAL
     */
    public String getPostal() {
        return (String) getAttributeInternal(POSTAL);
    }

    /**
     * Sets <code>value</code> as attribute value for POSTAL using the alias name Postal.
     * @param value value to set the POSTAL
     */
    public void setPostal(String value) {
        setAttributeInternal(POSTAL, value);
    }

    /**
     * Gets the attribute value for SET_ID using the alias name SetId.
     * @return the SET_ID
     */
    public String getSetId() {
        return (String) getAttributeInternal(SETID);
    }

    /**
     * Sets <code>value</code> as attribute value for SET_ID using the alias name SetId.
     * @param value value to set the SET_ID
     */
    public void setSetId(String value) {
        setAttributeInternal(SETID, value);
    }

    /**
     * Gets the attribute value for STATE using the alias name State.
     * @return the STATE
     */
    public String getState() {
        return (String) getAttributeInternal(STATE);
    }

    /**
     * Sets <code>value</code> as attribute value for STATE using the alias name State.
     * @param value value to set the STATE
     */
    public void setState(String value) {
        setAttributeInternal(STATE, value);
    }

    /**
     * Gets the attribute value for TITLE using the alias name Title.
     * @return the TITLE
     */
    public String getTitle() {
        return (String) getAttributeInternal(TITLE);
    }

    /**
     * Sets <code>value</code> as attribute value for TITLE using the alias name Title.
     * @param value value to set the TITLE
     */
    public void setTitle(String value) {
        setAttributeInternal(TITLE, value);
    }

    /**
     * Gets the attribute value for PRODUCT_TIER using the alias name ProductTier.
     * @return the PRODUCT_TIER
     */
    public String getProductTier() {
        return (String) getAttributeInternal(PRODUCTTIER);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCT_TIER using the alias name ProductTier.
     * @param value value to set the PRODUCT_TIER
     */
    public void setProductTier(String value) {
        setAttributeInternal(PRODUCTTIER, value);
    }

    /**
     * Gets the attribute value for CUSTOMER_TIER using the alias name CustomerTier.
     * @return the CUSTOMER_TIER
     */
    public String getCustomerTier() {
        return (String) getAttributeInternal(CUSTOMERTIER);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMER_TIER using the alias name CustomerTier.
     * @param value value to set the CUSTOMER_TIER
     */
    public void setCustomerTier(String value) {
        setAttributeInternal(CUSTOMERTIER, value);
    }
}

