package model.views.entitybased;

import java.sql.Timestamp;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Sep 10 03:03:11 EDT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XpeDccCfgDestinationsEOVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public XpeDccCfgDestinationsEOVOImpl() {
    }

    /**
     * Returns the variable value for bind_DestinationId.
     * @return variable value for bind_DestinationId
     */
    public String getbind_DestinationId() {
        return (String) ensureVariableManager().getVariableValue("bind_DestinationId");
    }

    /**
     * Sets <code>value</code> for variable bind_DestinationId.
     * @param value value to bind as bind_DestinationId
     */
    public void setbind_DestinationId(String value) {
        ensureVariableManager().setVariableValue("bind_DestinationId", value);
    }

    /**
     * Returns the variable value for bind_DestinationDesc.
     * @return variable value for bind_DestinationDesc
     */
    public String getbind_DestinationDesc() {
        return (String) ensureVariableManager().getVariableValue("bind_DestinationDesc");
    }

    /**
     * Sets <code>value</code> for variable bind_DestinationDesc.
     * @param value value to bind as bind_DestinationDesc
     */
    public void setbind_DestinationDesc(String value) {
        ensureVariableManager().setVariableValue("bind_DestinationDesc", value);
    }

    /**
     * Returns the variable value for bind_State.
     * @return variable value for bind_State
     */
    public String getbind_State() {
        return (String) ensureVariableManager().getVariableValue("bind_State");
    }

    /**
     * Sets <code>value</code> for variable bind_State.
     * @param value value to bind as bind_State
     */
    public void setbind_State(String value) {
        ensureVariableManager().setVariableValue("bind_State", value);
    }

    /**
     * Returns the variable value for bind_Inactive.
     * @return variable value for bind_Inactive
     */
    public String getbind_Inactive() {
        return (String) ensureVariableManager().getVariableValue("bind_Inactive");
    }

    /**
     * Sets <code>value</code> for variable bind_Inactive.
     * @param value value to bind as bind_Inactive
     */
    public void setbind_Inactive(String value) {
        ensureVariableManager().setVariableValue("bind_Inactive", value);
    }

    /**
     * Returns the variable value for bind_InactiveDate.
     * @return variable value for bind_InactiveDate
     */
    public Timestamp getbind_InactiveDate() {
        return (Timestamp) ensureVariableManager().getVariableValue("bind_InactiveDate");
    }

    /**
     * Sets <code>value</code> for variable bind_InactiveDate.
     * @param value value to bind as bind_InactiveDate
     */
    public void setbind_InactiveDate(Timestamp value) {
        ensureVariableManager().setVariableValue("bind_InactiveDate", value);
    }

    /**
     * Returns the variable value for bind_CountryId.
     * @return variable value for bind_CountryId
     */
    public String getbind_CountryId() {
        return (String) ensureVariableManager().getVariableValue("bind_CountryId");
    }

    /**
     * Sets <code>value</code> for variable bind_CountryId.
     * @param value value to bind as bind_CountryId
     */
    public void setbind_CountryId(String value) {
        ensureVariableManager().setVariableValue("bind_CountryId", value);
    }
}

