package model.views.entitybased;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 01 09:46:59 EDT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XpeDccCfgBusinessunitEOVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public XpeDccCfgBusinessunitEOVOImpl() {
    }

    /**
     * Returns the variable value for bind_BusinessUnit.
     * @return variable value for bind_BusinessUnit
     */
    public String getbind_BusinessUnit() {
        return (String) ensureVariableManager().getVariableValue("bind_BusinessUnit");
    }

    /**
     * Sets <code>value</code> for variable bind_BusinessUnit.
     * @param value value to bind as bind_BusinessUnit
     */
    public void setbind_BusinessUnit(String value) {
        ensureVariableManager().setVariableValue("bind_BusinessUnit", value);
    }

    /**
     * Returns the variable value for bind_SiteId.
     * @return variable value for bind_SiteId
     */
    public String getbind_SiteId() {
        return (String) ensureVariableManager().getVariableValue("bind_SiteId");
    }

    /**
     * Sets <code>value</code> for variable bind_SiteId.
     * @param value value to bind as bind_SiteId
     */
    public void setbind_SiteId(String value) {
        ensureVariableManager().setVariableValue("bind_SiteId", value);
    }

    /**
     * Returns the variable value for bind_TerminalId.
     * @return variable value for bind_TerminalId
     */
    public String getbind_TerminalId() {
        return (String) ensureVariableManager().getVariableValue("bind_TerminalId");
    }

    /**
     * Sets <code>value</code> for variable bind_TerminalId.
     * @param value value to bind as bind_TerminalId
     */
    public void setbind_TerminalId(String value) {
        ensureVariableManager().setVariableValue("bind_TerminalId", value);
    }

    /**
     * Returns the variable value for bind_AccountingClass.
     * @return variable value for bind_AccountingClass
     */
    public String getbind_AccountingClass() {
        return (String) ensureVariableManager().getVariableValue("bind_AccountingClass");
    }

    /**
     * Sets <code>value</code> for variable bind_AccountingClass.
     * @param value value to bind as bind_AccountingClass
     */
    public void setbind_AccountingClass(String value) {
        ensureVariableManager().setVariableValue("bind_AccountingClass", value);
    }

    /**
     * Returns the variable value for bind_Affiliate.
     * @return variable value for bind_Affiliate
     */
    public String getbind_Affiliate() {
        return (String) ensureVariableManager().getVariableValue("bind_Affiliate");
    }

    /**
     * Sets <code>value</code> for variable bind_Affiliate.
     * @param value value to bind as bind_Affiliate
     */
    public void setbind_Affiliate(String value) {
        ensureVariableManager().setVariableValue("bind_Affiliate", value);
    }
}

