package model.views.entitybased;

import java.sql.Timestamp;

import model.entities.XpeDccCfgDestinationsEOImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Sep 10 03:03:11 EDT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XpeDccCfgDestinationsEOVORowImpl extends ViewRowImpl {


    public static final int ENTITY_XPEDCCCFGDESTINATIONSEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        DestinationId,
        DestinationDesc,
        State,
        Country,
        Inactive,
        InactiveDate,
        CreatedBy,
        CreatedDate,
        LastUpdatedBy,
        LastUpdatedDate,
        XpeDccCfgDstAssTerminalsEOVO,
        LookupSharedAppModule_YONLOV,
        XpeDccGeneralItemListROVO1,
        PsCountryTblROVO1;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DESTINATIONID = AttributesEnum.DestinationId.index();
    public static final int DESTINATIONDESC = AttributesEnum.DestinationDesc.index();
    public static final int STATE = AttributesEnum.State.index();
    public static final int COUNTRY = AttributesEnum.Country.index();
    public static final int INACTIVE = AttributesEnum.Inactive.index();
    public static final int INACTIVEDATE = AttributesEnum.InactiveDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int XPEDCCCFGDSTASSTERMINALSEOVO = AttributesEnum.XpeDccCfgDstAssTerminalsEOVO.index();
    public static final int LOOKUPSHAREDAPPMODULE_YONLOV = AttributesEnum.LookupSharedAppModule_YONLOV.index();
    public static final int XPEDCCGENERALITEMLISTROVO1 = AttributesEnum.XpeDccGeneralItemListROVO1.index();
    public static final int PSCOUNTRYTBLROVO1 = AttributesEnum.PsCountryTblROVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XpeDccCfgDestinationsEOVORowImpl() {
    }

    /**
     * Gets XpeDccCfgDestinationsEO entity object.
     * @return the XpeDccCfgDestinationsEO
     */
    public XpeDccCfgDestinationsEOImpl getXpeDccCfgDestinationsEO() {
        return (XpeDccCfgDestinationsEOImpl) getEntity(ENTITY_XPEDCCCFGDESTINATIONSEO);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for DESTINATION_DESC using the alias name DestinationDesc.
     * @return the DESTINATION_DESC
     */
    public String getDestinationDesc() {
        return (String) getAttributeInternal(DESTINATIONDESC);
    }

    /**
     * Sets <code>value</code> as attribute value for DESTINATION_DESC using the alias name DestinationDesc.
     * @param value value to set the DESTINATION_DESC
     */
    public void setDestinationDesc(String value) {
        if (null != value) {
            setAttributeInternal(DESTINATIONDESC, value.toUpperCase());
        } else {
            setAttributeInternal(DESTINATIONDESC, value);
        }
    }

    /**
     * Gets the attribute value for DESTINATION_ID using the alias name DestinationId.
     * @return the DESTINATION_ID
     */
    public String getDestinationId() {
        return (String) getAttributeInternal(DESTINATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for DESTINATION_ID using the alias name DestinationId.
     * @param value value to set the DESTINATION_ID
     */
    public void setDestinationId(String value) {
        setAttributeInternal(DESTINATIONID, value);
    }

    /**
     * Gets the attribute value for INACTIVE using the alias name Inactive.
     * @return the INACTIVE
     */
    public String getInactive() {
        return (String) getAttributeInternal(INACTIVE);
    }

    /**
     * Sets <code>value</code> as attribute value for INACTIVE using the alias name Inactive.
     * @param value value to set the INACTIVE
     */
    public void setInactive(String value) {
        setAttributeInternal(INACTIVE, value);
    }

    /**
     * Gets the attribute value for INACTIVE_DATE using the alias name InactiveDate.
     * @return the INACTIVE_DATE
     */
    public Timestamp getInactiveDate() {
        return (Timestamp) getAttributeInternal(INACTIVEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for INACTIVE_DATE using the alias name InactiveDate.
     * @param value value to set the INACTIVE_DATE
     */
    public void setInactiveDate(Timestamp value) {
        setAttributeInternal(INACTIVEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for COUNTRY using the alias name Country.
     * @return the COUNTRY
     */
    public String getCountry() {
        return (String) getAttributeInternal(COUNTRY);
    }

    /**
     * Sets <code>value</code> as attribute value for COUNTRY using the alias name Country.
     * @param value value to set the COUNTRY
     */
    public void setCountry(String value) {
        setAttributeInternal(COUNTRY, value);
    }

    /**
     * Gets the attribute value for STATE using the alias name State.
     * @return the STATE
     */
    public String getState() {
        return (String) getAttributeInternal(STATE);
    }

    /**
     * Sets <code>value</code> as attribute value for STATE using the alias name State.
     * @param value value to set the STATE
     */
    public void setState(String value) {
        setAttributeInternal(STATE, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link XpeDccCfgDstAssTerminalsEOVO.
     */
    public RowIterator getXpeDccCfgDstAssTerminalsEOVO() {
        return (RowIterator) getAttributeInternal(XPEDCCCFGDSTASSTERMINALSEOVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LookupSharedAppModule_YONLOV.
     */
    public RowSet getLookupSharedAppModule_YONLOV() {
        return (RowSet) getAttributeInternal(LOOKUPSHAREDAPPMODULE_YONLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> XpeDccGeneralItemListROVO1.
     */
    public RowSet getXpeDccGeneralItemListROVO1() {
        return (RowSet) getAttributeInternal(XPEDCCGENERALITEMLISTROVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PsCountryTblROVO1.
     */
    public RowSet getPsCountryTblROVO1() {
        return (RowSet) getAttributeInternal(PSCOUNTRYTBLROVO1);
    }
}

