package model.views.entitybased;

import java.sql.Timestamp;

import oracle.jbo.RowSet;
import oracle.jbo.domain.BlobDomain;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 27 17:46:49 EDT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XpeDccCfgCmtmntFacilityEOVORowImpl extends ViewRowImpl {


    public static final int ENTITY_XPEDCCCFGCMTMNTFACILITYEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        XpeFacilityId,
        CustomerCareReview,
        LegalReview,
        FinancialReview,
        GeneralManagerReview,
        SustSolReview,
        CfoReview,
        CeoReview,
        CreatedBy,
        CreationDate,
        LastUpdatedBy,
        LastUpdateDate,
        Inactive,
        InactiveDate,
        CeoSignature,
        XpeDccDicFacilities1,
        LookupSharedAppModule_XpeDccDicNewContractSetupROVO1;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int XPEFACILITYID = AttributesEnum.XpeFacilityId.index();
    public static final int CUSTOMERCAREREVIEW = AttributesEnum.CustomerCareReview.index();
    public static final int LEGALREVIEW = AttributesEnum.LegalReview.index();
    public static final int FINANCIALREVIEW = AttributesEnum.FinancialReview.index();
    public static final int GENERALMANAGERREVIEW = AttributesEnum.GeneralManagerReview.index();
    public static final int SUSTSOLREVIEW = AttributesEnum.SustSolReview.index();
    public static final int CFOREVIEW = AttributesEnum.CfoReview.index();
    public static final int CEOREVIEW = AttributesEnum.CeoReview.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int INACTIVE = AttributesEnum.Inactive.index();
    public static final int INACTIVEDATE = AttributesEnum.InactiveDate.index();
    public static final int CEOSIGNATURE = AttributesEnum.CeoSignature.index();
    public static final int XPEDCCDICFACILITIES1 = AttributesEnum.XpeDccDicFacilities1.index();
    public static final int LOOKUPSHAREDAPPMODULE_XPEDCCDICNEWCONTRACTSETUPROVO1 =
        AttributesEnum.LookupSharedAppModule_XpeDccDicNewContractSetupROVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XpeDccCfgCmtmntFacilityEOVORowImpl() {
    }

    /**
     * Gets XpeDccCfgCmtmntFacilityEO entity object.
     * @return the XpeDccCfgCmtmntFacilityEO
     */
    public EntityImpl getXpeDccCfgCmtmntFacilityEO() {
        return (EntityImpl) getEntity(ENTITY_XPEDCCCFGCMTMNTFACILITYEO);
    }

    /**
     * Gets the attribute value for XPE_FACILITY_ID using the alias name XpeFacilityId.
     * @return the XPE_FACILITY_ID
     */
    public String getXpeFacilityId() {
        return (String) getAttributeInternal(XPEFACILITYID);
    }

    /**
     * Sets <code>value</code> as attribute value for XPE_FACILITY_ID using the alias name XpeFacilityId.
     * @param value value to set the XPE_FACILITY_ID
     */
    public void setXpeFacilityId(String value) {
        setAttributeInternal(XPEFACILITYID, value);
    }

    /**
     * Gets the attribute value for CUSTOMER_CARE_REVIEW using the alias name CustomerCareReview.
     * @return the CUSTOMER_CARE_REVIEW
     */
    public String getCustomerCareReview() {
        return (String) getAttributeInternal(CUSTOMERCAREREVIEW);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMER_CARE_REVIEW using the alias name CustomerCareReview.
     * @param value value to set the CUSTOMER_CARE_REVIEW
     */
    public void setCustomerCareReview(String value) {
        setAttributeInternal(CUSTOMERCAREREVIEW, value);
    }

    /**
     * Gets the attribute value for LEGAL_REVIEW using the alias name LegalReview.
     * @return the LEGAL_REVIEW
     */
    public String getLegalReview() {
        return (String) getAttributeInternal(LEGALREVIEW);
    }

    /**
     * Sets <code>value</code> as attribute value for LEGAL_REVIEW using the alias name LegalReview.
     * @param value value to set the LEGAL_REVIEW
     */
    public void setLegalReview(String value) {
        setAttributeInternal(LEGALREVIEW, value);
    }

    /**
     * Gets the attribute value for FINANCIAL_REVIEW using the alias name FinancialReview.
     * @return the FINANCIAL_REVIEW
     */
    public String getFinancialReview() {
        return (String) getAttributeInternal(FINANCIALREVIEW);
    }

    /**
     * Sets <code>value</code> as attribute value for FINANCIAL_REVIEW using the alias name FinancialReview.
     * @param value value to set the FINANCIAL_REVIEW
     */
    public void setFinancialReview(String value) {
        setAttributeInternal(FINANCIALREVIEW, value);
    }

    /**
     * Gets the attribute value for GENERAL_MANAGER_REVIEW using the alias name GeneralManagerReview.
     * @return the GENERAL_MANAGER_REVIEW
     */
    public String getGeneralManagerReview() {
        return (String) getAttributeInternal(GENERALMANAGERREVIEW);
    }

    /**
     * Sets <code>value</code> as attribute value for GENERAL_MANAGER_REVIEW using the alias name GeneralManagerReview.
     * @param value value to set the GENERAL_MANAGER_REVIEW
     */
    public void setGeneralManagerReview(String value) {
        setAttributeInternal(GENERALMANAGERREVIEW, value);
    }

    /**
     * Gets the attribute value for SUST_SOL_REVIEW using the alias name SustSolReview.
     * @return the SUST_SOL_REVIEW
     */
    public String getSustSolReview() {
        return (String) getAttributeInternal(SUSTSOLREVIEW);
    }

    /**
     * Sets <code>value</code> as attribute value for SUST_SOL_REVIEW using the alias name SustSolReview.
     * @param value value to set the SUST_SOL_REVIEW
     */
    public void setSustSolReview(String value) {
        setAttributeInternal(SUSTSOLREVIEW, value);
    }

    /**
     * Gets the attribute value for CFO_REVIEW using the alias name CfoReview.
     * @return the CFO_REVIEW
     */
    public String getCfoReview() {
        return (String) getAttributeInternal(CFOREVIEW);
    }

    /**
     * Sets <code>value</code> as attribute value for CFO_REVIEW using the alias name CfoReview.
     * @param value value to set the CFO_REVIEW
     */
    public void setCfoReview(String value) {
        setAttributeInternal(CFOREVIEW, value);
    }

    /**
     * Gets the attribute value for CEO_REVIEW using the alias name CeoReview.
     * @return the CEO_REVIEW
     */
    public String getCeoReview() {
        return (String) getAttributeInternal(CEOREVIEW);
    }

    /**
     * Sets <code>value</code> as attribute value for CEO_REVIEW using the alias name CeoReview.
     * @param value value to set the CEO_REVIEW
     */
    public void setCeoReview(String value) {
        setAttributeInternal(CEOREVIEW, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }


    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }


    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }


    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }


    /**
     * Gets the attribute value for INACTIVE using the alias name Inactive.
     * @return the INACTIVE
     */
    public String getInactive() {
        return (String) getAttributeInternal(INACTIVE);
    }

    /**
     * Sets <code>value</code> as attribute value for INACTIVE using the alias name Inactive.
     * @param value value to set the INACTIVE
     */
    public void setInactive(String value) {
        setAttributeInternal(INACTIVE, value);
    }

    /**
     * Gets the attribute value for INACTIVE_DATE using the alias name InactiveDate.
     * @return the INACTIVE_DATE
     */
    public Timestamp getInactiveDate() {
        return (Timestamp) getAttributeInternal(INACTIVEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for INACTIVE_DATE using the alias name InactiveDate.
     * @param value value to set the INACTIVE_DATE
     */
    public void setInactiveDate(Timestamp value) {
        setAttributeInternal(INACTIVEDATE, value);
    }

    /**
     * Gets the attribute value for CEO_SIGNATURE using the alias name CeoSignature.
     * @return the CEO_SIGNATURE
     */
    public BlobDomain getCeoSignature() {
        return (BlobDomain) getAttributeInternal(CEOSIGNATURE);
    }

    /**
     * Sets <code>value</code> as attribute value for CEO_SIGNATURE using the alias name CeoSignature.
     * @param value value to set the CEO_SIGNATURE
     */
    public void setCeoSignature(BlobDomain value) {
        setAttributeInternal(CEOSIGNATURE, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> XpeDccDicFacilities1.
     */
    public RowSet getXpeDccDicFacilities1() {
        return (RowSet) getAttributeInternal(XPEDCCDICFACILITIES1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LookupSharedAppModule_XpeDccDicNewContractSetupROVO1.
     */
    public RowSet getLookupSharedAppModule_XpeDccDicNewContractSetupROVO1() {
        return (RowSet) getAttributeInternal(LOOKUPSHAREDAPPMODULE_XPEDCCDICNEWCONTRACTSETUPROVO1);
    }
}

