package model.views.entitybased;

import java.sql.Timestamp;

import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 18 15:48:55 EDT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XpeDccWfActionEOVORowImpl extends ViewRowImpl {
    public static final int ENTITY_XPEDCCWFACTIONEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        CreatedBy,
        CreatedDate,
        LastUpdatedBy,
        LastUpdatedDate,
        XpeActionStatus,
        XpeApproverEmail,
        XpeApproverSequence,
        XpeContractId,
        XpeContractVersion,
        XpeEventNumber,
        XpeUuid;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int XPEACTIONSTATUS = AttributesEnum.XpeActionStatus.index();
    public static final int XPEAPPROVEREMAIL = AttributesEnum.XpeApproverEmail.index();
    public static final int XPEAPPROVERSEQUENCE = AttributesEnum.XpeApproverSequence.index();
    public static final int XPECONTRACTID = AttributesEnum.XpeContractId.index();
    public static final int XPECONTRACTVERSION = AttributesEnum.XpeContractVersion.index();
    public static final int XPEEVENTNUMBER = AttributesEnum.XpeEventNumber.index();
    public static final int XPEUUID = AttributesEnum.XpeUuid.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XpeDccWfActionEOVORowImpl() {
    }

    /**
     * Gets XpeDccWfActionEO entity object.
     * @return the XpeDccWfActionEO
     */
    public EntityImpl getXpeDccWfActionEO() {
        return (EntityImpl) getEntity(ENTITY_XPEDCCWFACTIONEO);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Gets the attribute value for XPE_ACTION_STATUS using the alias name XpeActionStatus.
     * @return the XPE_ACTION_STATUS
     */
    public String getXpeActionStatus() {
        return (String) getAttributeInternal(XPEACTIONSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for XPE_ACTION_STATUS using the alias name XpeActionStatus.
     * @param value value to set the XPE_ACTION_STATUS
     */
    public void setXpeActionStatus(String value) {
        setAttributeInternal(XPEACTIONSTATUS, value);
    }

    /**
     * Gets the attribute value for XPE_APPROVER_EMAIL using the alias name XpeApproverEmail.
     * @return the XPE_APPROVER_EMAIL
     */
    public String getXpeApproverEmail() {
        return (String) getAttributeInternal(XPEAPPROVEREMAIL);
    }

    /**
     * Sets <code>value</code> as attribute value for XPE_APPROVER_EMAIL using the alias name XpeApproverEmail.
     * @param value value to set the XPE_APPROVER_EMAIL
     */
    public void setXpeApproverEmail(String value) {
        setAttributeInternal(XPEAPPROVEREMAIL, value);
    }

    /**
     * Gets the attribute value for XPE_APPROVER_SEQUENCE using the alias name XpeApproverSequence.
     * @return the XPE_APPROVER_SEQUENCE
     */
    public String getXpeApproverSequence() {
        return (String) getAttributeInternal(XPEAPPROVERSEQUENCE);
    }

    /**
     * Sets <code>value</code> as attribute value for XPE_APPROVER_SEQUENCE using the alias name XpeApproverSequence.
     * @param value value to set the XPE_APPROVER_SEQUENCE
     */
    public void setXpeApproverSequence(String value) {
        setAttributeInternal(XPEAPPROVERSEQUENCE, value);
    }

    /**
     * Gets the attribute value for XPE_CONTRACT_ID using the alias name XpeContractId.
     * @return the XPE_CONTRACT_ID
     */
    public String getXpeContractId() {
        return (String) getAttributeInternal(XPECONTRACTID);
    }

    /**
     * Sets <code>value</code> as attribute value for XPE_CONTRACT_ID using the alias name XpeContractId.
     * @param value value to set the XPE_CONTRACT_ID
     */
    public void setXpeContractId(String value) {
        setAttributeInternal(XPECONTRACTID, value);
    }

    /**
     * Gets the attribute value for XPE_CONTRACT_VERSION using the alias name XpeContractVersion.
     * @return the XPE_CONTRACT_VERSION
     */
    public String getXpeContractVersion() {
        return (String) getAttributeInternal(XPECONTRACTVERSION);
    }

    /**
     * Sets <code>value</code> as attribute value for XPE_CONTRACT_VERSION using the alias name XpeContractVersion.
     * @param value value to set the XPE_CONTRACT_VERSION
     */
    public void setXpeContractVersion(String value) {
        setAttributeInternal(XPECONTRACTVERSION, value);
    }

    /**
     * Gets the attribute value for XPE_EVENT_NUMBER using the alias name XpeEventNumber.
     * @return the XPE_EVENT_NUMBER
     */
    public String getXpeEventNumber() {
        return (String) getAttributeInternal(XPEEVENTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for XPE_EVENT_NUMBER using the alias name XpeEventNumber.
     * @param value value to set the XPE_EVENT_NUMBER
     */
    public void setXpeEventNumber(String value) {
        setAttributeInternal(XPEEVENTNUMBER, value);
    }

    /**
     * Gets the attribute value for XPE_UUID using the alias name XpeUuid.
     * @return the XPE_UUID
     */
    public String getXpeUuid() {
        return (String) getAttributeInternal(XPEUUID);
    }

    /**
     * Sets <code>value</code> as attribute value for XPE_UUID using the alias name XpeUuid.
     * @param value value to set the XPE_UUID
     */
    public void setXpeUuid(String value) {
        setAttributeInternal(XPEUUID, value);
    }
}

