package model.views.entitybased;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 12 23:09:18 EST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XpeDccCfgAccountingEOVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public XpeDccCfgAccountingEOVOImpl() {
    }

    /**
     * Returns the variable value for bind_AccountingClass.
     * @return variable value for bind_AccountingClass
     */
    public String getbind_AccountingClass() {
        return (String) ensureVariableManager().getVariableValue("bind_AccountingClass");
    }

    /**
     * Sets <code>value</code> for variable bind_AccountingClass.
     * @param value value to bind as bind_AccountingClass
     */
    public void setbind_AccountingClass(String value) {
        ensureVariableManager().setVariableValue("bind_AccountingClass", value);
    }

    /**
     * Returns the variable value for bind_DealClass.
     * @return variable value for bind_DealClass
     */
    public String getbind_DealClass() {
        return (String) ensureVariableManager().getVariableValue("bind_DealClass");
    }

    /**
     * Sets <code>value</code> for variable bind_DealClass.
     * @param value value to bind as bind_DealClass
     */
    public void setbind_DealClass(String value) {
        ensureVariableManager().setVariableValue("bind_DealClass", value);
    }

    /**
     * Returns the variable value for bind_EntryType.
     * @return variable value for bind_EntryType
     */
    public String getbind_EntryType() {
        return (String) ensureVariableManager().getVariableValue("bind_EntryType");
    }

    /**
     * Sets <code>value</code> for variable bind_EntryType.
     * @param value value to bind as bind_EntryType
     */
    public void setbind_EntryType(String value) {
        ensureVariableManager().setVariableValue("bind_EntryType", value);
    }

    /**
     * Returns the variable value for bind_MaterialCategory.
     * @return variable value for bind_MaterialCategory
     */
    public String getbind_MaterialCategory() {
        return (String) ensureVariableManager().getVariableValue("bind_MaterialCategory");
    }

    /**
     * Sets <code>value</code> for variable bind_MaterialCategory.
     * @param value value to bind as bind_MaterialCategory
     */
    public void setbind_MaterialCategory(String value) {
        ensureVariableManager().setVariableValue("bind_MaterialCategory", value);
    }

    /**
     * Returns the variable value for bind_ProductService.
     * @return variable value for bind_ProductService
     */
    public String getbind_ProductService() {
        return (String) ensureVariableManager().getVariableValue("bind_ProductService");
    }

    /**
     * Sets <code>value</code> for variable bind_ProductService.
     * @param value value to bind as bind_ProductService
     */
    public void setbind_ProductService(String value) {
        ensureVariableManager().setVariableValue("bind_ProductService", value);
    }

    /**
     * Returns the variable value for bind_SiteId.
     * @return variable value for bind_SiteId
     */
    public String getbind_SiteId() {
        return (String) ensureVariableManager().getVariableValue("bind_SiteId");
    }

    /**
     * Sets <code>value</code> for variable bind_SiteId.
     * @param value value to bind as bind_SiteId
     */
    public void setbind_SiteId(String value) {
        ensureVariableManager().setVariableValue("bind_SiteId", value);
    }
}

