package model.views.entitybased;

import java.sql.Timestamp;

import model.entities.XpeDccCfgGeneralCnvEOImpl;

import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 28 22:07:38 EST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XpeDccCfgGeneralCnvEOVORowImpl extends ViewRowImpl {


    public static final int ENTITY_XPEDCCCFGGENERALCNVEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        GeneralCnvId,
        CarrierId,
        DestinationId,
        MaterialId,
        OriginId,
        PcsShortNameId,
        ConversionValue,
        TranslationConsumer,
        CreatedBy,
        CreatedDate,
        LastUpdatedBy,
        LastUpdatedDate,
        Inactive,
        InactiveDate,
        TohBusinessType,
        TohPayType,
        Country,
        TohBusnPaySrc,
        XpeDccCfgCarriers_LOV,
        XpeDccCfgOrigins_LOV,
        XpeDccCfgDestinations_LOV,
        XpeDccCfgProductService_LOV,
        XpeDccCfgPCSShortNames_LOV,
        LookupSharedAppModule_TranslationConsumerLOV,
        LookupSharedAppModule_XpeDccDicNewContractSetupROVO1,
        PsCountryTblROVO1;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int GENERALCNVID = AttributesEnum.GeneralCnvId.index();
    public static final int CARRIERID = AttributesEnum.CarrierId.index();
    public static final int DESTINATIONID = AttributesEnum.DestinationId.index();
    public static final int MATERIALID = AttributesEnum.MaterialId.index();
    public static final int ORIGINID = AttributesEnum.OriginId.index();
    public static final int PCSSHORTNAMEID = AttributesEnum.PcsShortNameId.index();
    public static final int CONVERSIONVALUE = AttributesEnum.ConversionValue.index();
    public static final int TRANSLATIONCONSUMER = AttributesEnum.TranslationConsumer.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int INACTIVE = AttributesEnum.Inactive.index();
    public static final int INACTIVEDATE = AttributesEnum.InactiveDate.index();
    public static final int TOHBUSINESSTYPE = AttributesEnum.TohBusinessType.index();
    public static final int TOHPAYTYPE = AttributesEnum.TohPayType.index();
    public static final int COUNTRY = AttributesEnum.Country.index();
    public static final int TOHBUSNPAYSRC = AttributesEnum.TohBusnPaySrc.index();
    public static final int XPEDCCCFGCARRIERS_LOV = AttributesEnum.XpeDccCfgCarriers_LOV.index();
    public static final int XPEDCCCFGORIGINS_LOV = AttributesEnum.XpeDccCfgOrigins_LOV.index();
    public static final int XPEDCCCFGDESTINATIONS_LOV = AttributesEnum.XpeDccCfgDestinations_LOV.index();
    public static final int XPEDCCCFGPRODUCTSERVICE_LOV = AttributesEnum.XpeDccCfgProductService_LOV.index();
    public static final int XPEDCCCFGPCSSHORTNAMES_LOV = AttributesEnum.XpeDccCfgPCSShortNames_LOV.index();
    public static final int LOOKUPSHAREDAPPMODULE_TRANSLATIONCONSUMERLOV =
        AttributesEnum.LookupSharedAppModule_TranslationConsumerLOV.index();
    public static final int LOOKUPSHAREDAPPMODULE_XPEDCCDICNEWCONTRACTSETUPROVO1 =
        AttributesEnum.LookupSharedAppModule_XpeDccDicNewContractSetupROVO1.index();
    public static final int PSCOUNTRYTBLROVO1 = AttributesEnum.PsCountryTblROVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XpeDccCfgGeneralCnvEOVORowImpl() {
    }

    /**
     * Gets XpeDccCfgGeneralCnvEO entity object.
     * @return the XpeDccCfgGeneralCnvEO
     */
    public XpeDccCfgGeneralCnvEOImpl getXpeDccCfgGeneralCnvEO() {
        return (XpeDccCfgGeneralCnvEOImpl) getEntity(ENTITY_XPEDCCCFGGENERALCNVEO);
    }

    /**
     * Gets the attribute value for GENERAL_CNV_ID using the alias name GeneralCnvId.
     * @return the GENERAL_CNV_ID
     */
    public String getGeneralCnvId() {
        return (String) getAttributeInternal(GENERALCNVID);
    }

    /**
     * Sets <code>value</code> as attribute value for GENERAL_CNV_ID using the alias name GeneralCnvId.
     * @param value value to set the GENERAL_CNV_ID
     */
    public void setGeneralCnvId(String value) {
        setAttributeInternal(GENERALCNVID, value);
    }

    /**
     * Gets the attribute value for CARRIER_ID using the alias name CarrierId.
     * @return the CARRIER_ID
     */
    public String getCarrierId() {
        return (String) getAttributeInternal(CARRIERID);
    }

    /**
     * Sets <code>value</code> as attribute value for CARRIER_ID using the alias name CarrierId.
     * @param value value to set the CARRIER_ID
     */
    public void setCarrierId(String value) {
        setAttributeInternal(CARRIERID, value);
    }

    /**
     * Gets the attribute value for DESTINATION_ID using the alias name DestinationId.
     * @return the DESTINATION_ID
     */
    public String getDestinationId() {
        return (String) getAttributeInternal(DESTINATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for DESTINATION_ID using the alias name DestinationId.
     * @param value value to set the DESTINATION_ID
     */
    public void setDestinationId(String value) {
        setAttributeInternal(DESTINATIONID, value);
    }

    /**
     * Gets the attribute value for MATERIAL_ID using the alias name MaterialId.
     * @return the MATERIAL_ID
     */
    public String getMaterialId() {
        return (String) getAttributeInternal(MATERIALID);
    }

    /**
     * Sets <code>value</code> as attribute value for MATERIAL_ID using the alias name MaterialId.
     * @param value value to set the MATERIAL_ID
     */
    public void setMaterialId(String value) {
        setAttributeInternal(MATERIALID, value);
    }

    /**
     * Gets the attribute value for ORIGIN_ID using the alias name OriginId.
     * @return the ORIGIN_ID
     */
    public String getOriginId() {
        return (String) getAttributeInternal(ORIGINID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORIGIN_ID using the alias name OriginId.
     * @param value value to set the ORIGIN_ID
     */
    public void setOriginId(String value) {
        setAttributeInternal(ORIGINID, value);
    }

    /**
     * Gets the attribute value for PCS_SHORT_NAME_ID using the alias name PcsShortNameId.
     * @return the PCS_SHORT_NAME_ID
     */
    public String getPcsShortNameId() {
        return (String) getAttributeInternal(PCSSHORTNAMEID);
    }

    /**
     * Sets <code>value</code> as attribute value for PCS_SHORT_NAME_ID using the alias name PcsShortNameId.
     * @param value value to set the PCS_SHORT_NAME_ID
     */
    public void setPcsShortNameId(String value) {
        setAttributeInternal(PCSSHORTNAMEID, value);
    }

    /**
     * Gets the attribute value for CONVERSION_VALUE using the alias name ConversionValue.
     * @return the CONVERSION_VALUE
     */
    public String getConversionValue() {
        return (String) getAttributeInternal(CONVERSIONVALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for CONVERSION_VALUE using the alias name ConversionValue.
     * @param value value to set the CONVERSION_VALUE
     */
    public void setConversionValue(String value) {
        setAttributeInternal(CONVERSIONVALUE, value);
    }

    /**
     * Gets the attribute value for TRANSLATION_CONSUMER using the alias name TranslationConsumer.
     * @return the TRANSLATION_CONSUMER
     */
    public String getTranslationConsumer() {
        return (String) getAttributeInternal(TRANSLATIONCONSUMER);
    }

    /**
     * Sets <code>value</code> as attribute value for TRANSLATION_CONSUMER using the alias name TranslationConsumer.
     * @param value value to set the TRANSLATION_CONSUMER
     */
    public void setTranslationConsumer(String value) {
        setAttributeInternal(TRANSLATIONCONSUMER, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }


    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }


    /**
     * Gets the attribute value for INACTIVE using the alias name Inactive.
     * @return the INACTIVE
     */
    public String getInactive() {
        return (String) getAttributeInternal(INACTIVE);
    }

    /**
     * Sets <code>value</code> as attribute value for INACTIVE using the alias name Inactive.
     * @param value value to set the INACTIVE
     */
    public void setInactive(String value) {
        setAttributeInternal(INACTIVE, value);
    }

    /**
     * Gets the attribute value for INACTIVE_DATE using the alias name InactiveDate.
     * @return the INACTIVE_DATE
     */
    public Timestamp getInactiveDate() {
        return (Timestamp) getAttributeInternal(INACTIVEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for INACTIVE_DATE using the alias name InactiveDate.
     * @param value value to set the INACTIVE_DATE
     */
    public void setInactiveDate(Timestamp value) {
        setAttributeInternal(INACTIVEDATE, value);
    }

    /**
     * Gets the attribute value for TOH_BUSINESS_TYPE using the alias name TohBusinessType.
     * @return the TOH_BUSINESS_TYPE
     */
    public String getTohBusinessType() {
        return (String) getAttributeInternal(TOHBUSINESSTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for TOH_BUSINESS_TYPE using the alias name TohBusinessType.
     * @param value value to set the TOH_BUSINESS_TYPE
     */
    public void setTohBusinessType(String value) {
        setAttributeInternal(TOHBUSINESSTYPE, value);
    }

    /**
     * Gets the attribute value for TOH_PAY_TYPE using the alias name TohPayType.
     * @return the TOH_PAY_TYPE
     */
    public String getTohPayType() {
        return (String) getAttributeInternal(TOHPAYTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for TOH_PAY_TYPE using the alias name TohPayType.
     * @param value value to set the TOH_PAY_TYPE
     */
    public void setTohPayType(String value) {
        setAttributeInternal(TOHPAYTYPE, value);
    }

    /**
     * Gets the attribute value for COUNTRY using the alias name Country.
     * @return the COUNTRY
     */
    public String getCountry() {
        return (String) getAttributeInternal(COUNTRY);
    }

    /**
     * Sets <code>value</code> as attribute value for COUNTRY using the alias name Country.
     * @param value value to set the COUNTRY
     */
    public void setCountry(String value) {
        setAttributeInternal(COUNTRY, value);
    }

    /**
     * Gets the attribute value for TOH_BUSN_PAY_SRC using the alias name TohBusnPaySrc.
     * @return the TOH_BUSN_PAY_SRC
     */
    public String getTohBusnPaySrc() {
        return (String) getAttributeInternal(TOHBUSNPAYSRC);
    }

    /**
     * Sets <code>value</code> as attribute value for TOH_BUSN_PAY_SRC using the alias name TohBusnPaySrc.
     * @param value value to set the TOH_BUSN_PAY_SRC
     */
    public void setTohBusnPaySrc(String value) {
        setAttributeInternal(TOHBUSNPAYSRC, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> XpeDccCfgCarriers_LOV.
     */
    public RowSet getXpeDccCfgCarriers_LOV() {
        return (RowSet) getAttributeInternal(XPEDCCCFGCARRIERS_LOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> XpeDccCfgOrigins_LOV.
     */
    public RowSet getXpeDccCfgOrigins_LOV() {
        return (RowSet) getAttributeInternal(XPEDCCCFGORIGINS_LOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> XpeDccCfgDestinations_LOV.
     */
    public RowSet getXpeDccCfgDestinations_LOV() {
        return (RowSet) getAttributeInternal(XPEDCCCFGDESTINATIONS_LOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> XpeDccCfgProductService_LOV.
     */
    public RowSet getXpeDccCfgProductService_LOV() {
        return (RowSet) getAttributeInternal(XPEDCCCFGPRODUCTSERVICE_LOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> XpeDccCfgPCSShortNames_LOV.
     */
    public RowSet getXpeDccCfgPCSShortNames_LOV() {
        return (RowSet) getAttributeInternal(XPEDCCCFGPCSSHORTNAMES_LOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LookupSharedAppModule_TranslationConsumerLOV.
     */
    public RowSet getLookupSharedAppModule_TranslationConsumerLOV() {
        return (RowSet) getAttributeInternal(LOOKUPSHAREDAPPMODULE_TRANSLATIONCONSUMERLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LookupSharedAppModule_XpeDccDicNewContractSetupROVO1.
     */
    public RowSet getLookupSharedAppModule_XpeDccDicNewContractSetupROVO1() {
        return (RowSet) getAttributeInternal(LOOKUPSHAREDAPPMODULE_XPEDCCDICNEWCONTRACTSETUPROVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PsCountryTblROVO1.
     */
    public RowSet getPsCountryTblROVO1() {
        return (RowSet) getAttributeInternal(PSCOUNTRYTBLROVO1);
    }
}

