package model.views.entitybased;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 18 15:48:25 EDT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XpeDccWfEventEOVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public XpeDccWfEventEOVOImpl() {
    }

    /**
     * Returns the variable value for bind_eventNumber.
     * @return variable value for bind_eventNumber
     */
    public String getbind_eventNumber() {
        return (String) ensureVariableManager().getVariableValue("bind_eventNumber");
    }

    /**
     * Sets <code>value</code> for variable bind_eventNumber.
     * @param value value to bind as bind_eventNumber
     */
    public void setbind_eventNumber(String value) {
        ensureVariableManager().setVariableValue("bind_eventNumber", value);
    }

    /**
     * Returns the variable value for bind_contractId.
     * @return variable value for bind_contractId
     */
    public String getbind_contractId() {
        return (String) ensureVariableManager().getVariableValue("bind_contractId");
    }

    /**
     * Sets <code>value</code> for variable bind_contractId.
     * @param value value to bind as bind_contractId
     */
    public void setbind_contractId(String value) {
        ensureVariableManager().setVariableValue("bind_contractId", value);
    }

    /**
     * Returns the variable value for bind_contractVersion.
     * @return variable value for bind_contractVersion
     */
    public String getbind_contractVersion() {
        return (String) ensureVariableManager().getVariableValue("bind_contractVersion");
    }

    /**
     * Sets <code>value</code> for variable bind_contractVersion.
     * @param value value to bind as bind_contractVersion
     */
    public void setbind_contractVersion(String value) {
        ensureVariableManager().setVariableValue("bind_contractVersion", value);
    }

    /**
     * Returns the variable value for bind_eventType.
     * @return variable value for bind_eventType
     */
    public String getbind_eventType() {
        return (String) ensureVariableManager().getVariableValue("bind_eventType");
    }

    /**
     * Sets <code>value</code> for variable bind_eventType.
     * @param value value to bind as bind_eventType
     */
    public void setbind_eventType(String value) {
        ensureVariableManager().setVariableValue("bind_eventType", value);
    }
}

