package model.views.entitybased;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 18 15:48:25 EDT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XpeDccWfEventEOVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public XpeDccWfEventEOVOImpl() {
    }

    /**
     * Returns the variable value for bind_eventNumber.
     * @return variable value for bind_eventNumber
     */
    public String getbind_eventNumber() {
        return (String) ensureVariableManager().getVariableValue("bind_eventNumber");
    }

    /**
     * Sets <code>value</code> for variable bind_eventNumber.
     * @param value value to bind as bind_eventNumber
     */
    public void setbind_eventNumber(String value) {
        ensureVariableManager().setVariableValue("bind_eventNumber", value);
    }
}

