package model.views.entitybased;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 28 22:07:38 EST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XpeDccCfgGeneralCnvEOVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public XpeDccCfgGeneralCnvEOVOImpl() {
    }

    /**
     * Returns the variable value for bind_CarrierId.
     * @return variable value for bind_CarrierId
     */
    public String getbind_CarrierId() {
        return (String) ensureVariableManager().getVariableValue("bind_CarrierId");
    }

    /**
     * Sets <code>value</code> for variable bind_CarrierId.
     * @param value value to bind as bind_CarrierId
     */
    public void setbind_CarrierId(String value) {
        ensureVariableManager().setVariableValue("bind_CarrierId", value);
    }

    /**
     * Returns the variable value for bind_DestinationId.
     * @return variable value for bind_DestinationId
     */
    public String getbind_DestinationId() {
        return (String) ensureVariableManager().getVariableValue("bind_DestinationId");
    }

    /**
     * Sets <code>value</code> for variable bind_DestinationId.
     * @param value value to bind as bind_DestinationId
     */
    public void setbind_DestinationId(String value) {
        ensureVariableManager().setVariableValue("bind_DestinationId", value);
    }

    /**
     * Returns the variable value for bind_MaterialId.
     * @return variable value for bind_MaterialId
     */
    public String getbind_MaterialId() {
        return (String) ensureVariableManager().getVariableValue("bind_MaterialId");
    }

    /**
     * Sets <code>value</code> for variable bind_MaterialId.
     * @param value value to bind as bind_MaterialId
     */
    public void setbind_MaterialId(String value) {
        ensureVariableManager().setVariableValue("bind_MaterialId", value);
    }

    /**
     * Returns the variable value for bind_OriginId.
     * @return variable value for bind_OriginId
     */
    public String getbind_OriginId() {
        return (String) ensureVariableManager().getVariableValue("bind_OriginId");
    }

    /**
     * Sets <code>value</code> for variable bind_OriginId.
     * @param value value to bind as bind_OriginId
     */
    public void setbind_OriginId(String value) {
        ensureVariableManager().setVariableValue("bind_OriginId", value);
    }

    /**
     * Returns the variable value for bind_PcsShortNameId.
     * @return variable value for bind_PcsShortNameId
     */
    public String getbind_PcsShortNameId() {
        return (String) ensureVariableManager().getVariableValue("bind_PcsShortNameId");
    }

    /**
     * Sets <code>value</code> for variable bind_PcsShortNameId.
     * @param value value to bind as bind_PcsShortNameId
     */
    public void setbind_PcsShortNameId(String value) {
        ensureVariableManager().setVariableValue("bind_PcsShortNameId", value);
    }

    /**
     * Returns the variable value for bind_TranslationConsumer.
     * @return variable value for bind_TranslationConsumer
     */
    public String getbind_TranslationConsumer() {
        return (String) ensureVariableManager().getVariableValue("bind_TranslationConsumer");
    }

    /**
     * Sets <code>value</code> for variable bind_TranslationConsumer.
     * @param value value to bind as bind_TranslationConsumer
     */
    public void setbind_TranslationConsumer(String value) {
        ensureVariableManager().setVariableValue("bind_TranslationConsumer", value);
    }

    /**
     * Returns the variable value for bind_Country.
     * @return variable value for bind_Country
     */
    public String getbind_Country() {
        return (String) ensureVariableManager().getVariableValue("bind_Country");
    }

    /**
     * Sets <code>value</code> for variable bind_Country.
     * @param value value to bind as bind_Country
     */
    public void setbind_Country(String value) {
        ensureVariableManager().setVariableValue("bind_Country", value);
    }
}

