package model.views.entitybased;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 12 15:50:50 EDT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XpeDccCfgPcsshortnamesEOVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public XpeDccCfgPcsshortnamesEOVOImpl() {
    }

    /**
     * Returns the variable value for bind_PcsShortNameId.
     * @return variable value for bind_PcsShortNameId
     */
    public String getbind_PcsShortNameId() {
        return (String) ensureVariableManager().getVariableValue("bind_PcsShortNameId");
    }

    /**
     * Sets <code>value</code> for variable bind_PcsShortNameId.
     * @param value value to bind as bind_PcsShortNameId
     */
    public void setbind_PcsShortNameId(String value) {
        ensureVariableManager().setVariableValue("bind_PcsShortNameId", value);
    }

    /**
     * Returns the variable value for bind_PcsShortName.
     * @return variable value for bind_PcsShortName
     */
    public String getbind_PcsShortName() {
        return (String) ensureVariableManager().getVariableValue("bind_PcsShortName");
    }

    /**
     * Sets <code>value</code> for variable bind_PcsShortName.
     * @param value value to bind as bind_PcsShortName
     */
    public void setbind_PcsShortName(String value) {
        ensureVariableManager().setVariableValue("bind_PcsShortName", value);
    }

    /**
     * Returns the variable value for bind_BillCycleId.
     * @return variable value for bind_BillCycleId
     */
    public String getbind_BillCycleId() {
        return (String) ensureVariableManager().getVariableValue("bind_BillCycleId");
    }

    /**
     * Sets <code>value</code> for variable bind_BillCycleId.
     * @param value value to bind as bind_BillCycleId
     */
    public void setbind_BillCycleId(String value) {
        ensureVariableManager().setVariableValue("bind_BillCycleId", value);
    }

    /**
     * Returns the variable value for bind_CovId.
     * @return variable value for bind_CovId
     */
    public String getbind_CovId() {
        return (String) ensureVariableManager().getVariableValue("bind_CovId");
    }

    /**
     * Sets <code>value</code> for variable bind_CovId.
     * @param value value to bind as bind_CovId
     */
    public void setbind_CovId(String value) {
        ensureVariableManager().setVariableValue("bind_CovId", value);
    }
}

