package model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 18 01:49:13 EDT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PsCisXpeImportViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PsCisXpeImportViewImpl() {
    }
}

