package model;

import java.sql.Timestamp;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 23 17:22:56 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XpeDccContractVersionViewRowImpl extends ViewRowImpl {


    public static final int ENTITY_XPEDCCCONTRACTVERSION = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        XpeContractId,
        XpeContractVersion,
        XpeContractStatus,
        XpeStartDate,
        XpeEndDate,
        XpeNewTermMode,
        CreatedBy,
        UpdatedBy,
        XpeBillOptionsSet,
        XpeAcctgOptionsSet,
        XpeContractTemplate,
        BusinessUnitGl,
        CurrencyCd,
        XpeAgreementType,
        XpeAsOfDate,
        XpeWasteType,
        XpeContractSubType,
        XpeTermId,
        SalesPerson,
        XpeContractDirection,
        XpeTermAgreement,
        XpeValueTransaction,
        XpeVarianceBudget,
        XpePaymentHistory,
        XpePaymentMethod,
        XpeEstDisposalVol,
        XpeExistingCustomer,
        XpeJustification,
        XpeCreditLimit,
        XpeDccContractNotesView,
        XpeDccContractLineView,
        XpeDccWorkflowView,
        XpeDccContractsAttachmentsView,
        XpeDccTermsContractEOVO,
        XpeDccDicContractStatus1,
        XpeDccDicOptionsRenewal1,
        XpeDccDicOptionsBilling1,
        XpeDccDicOptionsAccounting1,
        XpeDccDicBusinessUnits1,
        XpeDccDicCurrency1,
        LookupSharedAppModule_XpeDccDicWasteType,
        LookupSharedAppModule_XpeDccDicContractSubtype,
        LookupSharedAppModule_XpeDccDicAgreementType,
        XpeDccMasterTermsLOV,
        LookupSharedAppModule_XpeDccDicNewContractSetupROVO1,
        PsCurrencyCdTblROVO1,
        PsSalesPersonROVO1,
        PcBusUnitTblGlROVO1,
        LookupSharedAppModule_YORNLOV;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int XPECONTRACTID = AttributesEnum.XpeContractId.index();
    public static final int XPECONTRACTVERSION = AttributesEnum.XpeContractVersion.index();
    public static final int XPECONTRACTSTATUS = AttributesEnum.XpeContractStatus.index();
    public static final int XPESTARTDATE = AttributesEnum.XpeStartDate.index();
    public static final int XPEENDDATE = AttributesEnum.XpeEndDate.index();
    public static final int XPENEWTERMMODE = AttributesEnum.XpeNewTermMode.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int XPEBILLOPTIONSSET = AttributesEnum.XpeBillOptionsSet.index();
    public static final int XPEACCTGOPTIONSSET = AttributesEnum.XpeAcctgOptionsSet.index();
    public static final int XPECONTRACTTEMPLATE = AttributesEnum.XpeContractTemplate.index();
    public static final int BUSINESSUNITGL = AttributesEnum.BusinessUnitGl.index();
    public static final int CURRENCYCD = AttributesEnum.CurrencyCd.index();
    public static final int XPEAGREEMENTTYPE = AttributesEnum.XpeAgreementType.index();
    public static final int XPEASOFDATE = AttributesEnum.XpeAsOfDate.index();
    public static final int XPEWASTETYPE = AttributesEnum.XpeWasteType.index();
    public static final int XPECONTRACTSUBTYPE = AttributesEnum.XpeContractSubType.index();
    public static final int XPETERMID = AttributesEnum.XpeTermId.index();
    public static final int SALESPERSON = AttributesEnum.SalesPerson.index();
    public static final int XPECONTRACTDIRECTION = AttributesEnum.XpeContractDirection.index();
    public static final int XPETERMAGREEMENT = AttributesEnum.XpeTermAgreement.index();
    public static final int XPEVALUETRANSACTION = AttributesEnum.XpeValueTransaction.index();
    public static final int XPEVARIANCEBUDGET = AttributesEnum.XpeVarianceBudget.index();
    public static final int XPEPAYMENTHISTORY = AttributesEnum.XpePaymentHistory.index();
    public static final int XPEPAYMENTMETHOD = AttributesEnum.XpePaymentMethod.index();
    public static final int XPEESTDISPOSALVOL = AttributesEnum.XpeEstDisposalVol.index();
    public static final int XPEEXISTINGCUSTOMER = AttributesEnum.XpeExistingCustomer.index();
    public static final int XPEJUSTIFICATION = AttributesEnum.XpeJustification.index();
    public static final int XPECREDITLIMIT = AttributesEnum.XpeCreditLimit.index();
    public static final int XPEDCCCONTRACTNOTESVIEW = AttributesEnum.XpeDccContractNotesView.index();
    public static final int XPEDCCCONTRACTLINEVIEW = AttributesEnum.XpeDccContractLineView.index();
    public static final int XPEDCCWORKFLOWVIEW = AttributesEnum.XpeDccWorkflowView.index();
    public static final int XPEDCCCONTRACTSATTACHMENTSVIEW = AttributesEnum.XpeDccContractsAttachmentsView.index();
    public static final int XPEDCCTERMSCONTRACTEOVO = AttributesEnum.XpeDccTermsContractEOVO.index();
    public static final int XPEDCCDICCONTRACTSTATUS1 = AttributesEnum.XpeDccDicContractStatus1.index();
    public static final int XPEDCCDICOPTIONSRENEWAL1 = AttributesEnum.XpeDccDicOptionsRenewal1.index();
    public static final int XPEDCCDICOPTIONSBILLING1 = AttributesEnum.XpeDccDicOptionsBilling1.index();
    public static final int XPEDCCDICOPTIONSACCOUNTING1 = AttributesEnum.XpeDccDicOptionsAccounting1.index();
    public static final int XPEDCCDICBUSINESSUNITS1 = AttributesEnum.XpeDccDicBusinessUnits1.index();
    public static final int XPEDCCDICCURRENCY1 = AttributesEnum.XpeDccDicCurrency1.index();
    public static final int LOOKUPSHAREDAPPMODULE_XPEDCCDICWASTETYPE =
        AttributesEnum.LookupSharedAppModule_XpeDccDicWasteType.index();
    public static final int LOOKUPSHAREDAPPMODULE_XPEDCCDICCONTRACTSUBTYPE =
        AttributesEnum.LookupSharedAppModule_XpeDccDicContractSubtype.index();
    public static final int LOOKUPSHAREDAPPMODULE_XPEDCCDICAGREEMENTTYPE =
        AttributesEnum.LookupSharedAppModule_XpeDccDicAgreementType.index();
    public static final int XPEDCCMASTERTERMSLOV = AttributesEnum.XpeDccMasterTermsLOV.index();
    public static final int LOOKUPSHAREDAPPMODULE_XPEDCCDICNEWCONTRACTSETUPROVO1 =
        AttributesEnum.LookupSharedAppModule_XpeDccDicNewContractSetupROVO1.index();
    public static final int PSCURRENCYCDTBLROVO1 = AttributesEnum.PsCurrencyCdTblROVO1.index();
    public static final int PSSALESPERSONROVO1 = AttributesEnum.PsSalesPersonROVO1.index();
    public static final int PCBUSUNITTBLGLROVO1 = AttributesEnum.PcBusUnitTblGlROVO1.index();
    public static final int LOOKUPSHAREDAPPMODULE_YORNLOV = AttributesEnum.LookupSharedAppModule_YORNLOV.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XpeDccContractVersionViewRowImpl() {
    }

    /**
     * Gets XpeDccContractVersion entity object.
     * @return the XpeDccContractVersion
     */
    public XpeDccContractVersionImpl getXpeDccContractVersion() {
        return (XpeDccContractVersionImpl) getEntity(ENTITY_XPEDCCCONTRACTVERSION);
    }

    /**
     * Gets the attribute value for XPE_CONTRACT_ID using the alias name XpeContractId.
     * @return the XPE_CONTRACT_ID
     */
    public String getXpeContractId() {
        return (String) getAttributeInternal(XPECONTRACTID);
    }

    /**
     * Sets <code>value</code> as attribute value for XPE_CONTRACT_ID using the alias name XpeContractId.
     * @param value value to set the XPE_CONTRACT_ID
     */
    public void setXpeContractId(String value) {
        setAttributeInternal(XPECONTRACTID, value);
    }

    /**
     * Gets the attribute value for XPE_CONTRACT_VERSION using the alias name XpeContractVersion.
     * @return the XPE_CONTRACT_VERSION
     */
    public String getXpeContractVersion() {
        return (String) getAttributeInternal(XPECONTRACTVERSION);
    }


    /**
     * Sets <code>value</code> as attribute value for XPE_CONTRACT_VERSION using the alias name XpeContractVersion.
     * @param value value to set the XPE_CONTRACT_VERSION
     */
    public void setXpeContractVersion(String value) {
        setAttributeInternal(XPECONTRACTVERSION, value);
    }

    /**
     * Gets the attribute value for XPE_CONTRACT_STATUS using the alias name XpeContractStatus.
     * @return the XPE_CONTRACT_STATUS
     */
    public String getXpeContractStatus() {
        return (String) getAttributeInternal(XPECONTRACTSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for XPE_CONTRACT_STATUS using the alias name XpeContractStatus.
     * @param value value to set the XPE_CONTRACT_STATUS
     */
    public void setXpeContractStatus(String value) {
        setAttributeInternal(XPECONTRACTSTATUS, value);
    }

    /**
     * Gets the attribute value for XPE_START_DATE using the alias name XpeStartDate.
     * @return the XPE_START_DATE
     */
    public Timestamp getXpeStartDate() {
        return (Timestamp) getAttributeInternal(XPESTARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for XPE_START_DATE using the alias name XpeStartDate.
     * @param value value to set the XPE_START_DATE
     */
    public void setXpeStartDate(Timestamp value) {
        setAttributeInternal(XPESTARTDATE, value);
    }

    /**
     * Gets the attribute value for XPE_END_DATE using the alias name XpeEndDate.
     * @return the XPE_END_DATE
     */
    public Timestamp getXpeEndDate() {
        return (Timestamp) getAttributeInternal(XPEENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for XPE_END_DATE using the alias name XpeEndDate.
     * @param value value to set the XPE_END_DATE
     */
    public void setXpeEndDate(Timestamp value) {
        setAttributeInternal(XPEENDDATE, value);
    }

    /**
     * Gets the attribute value for XPE_NEW_TERM_MODE using the alias name XpeNewTermMode.
     * @return the XPE_NEW_TERM_MODE
     */
    public String getXpeNewTermMode() {
        return (String) getAttributeInternal(XPENEWTERMMODE);
    }

    /**
     * Sets <code>value</code> as attribute value for XPE_NEW_TERM_MODE using the alias name XpeNewTermMode.
     * @param value value to set the XPE_NEW_TERM_MODE
     */
    public void setXpeNewTermMode(String value) {
        setAttributeInternal(XPENEWTERMMODE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for UPDATED_BY using the alias name UpdatedBy.
     * @return the UPDATED_BY
     */
    public String getUpdatedBy() {
        return (String) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for UPDATED_BY using the alias name UpdatedBy.
     * @param value value to set the UPDATED_BY
     */
    public void setUpdatedBy(String value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for XPE_BILL_OPTIONS_SET using the alias name XpeBillOptionsSet.
     * @return the XPE_BILL_OPTIONS_SET
     */
    public String getXpeBillOptionsSet() {
        return (String) getAttributeInternal(XPEBILLOPTIONSSET);
    }

    /**
     * Sets <code>value</code> as attribute value for XPE_BILL_OPTIONS_SET using the alias name XpeBillOptionsSet.
     * @param value value to set the XPE_BILL_OPTIONS_SET
     */
    public void setXpeBillOptionsSet(String value) {
        setAttributeInternal(XPEBILLOPTIONSSET, value);
    }

    /**
     * Gets the attribute value for XPE_ACCTG_OPTIONS_SET using the alias name XpeAcctgOptionsSet.
     * @return the XPE_ACCTG_OPTIONS_SET
     */
    public String getXpeAcctgOptionsSet() {
        return (String) getAttributeInternal(XPEACCTGOPTIONSSET);
    }

    /**
     * Sets <code>value</code> as attribute value for XPE_ACCTG_OPTIONS_SET using the alias name XpeAcctgOptionsSet.
     * @param value value to set the XPE_ACCTG_OPTIONS_SET
     */
    public void setXpeAcctgOptionsSet(String value) {
        setAttributeInternal(XPEACCTGOPTIONSSET, value);
    }

    /**
     * Gets the attribute value for XPE_CONTRACT_TEMPLATE using the alias name XpeContractTemplate.
     * @return the XPE_CONTRACT_TEMPLATE
     */
    public String getXpeContractTemplate() {
        return (String) getAttributeInternal(XPECONTRACTTEMPLATE);
    }

    /**
     * Sets <code>value</code> as attribute value for XPE_CONTRACT_TEMPLATE using the alias name XpeContractTemplate.
     * @param value value to set the XPE_CONTRACT_TEMPLATE
     */
    public void setXpeContractTemplate(String value) {
        setAttributeInternal(XPECONTRACTTEMPLATE, value);
    }

    /**
     * Gets the attribute value for BUSINESS_UNIT_GL using the alias name BusinessUnitGl.
     * @return the BUSINESS_UNIT_GL
     */
    public String getBusinessUnitGl() {
        return (String) getAttributeInternal(BUSINESSUNITGL);
    }

    /**
     * Sets <code>value</code> as attribute value for BUSINESS_UNIT_GL using the alias name BusinessUnitGl.
     * @param value value to set the BUSINESS_UNIT_GL
     */
    public void setBusinessUnitGl(String value) {
        setAttributeInternal(BUSINESSUNITGL, value);
    }

    /**
     * Gets the attribute value for CURRENCY_CD using the alias name CurrencyCd.
     * @return the CURRENCY_CD
     */
    public String getCurrencyCd() {
        return (String) getAttributeInternal(CURRENCYCD);
    }

    /**
     * Sets <code>value</code> as attribute value for CURRENCY_CD using the alias name CurrencyCd.
     * @param value value to set the CURRENCY_CD
     */
    public void setCurrencyCd(String value) {
        setAttributeInternal(CURRENCYCD, value);
    }

    /**
     * Gets the attribute value for XPE_AGREEMENT_TYPE using the alias name XpeAgreementType.
     * @return the XPE_AGREEMENT_TYPE
     */
    public String getXpeAgreementType() {
        return (String) getAttributeInternal(XPEAGREEMENTTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for XPE_AGREEMENT_TYPE using the alias name XpeAgreementType.
     * @param value value to set the XPE_AGREEMENT_TYPE
     */
    public void setXpeAgreementType(String value) {
        setAttributeInternal(XPEAGREEMENTTYPE, value);
    }

    /**
     * Gets the attribute value for XPE_AS_OF_DATE using the alias name XpeAsOfDate.
     * @return the XPE_AS_OF_DATE
     */
    public Timestamp getXpeAsOfDate() {
        return (Timestamp) getAttributeInternal(XPEASOFDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for XPE_AS_OF_DATE using the alias name XpeAsOfDate.
     * @param value value to set the XPE_AS_OF_DATE
     */
    public void setXpeAsOfDate(Timestamp value) {
        setAttributeInternal(XPEASOFDATE, value);
    }

    /**
     * Gets the attribute value for XPE_WASTE_TYPE using the alias name XpeWasteType.
     * @return the XPE_WASTE_TYPE
     */
    public String getXpeWasteType() {
        return (String) getAttributeInternal(XPEWASTETYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for XPE_WASTE_TYPE using the alias name XpeWasteType.
     * @param value value to set the XPE_WASTE_TYPE
     */
    public void setXpeWasteType(String value) {
        setAttributeInternal(XPEWASTETYPE, value);
    }

    /**
     * Gets the attribute value for XPE_CONTRACT_SUB_TYPE using the alias name XpeContractSubType.
     * @return the XPE_CONTRACT_SUB_TYPE
     */
    public String getXpeContractSubType() {
        return (String) getAttributeInternal(XPECONTRACTSUBTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for XPE_CONTRACT_SUB_TYPE using the alias name XpeContractSubType.
     * @param value value to set the XPE_CONTRACT_SUB_TYPE
     */
    public void setXpeContractSubType(String value) {
        setAttributeInternal(XPECONTRACTSUBTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute XpeTermId.
     * @return the XpeTermId
     */
    public String getXpeTermId() {
        return (String) getAttributeInternal(XPETERMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute XpeTermId.
     * @param value value to set the  XpeTermId
     */
    public void setXpeTermId(String value) {
        setAttributeInternal(XPETERMID, value);
    }

    /**
     * Gets the attribute value for SALES_PERSON using the alias name SalesPerson.
     * @return the SALES_PERSON
     */
    public String getSalesPerson() {
        return (String) getAttributeInternal(SALESPERSON);
    }

    /**
     * Sets <code>value</code> as attribute value for SALES_PERSON using the alias name SalesPerson.
     * @param value value to set the SALES_PERSON
     */
    public void setSalesPerson(String value) {
        setAttributeInternal(SALESPERSON, value);
    }


    /**
     * Gets the attribute value for XPE_CONTRACT_DIRECTION using the alias name XpeContractDirection.
     * @return the XPE_CONTRACT_DIRECTION
     */
    public String getXpeContractDirection() {
        return (String) getAttributeInternal(XPECONTRACTDIRECTION);
    }

    /**
     * Sets <code>value</code> as attribute value for XPE_CONTRACT_DIRECTION using the alias name XpeContractDirection.
     * @param value value to set the XPE_CONTRACT_DIRECTION
     */
    public void setXpeContractDirection(String value) {
        setAttributeInternal(XPECONTRACTDIRECTION, value);
    }

    /**
     * Gets the attribute value for XPE_TERM_AGREEMENT using the alias name XpeTermAgreement.
     * @return the XPE_TERM_AGREEMENT
     */
    public String getXpeTermAgreement() {
        return (String) getAttributeInternal(XPETERMAGREEMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for XPE_TERM_AGREEMENT using the alias name XpeTermAgreement.
     * @param value value to set the XPE_TERM_AGREEMENT
     */
    public void setXpeTermAgreement(String value) {
        setAttributeInternal(XPETERMAGREEMENT, value);
    }

    /**
     * Gets the attribute value for XPE_VALUE_TRANSACTION using the alias name XpeValueTransaction.
     * @return the XPE_VALUE_TRANSACTION
     */
    public String getXpeValueTransaction() {
        return (String) getAttributeInternal(XPEVALUETRANSACTION);
    }

    /**
     * Sets <code>value</code> as attribute value for XPE_VALUE_TRANSACTION using the alias name XpeValueTransaction.
     * @param value value to set the XPE_VALUE_TRANSACTION
     */
    public void setXpeValueTransaction(String value) {
        setAttributeInternal(XPEVALUETRANSACTION, value);
    }

    /**
     * Gets the attribute value for XPE_VARIANCE_BUDGET using the alias name XpeVarianceBudget.
     * @return the XPE_VARIANCE_BUDGET
     */
    public String getXpeVarianceBudget() {
        return (String) getAttributeInternal(XPEVARIANCEBUDGET);
    }

    /**
     * Sets <code>value</code> as attribute value for XPE_VARIANCE_BUDGET using the alias name XpeVarianceBudget.
     * @param value value to set the XPE_VARIANCE_BUDGET
     */
    public void setXpeVarianceBudget(String value) {
        setAttributeInternal(XPEVARIANCEBUDGET, value);
    }

    /**
     * Gets the attribute value for XPE_PAYMENT_HISTORY using the alias name XpePaymentHistory.
     * @return the XPE_PAYMENT_HISTORY
     */
    public String getXpePaymentHistory() {
        return (String) getAttributeInternal(XPEPAYMENTHISTORY);
    }

    /**
     * Sets <code>value</code> as attribute value for XPE_PAYMENT_HISTORY using the alias name XpePaymentHistory.
     * @param value value to set the XPE_PAYMENT_HISTORY
     */
    public void setXpePaymentHistory(String value) {
        setAttributeInternal(XPEPAYMENTHISTORY, value);
    }

    /**
     * Gets the attribute value for XPE_PAYMENT_METHOD using the alias name XpePaymentMethod.
     * @return the XPE_PAYMENT_METHOD
     */
    public String getXpePaymentMethod() {
        return (String) getAttributeInternal(XPEPAYMENTMETHOD);
    }

    /**
     * Sets <code>value</code> as attribute value for XPE_PAYMENT_METHOD using the alias name XpePaymentMethod.
     * @param value value to set the XPE_PAYMENT_METHOD
     */
    public void setXpePaymentMethod(String value) {
        setAttributeInternal(XPEPAYMENTMETHOD, value);
    }

    /**
     * Gets the attribute value for XPE_EST_DISPOSAL_VOL using the alias name XpeEstDisposalVol.
     * @return the XPE_EST_DISPOSAL_VOL
     */
    public String getXpeEstDisposalVol() {
        return (String) getAttributeInternal(XPEESTDISPOSALVOL);
    }

    /**
     * Sets <code>value</code> as attribute value for XPE_EST_DISPOSAL_VOL using the alias name XpeEstDisposalVol.
     * @param value value to set the XPE_EST_DISPOSAL_VOL
     */
    public void setXpeEstDisposalVol(String value) {
        setAttributeInternal(XPEESTDISPOSALVOL, value);
    }

    /**
     * Gets the attribute value for XPE_EXISTING_CUSTOMER using the alias name XpeExistingCustomer.
     * @return the XPE_EXISTING_CUSTOMER
     */
    public String getXpeExistingCustomer() {
        return (String) getAttributeInternal(XPEEXISTINGCUSTOMER);
    }

    /**
     * Sets <code>value</code> as attribute value for XPE_EXISTING_CUSTOMER using the alias name XpeExistingCustomer.
     * @param value value to set the XPE_EXISTING_CUSTOMER
     */
    public void setXpeExistingCustomer(String value) {
        setAttributeInternal(XPEEXISTINGCUSTOMER, value);
    }

    /**
     * Gets the attribute value for XPE_JUSTIFICATION using the alias name XpeJustification.
     * @return the XPE_JUSTIFICATION
     */
    public String getXpeJustification() {
        return (String) getAttributeInternal(XPEJUSTIFICATION);
    }

    /**
     * Sets <code>value</code> as attribute value for XPE_JUSTIFICATION using the alias name XpeJustification.
     * @param value value to set the XPE_JUSTIFICATION
     */
    public void setXpeJustification(String value) {
        setAttributeInternal(XPEJUSTIFICATION, value);
    }

    /**
     * Gets the attribute value for XPE_CREDIT_LIMIT using the alias name XpeCreditLimit.
     * @return the XPE_CREDIT_LIMIT
     */
    public String getXpeCreditLimit() {
        return (String) getAttributeInternal(XPECREDITLIMIT);
    }

    /**
     * Sets <code>value</code> as attribute value for XPE_CREDIT_LIMIT using the alias name XpeCreditLimit.
     * @param value value to set the XPE_CREDIT_LIMIT
     */
    public void setXpeCreditLimit(String value) {
        setAttributeInternal(XPECREDITLIMIT, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link XpeDccContractNotesView.
     */
    public RowIterator getXpeDccContractNotesView() {
        return (RowIterator) getAttributeInternal(XPEDCCCONTRACTNOTESVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link XpeDccContractLineView.
     */
    public RowIterator getXpeDccContractLineView() {
        return (RowIterator) getAttributeInternal(XPEDCCCONTRACTLINEVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link XpeDccWorkflowView.
     */
    public RowIterator getXpeDccWorkflowView() {
        return (RowIterator) getAttributeInternal(XPEDCCWORKFLOWVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link XpeDccContractsAttachmentsView.
     */
    public RowIterator getXpeDccContractsAttachmentsView() {
        return (RowIterator) getAttributeInternal(XPEDCCCONTRACTSATTACHMENTSVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link XpeDccTermsContractEOVO.
     */
    public RowIterator getXpeDccTermsContractEOVO() {
        return (RowIterator) getAttributeInternal(XPEDCCTERMSCONTRACTEOVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> XpeDccDicContractStatus1.
     */
    public RowSet getXpeDccDicContractStatus1() {
        return (RowSet) getAttributeInternal(XPEDCCDICCONTRACTSTATUS1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> XpeDccDicOptionsRenewal1.
     */
    public RowSet getXpeDccDicOptionsRenewal1() {
        return (RowSet) getAttributeInternal(XPEDCCDICOPTIONSRENEWAL1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> XpeDccDicOptionsBilling1.
     */
    public RowSet getXpeDccDicOptionsBilling1() {
        return (RowSet) getAttributeInternal(XPEDCCDICOPTIONSBILLING1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> XpeDccDicOptionsAccounting1.
     */
    public RowSet getXpeDccDicOptionsAccounting1() {
        return (RowSet) getAttributeInternal(XPEDCCDICOPTIONSACCOUNTING1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> XpeDccDicBusinessUnits1.
     */
    public RowSet getXpeDccDicBusinessUnits1() {
        return (RowSet) getAttributeInternal(XPEDCCDICBUSINESSUNITS1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> XpeDccDicCurrency1.
     */
    public RowSet getXpeDccDicCurrency1() {
        return (RowSet) getAttributeInternal(XPEDCCDICCURRENCY1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LookupSharedAppModule_XpeDccDicWasteType.
     */
    public RowSet getLookupSharedAppModule_XpeDccDicWasteType() {
        return (RowSet) getAttributeInternal(LOOKUPSHAREDAPPMODULE_XPEDCCDICWASTETYPE);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LookupSharedAppModule_XpeDccDicContractSubtype.
     */
    public RowSet getLookupSharedAppModule_XpeDccDicContractSubtype() {
        return (RowSet) getAttributeInternal(LOOKUPSHAREDAPPMODULE_XPEDCCDICCONTRACTSUBTYPE);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LookupSharedAppModule_XpeDccDicAgreementType.
     */
    public RowSet getLookupSharedAppModule_XpeDccDicAgreementType() {
        return (RowSet) getAttributeInternal(LOOKUPSHAREDAPPMODULE_XPEDCCDICAGREEMENTTYPE);
    }

    /**
     * Gets the view accessor <code>RowSet</code> XpeDccMasterTermsLOV.
     */
    public RowSet getXpeDccMasterTermsLOV() {
        return (RowSet) getAttributeInternal(XPEDCCMASTERTERMSLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LookupSharedAppModule_XpeDccDicNewContractSetupROVO1.
     */
    public RowSet getLookupSharedAppModule_XpeDccDicNewContractSetupROVO1() {
        return (RowSet) getAttributeInternal(LOOKUPSHAREDAPPMODULE_XPEDCCDICNEWCONTRACTSETUPROVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PsCurrencyCdTblROVO1.
     */
    public RowSet getPsCurrencyCdTblROVO1() {
        return (RowSet) getAttributeInternal(PSCURRENCYCDTBLROVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PsSalesPersonROVO1.
     */
    public RowSet getPsSalesPersonROVO1() {
        return (RowSet) getAttributeInternal(PSSALESPERSONROVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PcBusUnitTblGlROVO1.
     */
    public RowSet getPcBusUnitTblGlROVO1() {
        return (RowSet) getAttributeInternal(PCBUSUNITTBLGLROVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LookupSharedAppModule_YORNLOV.
     */
    public RowSet getLookupSharedAppModule_YORNLOV() {
        return (RowSet) getAttributeInternal(LOOKUPSHAREDAPPMODULE_YORNLOV);
    }
}

