package model;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.RowID;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 22 16:41:25 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XpeDccContractsViewRowImpl extends ViewRowImpl {
    public static final int ENTITY_XPEDCCCONTRACTS = 0;
    public static final int ENTITY_PSCUSTOMER = 1;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        XpeContractId,
        XpeContractDesc,
        Setid,
        CustId,
        CreatedBy,
        CurrencyCd,
        Name1,
        RowID,
        XpeDccPcsname,
        CustContractApproverEmail,
        CustContractContactName,
        XpeDccContractPartyView,
        XpeDccContractVersionView,
        XpeDccPlatformEventView,
        XpeDccDicCurrency1,
        NeuCustomersVwView1,
        XpeDccCfgPCSShortNamesROVO1,
        PsCustomerROVO1;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int XPECONTRACTID = AttributesEnum.XpeContractId.index();
    public static final int XPECONTRACTDESC = AttributesEnum.XpeContractDesc.index();
    public static final int SETID = AttributesEnum.Setid.index();
    public static final int CUSTID = AttributesEnum.CustId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CURRENCYCD = AttributesEnum.CurrencyCd.index();
    public static final int NAME1 = AttributesEnum.Name1.index();
    public static final int ROWID = AttributesEnum.RowID.index();
    public static final int XPEDCCPCSNAME = AttributesEnum.XpeDccPcsname.index();
    public static final int CUSTCONTRACTAPPROVEREMAIL = AttributesEnum.CustContractApproverEmail.index();
    public static final int CUSTCONTRACTCONTACTNAME = AttributesEnum.CustContractContactName.index();
    public static final int XPEDCCCONTRACTPARTYVIEW = AttributesEnum.XpeDccContractPartyView.index();
    public static final int XPEDCCCONTRACTVERSIONVIEW = AttributesEnum.XpeDccContractVersionView.index();
    public static final int XPEDCCPLATFORMEVENTVIEW = AttributesEnum.XpeDccPlatformEventView.index();
    public static final int XPEDCCDICCURRENCY1 = AttributesEnum.XpeDccDicCurrency1.index();
    public static final int NEUCUSTOMERSVWVIEW1 = AttributesEnum.NeuCustomersVwView1.index();
    public static final int XPEDCCCFGPCSSHORTNAMESROVO1 = AttributesEnum.XpeDccCfgPCSShortNamesROVO1.index();
    public static final int PSCUSTOMERROVO1 = AttributesEnum.PsCustomerROVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XpeDccContractsViewRowImpl() {
    }

    /**
     * Gets XpeDccContracts entity object.
     * @return the XpeDccContracts
     */
    public XpeDccContractsImpl getXpeDccContracts() {
        return (XpeDccContractsImpl) getEntity(ENTITY_XPEDCCCONTRACTS);
    }

    /**
     * Gets PsCustomer entity object.
     * @return the PsCustomer
     */
    public EntityImpl getPsCustomer() {
        return (EntityImpl) getEntity(ENTITY_PSCUSTOMER);
    }

    /**
     * Gets the attribute value for XPE_CONTRACT_ID using the alias name XpeContractId.
     * @return the XPE_CONTRACT_ID
     */
    public String getXpeContractId() {
        return (String) getAttributeInternal(XPECONTRACTID);
    }

    /**
     * Sets <code>value</code> as attribute value for XPE_CONTRACT_ID using the alias name XpeContractId.
     * @param value value to set the XPE_CONTRACT_ID
     */
    public void setXpeContractId(String value) {
        setAttributeInternal(XPECONTRACTID, value);
    }

    /**
     * Gets the attribute value for XPE_CONTRACT_DESC using the alias name XpeContractDesc.
     * @return the XPE_CONTRACT_DESC
     */
    public String getXpeContractDesc() {
        return (String) getAttributeInternal(XPECONTRACTDESC);
    }

    /**
     * Sets <code>value</code> as attribute value for XPE_CONTRACT_DESC using the alias name XpeContractDesc.
     * @param value value to set the XPE_CONTRACT_DESC
     */
    public void setXpeContractDesc(String value) {
        setAttributeInternal(XPECONTRACTDESC, value);
    }

    /**
     * Gets the attribute value for SETID using the alias name Setid.
     * @return the SETID
     */
    public String getSetid() {
        return (String) getAttributeInternal(SETID);
    }

    /**
     * Sets <code>value</code> as attribute value for SETID using the alias name Setid.
     * @param value value to set the SETID
     */
    public void setSetid(String value) {
        setAttributeInternal(SETID, value);
    }

    /**
     * Gets the attribute value for CUST_ID using the alias name CustId.
     * @return the CUST_ID
     */
    public String getCustId() {
        return (String) getAttributeInternal(CUSTID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUST_ID using the alias name CustId.
     * @param value value to set the CUST_ID
     */
    public void setCustId(String value) {
        setAttributeInternal(CUSTID, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CURRENCY_CD using the alias name CurrencyCd.
     * @return the CURRENCY_CD
     */
    public String getCurrencyCd() {
        return (String) getAttributeInternal(CURRENCYCD);
    }

    /**
     * Sets <code>value</code> as attribute value for CURRENCY_CD using the alias name CurrencyCd.
     * @param value value to set the CURRENCY_CD
     */
    public void setCurrencyCd(String value) {
        setAttributeInternal(CURRENCYCD, value);
    }

    /**
     * Gets the attribute value for NAME1 using the alias name Name1.
     * @return the NAME1
     */
    public String getName1() {
        return (String) getAttributeInternal(NAME1);
    }

    /**
     * Sets <code>value</code> as attribute value for NAME1 using the alias name Name1.
     * @param value value to set the NAME1
     */
    public void setName1(String value) {
        setAttributeInternal(NAME1, value);
    }

    /**
     * Gets the attribute value for ROWID using the alias name RowID.
     * @return the ROWID
     */
    public RowID getRowID() {
        return (RowID) getAttributeInternal(ROWID);
    }

    /**
     * Gets the attribute value for XPE_DCC_PCSNAME using the alias name XpeDccPcsname.
     * @return the XPE_DCC_PCSNAME
     */
    public String getXpeDccPcsname() {
        return (String) getAttributeInternal(XPEDCCPCSNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for XPE_DCC_PCSNAME using the alias name XpeDccPcsname.
     * @param value value to set the XPE_DCC_PCSNAME
     */
    public void setXpeDccPcsname(String value) {
        setAttributeInternal(XPEDCCPCSNAME, value);
    }

    /**
     * Gets the attribute value for CUST_CONTRACT_APPROVER_EMAIL using the alias name CustContractApproverEmail.
     * @return the CUST_CONTRACT_APPROVER_EMAIL
     */
    public String getCustContractApproverEmail() {
        return (String) getAttributeInternal(CUSTCONTRACTAPPROVEREMAIL);
    }

    /**
     * Sets <code>value</code> as attribute value for CUST_CONTRACT_APPROVER_EMAIL using the alias name CustContractApproverEmail.
     * @param value value to set the CUST_CONTRACT_APPROVER_EMAIL
     */
    public void setCustContractApproverEmail(String value) {
        setAttributeInternal(CUSTCONTRACTAPPROVEREMAIL, value);
    }

    /**
     * Gets the attribute value for CUST_CONTRACT_CONTACT_NAME using the alias name CustContractContactName.
     * @return the CUST_CONTRACT_CONTACT_NAME
     */
    public String getCustContractContactName() {
        return (String) getAttributeInternal(CUSTCONTRACTCONTACTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for CUST_CONTRACT_CONTACT_NAME using the alias name CustContractContactName.
     * @param value value to set the CUST_CONTRACT_CONTACT_NAME
     */
    public void setCustContractContactName(String value) {
        setAttributeInternal(CUSTCONTRACTCONTACTNAME, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link XpeDccContractPartyView.
     */
    public RowIterator getXpeDccContractPartyView() {
        return (RowIterator) getAttributeInternal(XPEDCCCONTRACTPARTYVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link XpeDccContractVersionView.
     */
    public RowIterator getXpeDccContractVersionView() {
        return (RowIterator) getAttributeInternal(XPEDCCCONTRACTVERSIONVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link XpeDccPlatformEventView.
     */
    public RowIterator getXpeDccPlatformEventView() {
        return (RowIterator) getAttributeInternal(XPEDCCPLATFORMEVENTVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> XpeDccDicCurrency1.
     */
    public RowSet getXpeDccDicCurrency1() {
        return (RowSet) getAttributeInternal(XPEDCCDICCURRENCY1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> NeuCustomersVwView1.
     */
    public RowSet getNeuCustomersVwView1() {
        return (RowSet) getAttributeInternal(NEUCUSTOMERSVWVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> XpeDccCfgPCSShortNamesROVO1.
     */
    public RowSet getXpeDccCfgPCSShortNamesROVO1() {
        return (RowSet) getAttributeInternal(XPEDCCCFGPCSSHORTNAMESROVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PsCustomerROVO1.
     */
    public RowSet getPsCustomerROVO1() {
        return (RowSet) getAttributeInternal(PSCUSTOMERROVO1);
    }
}

