SET SQLBLANKLINES ON
CREATE TABLE PS_CUSTOMER 
(
  SETID VARCHAR2(5 CHAR) NOT NULL 
, CUST_ID VARCHAR2(15 CHAR) NOT NULL 
, CUST_STATUS VARCHAR2(1 CHAR) NOT NULL 
, CUST_STATUS_DT DATE 
, STCUST_DAYS NUMBER(*, 0) NOT NULL 
, EXPIRATION_DATE DATE 
, EXP_PENDING VARCHAR2(1 CHAR) NOT NULL 
, TEMPLATE_ADDR VARCHAR2(1 CHAR) NOT NULL 
, CUSTOMER_TYPE VARCHAR2(1 CHAR) NOT NULL 
, SINCE_DT DATE NOT NULL 
, ADD_DT DATE NOT NULL 
, NAME1 VARCHAR2(40 CHAR) NOT NULL 
, NAMESHORT VARCHAR2(10 CHAR) NOT NULL 
, NAME2 VARCHAR2(40 CHAR) NOT NULL 
, NAME3 VARCHAR2(40 CHAR) NOT NULL 
, NAME1_AC VARCHAR2(40 CHAR) NOT NULL 
, NAME2_AC VARCHAR2(40 CHAR) NOT NULL 
, NAME3_AC VARCHAR2(40 CHAR) NOT NULL 
, ADDRESS_SEQ_NUM NUMBER(*, 0) NOT NULL 
, CORPORATE_SETID VARCHAR2(5 CHAR) NOT NULL 
, CORPORATE_CUST_ID VARCHAR2(15 CHAR) NOT NULL 
, PARENT_SETID VARCHAR2(5 CHAR) NOT NULL 
, PARENT_CUST_ID VARCHAR2(15 CHAR) NOT NULL 
, REMIT_FROM_SETID VARCHAR2(5 CHAR) NOT NULL 
, REMIT_FROM_CUST_ID VARCHAR2(15 CHAR) NOT NULL 
, CRSPD_SETID VARCHAR2(5 CHAR) NOT NULL 
, CRSPD_CUST_ID VARCHAR2(15 CHAR) NOT NULL 
, CONSOL_BUS_UNIT VARCHAR2(5 CHAR) NOT NULL 
, VENDOR_SETID VARCHAR2(5 CHAR) NOT NULL 
, VENDOR_ID VARCHAR2(10 CHAR) NOT NULL 
, REFER_TO_SETID VARCHAR2(5 CHAR) NOT NULL 
, REFER_TO_CUST_ID VARCHAR2(15 CHAR) NOT NULL 
, REVIEW_DAYS NUMBER(*, 0) NOT NULL 
, FORMER_NAME_1 VARCHAR2(40 CHAR) NOT NULL 
, FORMER_NAME_2 VARCHAR2(40 CHAR) NOT NULL 
, CNTCT_SEQ_NUM NUMBER(*, 0) NOT NULL 
, SUBCUST_USE VARCHAR2(1 CHAR) NOT NULL 
, SUBCUST_QUAL1 VARCHAR2(15 CHAR) NOT NULL 
, SUBCUST_QUAL2 VARCHAR2(15 CHAR) NOT NULL 
, CUR_RT_TYPE VARCHAR2(5 CHAR) NOT NULL 
, CURRENCY_CD VARCHAR2(3 CHAR) NOT NULL 
, SHIP_TO_FLG VARCHAR2(1 CHAR) NOT NULL 
, BILL_TO_FLG VARCHAR2(1 CHAR) NOT NULL 
, SOLD_TO_FLG VARCHAR2(1 CHAR) NOT NULL 
, BROKER_FLG VARCHAR2(1 CHAR) NOT NULL 
, INDIRECT_CUST_FLG VARCHAR2(1 CHAR) NOT NULL 
, CUST_LEVEL VARCHAR2(1 CHAR) NOT NULL 
, ADDRESS_SEQ_SOLD NUMBER(*, 0) NOT NULL 
, CNTCT_SEQ_SOLD NUMBER(*, 0) NOT NULL 
, ADDRESS_SEQ_SHIP NUMBER(*, 0) NOT NULL 
, CNTCT_SEQ_SHIP NUMBER(*, 0) NOT NULL 
, ADDRESS_SEQ_BRK NUMBER(*, 0) NOT NULL 
, ADDRESS_SEQ_IND NUMBER(*, 0) NOT NULL 
, HOLD_UPDATE_SW VARCHAR2(1 CHAR) NOT NULL 
, ROLEUSER VARCHAR2(30 CHAR) NOT NULL 
, TAXPAYER_ID VARCHAR2(14 CHAR) NOT NULL 
, WEB_URL VARCHAR2(130 CHAR) NOT NULL 
, STOCK_SYMBOL VARCHAR2(10 CHAR) NOT NULL 
, REPORTS_TO_SPONSOR VARCHAR2(15 CHAR) NOT NULL 
, SPNSR_LEVEL VARCHAR2(4 CHAR) NOT NULL 
, SPNSR_TYPE VARCHAR2(4 CHAR) NOT NULL 
, SPNSR_PROGRAM VARCHAR2(4 CHAR) NOT NULL 
, COST_LIV_INCR_PCT NUMBER(5, 2) NOT NULL 
, CFDA_NBR NUMBER(5, 3) NOT NULL 
, ALLOW_COPI VARCHAR2(1 CHAR) NOT NULL 
, MULTI_PI VARCHAR2(1 CHAR) NOT NULL 
, FOREIGN_FLAG VARCHAR2(1 CHAR) NOT NULL 
, FED_SP_TYPE VARCHAR2(4 CHAR) NOT NULL 
, OFAC_STATUS VARCHAR2(1 CHAR) NOT NULL 
, REASON_CD VARCHAR2(10 CHAR) NOT NULL 
, FSS_OFFSET_DAYS NUMBER(*, 0) NOT NULL 
, GM_FEDERAL_FLAG VARCHAR2(1 CHAR) NOT NULL 
, US_FLAG_CARRIER VARCHAR2(1 CHAR) NOT NULL 
, LOC_INDICATOR VARCHAR2(1 CHAR) NOT NULL 
, GM_LOC_SPONSOR_ID VARCHAR2(15 CHAR) NOT NULL 
, GGOV_FLG VARCHAR2(1 CHAR) NOT NULL 
, FA_SPNSR_BASE_ID VARCHAR2(5 CHAR) NOT NULL 
, GM_DEL_LOC_REFS_SW VARCHAR2(1 CHAR) NOT NULL 
, GRANTS_SPONSOR_FLG VARCHAR2(1 CHAR) NOT NULL 
, SPNSR_SALARY_CAP NUMBER(13, 2) NOT NULL 
, FEDERAL_INDICATOR VARCHAR2(1 CHAR) NOT NULL 
, TRADING_PARTNER VARCHAR2(6 CHAR) NOT NULL 
, IPAC_INTERFACE VARCHAR2(1 CHAR) NOT NULL 
, CNTCT_SEQ_IPAC NUMBER(*, 0) NOT NULL 
, CUSTOMER_ALC VARCHAR2(8 CHAR) NOT NULL 
, CUSTOMER_DO VARCHAR2(5 CHAR) NOT NULL 
, SYMBOL_REQ VARCHAR2(1 CHAR) NOT NULL 
, SOURCE_SYSTEM VARCHAR2(3 CHAR) NOT NULL 
, CUST_USF_STATUS VARCHAR2(1 CHAR) NOT NULL 
, EMPLID VARCHAR2(11 CHAR) NOT NULL 
, FED_SHARE_PCT NUMBER(5, 2) NOT NULL 
, CONT_ALLOW_PCT NUMBER(5, 2) NOT NULL 
, CONT_NO_ALLW_PCT NUMBER(5, 2) NOT NULL 
, CUST_FIELD_C1_A VARCHAR2(1 CHAR) NOT NULL 
, CUST_FIELD_C1_B VARCHAR2(1 CHAR) NOT NULL 
, CUST_FIELD_C1_C VARCHAR2(1 CHAR) NOT NULL 
, CUST_FIELD_C1_D VARCHAR2(1 CHAR) NOT NULL 
, CUST_FIELD_C2 VARCHAR2(2 CHAR) NOT NULL 
, CUST_FIELD_C4 VARCHAR2(4 CHAR) NOT NULL 
, CUST_FIELD_C6 VARCHAR2(6 CHAR) NOT NULL 
, CUST_FIELD_C8 VARCHAR2(8 CHAR) NOT NULL 
, CUST_FIELD_C10_A VARCHAR2(10 CHAR) NOT NULL 
, CUST_FIELD_C10_B VARCHAR2(10 CHAR) NOT NULL 
, CUST_FIELD_C10_C VARCHAR2(10 CHAR) NOT NULL 
, CUST_FIELD_C10_D VARCHAR2(10 CHAR) NOT NULL 
, CUST_FIELD_C30_A VARCHAR2(30 CHAR) NOT NULL 
, CUST_FIELD_C30_B VARCHAR2(30 CHAR) NOT NULL 
, CUST_FIELD_C30_C VARCHAR2(30 CHAR) NOT NULL 
, CUST_FIELD_C30_D VARCHAR2(30 CHAR) NOT NULL 
, CUST_FIELD_N12_A NUMBER(15, 3) NOT NULL 
, CUST_FIELD_N12_B NUMBER(15, 3) NOT NULL 
, CUST_FIELD_N12_C NUMBER(15, 3) NOT NULL 
, CUST_FIELD_N12_D NUMBER(15, 3) NOT NULL 
, CUST_FIELD_N15_A NUMBER(15, 0) NOT NULL 
, CUST_FIELD_N15_B NUMBER(15, 0) NOT NULL 
, CUST_FIELD_N15_C NUMBER(15, 0) NOT NULL 
, CUST_FIELD_N15_D NUMBER(15, 0) NOT NULL 
, LAST_MAINT_OPRID VARCHAR2(30 CHAR) NOT NULL 
, DATE_LAST_MAINT DATE 
, LASTUPDDTTM TIMESTAMP(6) 
) 
LOGGING 
TABLESPACE OMLARGE 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 40960 
  NEXT 106496 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE PS_CUST_ADDRESS 
(
  SETID VARCHAR2(5 CHAR) NOT NULL 
, CUST_ID VARCHAR2(15 CHAR) NOT NULL 
, ADDRESS_SEQ_NUM NUMBER(*, 0) NOT NULL 
, EFFDT DATE NOT NULL 
, EFF_STATUS VARCHAR2(1 CHAR) NOT NULL 
, ALT_NAME1 VARCHAR2(40 CHAR) NOT NULL 
, ALT_NAME2 VARCHAR2(40 CHAR) NOT NULL 
, LANGUAGE_CD VARCHAR2(3 CHAR) NOT NULL 
, TAX_CD VARCHAR2(8 CHAR) NOT NULL 
, COUNTRY VARCHAR2(3 CHAR) NOT NULL 
, ADDRESS1 VARCHAR2(55 CHAR) NOT NULL 
, ADDRESS2 VARCHAR2(55 CHAR) NOT NULL 
, ADDRESS3 VARCHAR2(55 CHAR) NOT NULL 
, ADDRESS4 VARCHAR2(55 CHAR) NOT NULL 
, CITY VARCHAR2(30 CHAR) NOT NULL 
, NUM1 VARCHAR2(6 CHAR) NOT NULL 
, NUM2 VARCHAR2(4 CHAR) NOT NULL 
, HOUSE_TYPE VARCHAR2(2 CHAR) NOT NULL 
, ADDR_FIELD1 VARCHAR2(2 CHAR) NOT NULL 
, ADDR_FIELD2 VARCHAR2(4 CHAR) NOT NULL 
, ADDR_FIELD3 VARCHAR2(4 CHAR) NOT NULL 
, COUNTY VARCHAR2(30 CHAR) NOT NULL 
, STATE VARCHAR2(6 CHAR) NOT NULL 
, POSTAL VARCHAR2(12 CHAR) NOT NULL 
, GEO_CODE VARCHAR2(11 CHAR) NOT NULL 
, IN_CITY_LIMIT VARCHAR2(1 CHAR) NOT NULL 
, COUNTRY_CODE VARCHAR2(3 CHAR) NOT NULL 
, PHONE VARCHAR2(24 CHAR) NOT NULL 
, EXTENSION VARCHAR2(6 CHAR) NOT NULL 
, FAX VARCHAR2(24 CHAR) NOT NULL 
, PHYSICAL_NATURE VARCHAR2(1 CHAR) NOT NULL 
, VAT_SVC_PERFRM_FLG VARCHAR2(1 CHAR) NOT NULL 
, LAST_EXP_CHK_DTTM TIMESTAMP(6) 
, LAST_MAINT_OPRID VARCHAR2(30 CHAR) NOT NULL 
, DATE_LAST_MAINT DATE 
, LASTUPDDTTM TIMESTAMP(6) 
, URL_LONG VARCHAR2(130 CHAR) NOT NULL 
) 
LOGGING 
TABLESPACE FSLARGE 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 40960 
  NEXT 106496 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE PS_CUST_ADDR_SEQ 
(
  SETID VARCHAR2(5 CHAR) NOT NULL 
, CUST_ID VARCHAR2(15 CHAR) NOT NULL 
, ADDRESS_SEQ_NUM NUMBER(*, 0) NOT NULL 
, DESCR VARCHAR2(30 CHAR) NOT NULL 
, BILL_TO_ADDR VARCHAR2(1 CHAR) NOT NULL 
, SHIP_TO_ADDR VARCHAR2(1 CHAR) NOT NULL 
, SOLD_TO_ADDR VARCHAR2(1 CHAR) NOT NULL 
, CRSPD_TO_ADDR VARCHAR2(1 CHAR) NOT NULL 
, BROKER_ADDR VARCHAR2(1 CHAR) NOT NULL 
, INDIRECT_ADDR VARCHAR2(1 CHAR) NOT NULL 
, RFID_ENABLED VARCHAR2(1 CHAR) NOT NULL 
, LAST_MAINT_OPRID VARCHAR2(30 CHAR) NOT NULL 
, DATE_LAST_MAINT DATE 
) 
LOGGING 
TABLESPACE FSLARGE 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 24576 
  NEXT 106496 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE PS_ITEM 
(
  BUSINESS_UNIT VARCHAR2(5 CHAR) NOT NULL 
, CUST_ID VARCHAR2(15 CHAR) NOT NULL 
, ITEM VARCHAR2(30 CHAR) NOT NULL 
, ITEM_LINE NUMBER(*, 0) NOT NULL 
, ITEM_STATUS VARCHAR2(1 CHAR) NOT NULL 
, ENTRY_TYPE VARCHAR2(5 CHAR) NOT NULL 
, ENTRY_REASON VARCHAR2(5 CHAR) NOT NULL 
, ENTRY_EVENT VARCHAR2(10 CHAR) NOT NULL 
, REF_REASON VARCHAR2(5 CHAR) NOT NULL 
, BAL_AMT NUMBER(26, 3) NOT NULL 
, ACCOUNTING_DT DATE NOT NULL 
, ASOF_DT DATE 
, POST_DT DATE NOT NULL 
, DUE_DT DATE 
, CR_ANALYST VARCHAR2(8 CHAR) NOT NULL 
, SALES_PERSON VARCHAR2(8 CHAR) NOT NULL 
, COLLECTOR VARCHAR2(8 CHAR) NOT NULL 
, DISPUTE_STATUS VARCHAR2(3 CHAR) NOT NULL 
, DISPUTE_DT DATE 
, DISPUTE_AMOUNT NUMBER(26, 3) NOT NULL 
, PO_REF VARCHAR2(30 CHAR) NOT NULL 
, PO_LINE NUMBER(*, 0) NOT NULL 
, DOCUMENT VARCHAR2(30 CHAR) NOT NULL 
, DOCUMENT_LINE NUMBER(*, 0) NOT NULL 
, PYMNT_TERMS_CD VARCHAR2(5 CHAR) NOT NULL 
, DISC_AMT NUMBER(26, 3) NOT NULL 
, DISC_AMT1 NUMBER(26, 3) NOT NULL 
, DISC_DT DATE 
, DISC_DT1 DATE 
, DISC_LEVEL VARCHAR2(1 CHAR) NOT NULL 
, DISC_DAYS NUMBER(*, 0) NOT NULL 
, DUE_DAYS NUMBER(*, 0) NOT NULL 
, ALLOW_DISC VARCHAR2(1 CHAR) NOT NULL 
, AGING_CATEGORY VARCHAR2(2 CHAR) NOT NULL 
, DST_ID_AR VARCHAR2(10 CHAR) NOT NULL 
, HIST_STATUS VARCHAR2(1 CHAR) NOT NULL 
, DUN_DT DATE 
, DUN_SEQ_NUM NUMBER(*, 0) NOT NULL 
, ST_DT DATE 
, FC_DT DATE 
, FC_AMT NUMBER(26, 3) NOT NULL 
, OC_ADMIN_DT DATE 
, OC_ADMIN_AMT NUMBER(26, 3) NOT NULL 
, OC_PNLTY_DT DATE 
, OC_PNLTY_AMT NUMBER(26, 3) NOT NULL 
, OVERDUE_CHG_LINE VARCHAR2(1 CHAR) NOT NULL 
, ITEM_LINE_ORIG NUMBER(*, 0) NOT NULL 
, UPDATE_STATUS VARCHAR2(1 CHAR) NOT NULL 
, COLLECTION_STATUS VARCHAR2(3 CHAR) NOT NULL 
, COLLECTION_DT DATE 
, ITEM_SEQ_NUM NUMBER(*, 0) NOT NULL 
, BILL_OF_LADING VARCHAR2(30 CHAR) NOT NULL 
, SUBCUST_QUAL1 VARCHAR2(15 CHAR) NOT NULL 
, SUBCUST_QUAL2 VARCHAR2(15 CHAR) NOT NULL 
, SUBCUST_STATUS VARCHAR2(1 CHAR) NOT NULL 
, BAL_CURRENCY VARCHAR2(3 CHAR) NOT NULL 
, RT_TYPE VARCHAR2(5 CHAR) NOT NULL 
, RATE_MULT NUMBER(15, 8) NOT NULL 
, RATE_DIV NUMBER(15, 8) NOT NULL 
, BAL_AMT_BASE NUMBER(26, 3) NOT NULL 
, BAL_AMT_LAST NUMBER(26, 3) NOT NULL 
, CURRENCY_CD VARCHAR2(3 CHAR) NOT NULL 
, ENTRY_USE_ID VARCHAR2(5 CHAR) NOT NULL 
, VAT_DCLRTN_POINT VARCHAR2(1 CHAR) NOT NULL 
, VAT_RECALC_FLG VARCHAR2(1 CHAR) NOT NULL 
, COUNTRY_VAT_BILLFR VARCHAR2(3 CHAR) NOT NULL 
, COUNTRY_VAT_BILLTO VARCHAR2(3 CHAR) NOT NULL 
, COUNTRY_SHIP_TO VARCHAR2(3 CHAR) NOT NULL 
, COUNTRY_SHIP_FROM VARCHAR2(3 CHAR) NOT NULL 
, VAT_CALC_GROSS_NET VARCHAR2(1 CHAR) NOT NULL 
, VAT_ENTITY VARCHAR2(20 CHAR) NOT NULL 
, VAT_EXCPTN_TYPE VARCHAR2(1 CHAR) NOT NULL 
, VAT_EXCPTN_CERTIF VARCHAR2(20 CHAR) NOT NULL 
, VAT_RGSTRN_BUYER VARCHAR2(20 CHAR) NOT NULL 
, VAT_ROUND_RULE VARCHAR2(1 CHAR) NOT NULL 
, ORDER_NO VARCHAR2(10 CHAR) NOT NULL 
, CONTRACT_NUM VARCHAR2(25 CHAR) NOT NULL 
, BUSINESS_UNIT_BI VARCHAR2(5 CHAR) NOT NULL 
, BUSINESS_UNIT_OM VARCHAR2(5 CHAR) NOT NULL 
, ADDRESS_SEQ_NUM NUMBER(*, 0) NOT NULL 
, LETTER_CD VARCHAR2(3 CHAR) NOT NULL 
, TRAN_FROM_BU VARCHAR2(5 CHAR) NOT NULL 
, TRAN_FROM_CUSTID VARCHAR2(15 CHAR) NOT NULL 
, CONSOL_BUS_UNIT VARCHAR2(5 CHAR) NOT NULL 
, CONSOL_INVOICE VARCHAR2(22 CHAR) NOT NULL 
, PAYMENT_METHOD VARCHAR2(3 CHAR) NOT NULL 
, DRAFT_BU VARCHAR2(5 CHAR) NOT NULL 
, DRAFT_ID VARCHAR2(15 CHAR) NOT NULL 
, DRAFT_APPROVAL VARCHAR2(1 CHAR) NOT NULL 
, DRAFT_DOC VARCHAR2(1 CHAR) NOT NULL 
, DRAFT_CURRENCY VARCHAR2(3 CHAR) NOT NULL 
, DRAFT_FORMAT VARCHAR2(1 CHAR) NOT NULL 
, DRAFT_STATUS VARCHAR2(1 CHAR) NOT NULL 
, BANK_SETID VARCHAR2(5 CHAR) NOT NULL 
, BANK_CD VARCHAR2(5 CHAR) NOT NULL 
, BANK_ACCT_KEY VARCHAR2(4 CHAR) NOT NULL 
, DD_BU VARCHAR2(5 CHAR) NOT NULL 
, DD_ID VARCHAR2(15 CHAR) NOT NULL 
, DD_CURRENCY VARCHAR2(3 CHAR) NOT NULL 
, DD_STATUS VARCHAR2(1 CHAR) NOT NULL 
, DD_PROFILE_ID VARCHAR2(5 CHAR) NOT NULL 
, DRAFT_TYPE VARCHAR2(10 CHAR) NOT NULL 
, PROCESS_INSTANCE NUMBER(10, 0) NOT NULL 
, USER_AMT1 NUMBER(26, 3) NOT NULL 
, USER_AMT2 NUMBER(26, 3) NOT NULL 
, USER_AMT3 NUMBER(26, 3) NOT NULL 
, USER_AMT4 NUMBER(26, 3) NOT NULL 
, USER_AMT5 NUMBER(26, 3) NOT NULL 
, USER_AMT6 NUMBER(26, 3) NOT NULL 
, USER_AMT7 NUMBER(26, 3) NOT NULL 
, USER_AMT8 NUMBER(26, 3) NOT NULL 
, USER_DT1 DATE 
, USER_DT2 DATE 
, USER_DT3 DATE 
, USER_DT4 DATE 
, USER1 VARCHAR2(1 CHAR) NOT NULL 
, USER2 VARCHAR2(1 CHAR) NOT NULL 
, USER3 VARCHAR2(1 CHAR) NOT NULL 
, USER4 VARCHAR2(1 CHAR) NOT NULL 
, USER5 VARCHAR2(1 CHAR) NOT NULL 
, USER6 VARCHAR2(1 CHAR) NOT NULL 
, USER7 VARCHAR2(1 CHAR) NOT NULL 
, USER8 VARCHAR2(1 CHAR) NOT NULL 
, USER9 VARCHAR2(1 CHAR) NOT NULL 
, USER10 VARCHAR2(1 CHAR) NOT NULL 
, ORIG_ITEM_AMT NUMBER(26, 3) NOT NULL 
, LAST_ACTIVITY_DT DATE 
, ST_ID_NUM NUMBER(*, 0) NOT NULL 
, DOUBTFUL VARCHAR2(1 CHAR) NOT NULL 
, DRAFT_BUSN_EVENT VARCHAR2(2 CHAR) NOT NULL 
, DRAFT_SUB_EVENT VARCHAR2(2 CHAR) NOT NULL 
, SALES_PERSON2 VARCHAR2(8 CHAR) NOT NULL 
, REGION_CD VARCHAR2(10 CHAR) NOT NULL 
, REVALUE_FLAG VARCHAR2(1 CHAR) NOT NULL 
, PACKSLIP_NO VARCHAR2(22 CHAR) NOT NULL 
, SBI_NUM VARCHAR2(40 CHAR) NOT NULL 
, LC_ID VARCHAR2(12 CHAR) NOT NULL 
, NETTING_SW VARCHAR2(1 CHAR) NOT NULL 
, NET_REF_ID VARCHAR2(12 CHAR) NOT NULL 
, RECEIVABLE_TYPE VARCHAR2(3 CHAR) NOT NULL 
, ENTITY_CODE VARCHAR2(9 CHAR) NOT NULL 
, PPRC_PROMO_CD VARCHAR2(20 CHAR) NOT NULL 
, CLAIM_NO VARCHAR2(30 CHAR) NOT NULL 
, CLAIM_SETID VARCHAR2(5 CHAR) NOT NULL 
, AR_SPECIALIST VARCHAR2(8 CHAR) NOT NULL 
, BROKER_ID VARCHAR2(15 CHAR) NOT NULL 
, CARRIER_ID VARCHAR2(10 CHAR) NOT NULL 
, CLAIM_DT DATE 
, CLASS_OF_TRADE VARCHAR2(20 CHAR) NOT NULL 
, DEDUCTION_STATUS VARCHAR2(5 CHAR) NOT NULL 
, DEDUCTION_DT DATE 
, DIVISION VARCHAR2(20 CHAR) NOT NULL 
, DT_INVOICED DATE 
, INV_PROD_FAM_CD VARCHAR2(10 CHAR) NOT NULL 
, INVOICE VARCHAR2(22 CHAR) NOT NULL 
, INVOICE_BU VARCHAR2(5 CHAR) NOT NULL 
, MAJOR_CLASS VARCHAR2(10 CHAR) NOT NULL 
, MEMO_STATUS_CD VARCHAR2(10 CHAR) NOT NULL 
, MERCH_TYPE VARCHAR2(10 CHAR) NOT NULL 
, PROOF_OF_DELIVERY VARCHAR2(30 CHAR) NOT NULL 
, SHIP_FROM_BU VARCHAR2(5 CHAR) NOT NULL 
, SHIP_TO_ADDR_NUM NUMBER(*, 0) NOT NULL 
, SHIP_TO_CUST_ID VARCHAR2(15 CHAR) NOT NULL 
, SOLD_TO_ADDR_NUM NUMBER(*, 0) NOT NULL 
, SOLD_TO_CUST_ID VARCHAR2(15 CHAR) NOT NULL 
, VAT_TREATMENT_GRP VARCHAR2(4 CHAR) NOT NULL 
, PHYSICAL_NATURE VARCHAR2(1 CHAR) NOT NULL 
, COUNTRY_LOC_BUYER VARCHAR2(3 CHAR) NOT NULL 
, STATE_LOC_BUYER VARCHAR2(6 CHAR) NOT NULL 
, COUNTRY_LOC_SELLER VARCHAR2(3 CHAR) NOT NULL 
, STATE_LOC_SELLER VARCHAR2(6 CHAR) NOT NULL 
, VAT_SVC_SUPPLY_FLG VARCHAR2(1 CHAR) NOT NULL 
, VAT_SERVICE_TYPE VARCHAR2(1 CHAR) NOT NULL 
, COUNTRY_VAT_PERFRM VARCHAR2(3 CHAR) NOT NULL 
, STATE_VAT_PERFRM VARCHAR2(6 CHAR) NOT NULL 
, COUNTRY_VAT_SUPPLY VARCHAR2(3 CHAR) NOT NULL 
, STATE_VAT_SUPPLY VARCHAR2(6 CHAR) NOT NULL 
, STATE_SHIP_FROM VARCHAR2(6 CHAR) NOT NULL 
, STATE_SHIP_TO VARCHAR2(6 CHAR) NOT NULL 
, VAT_RPT_CNTRY_SRC VARCHAR2(1 CHAR) NOT NULL 
, STATE_VAT_DEFAULT VARCHAR2(6 CHAR) NOT NULL 
, CONVERS_EXISTS VARCHAR2(1 CHAR) NOT NULL 
, AG_REF_NBR NUMBER(16, 0) NOT NULL 
, INVOICE_DT DATE 
, AR_EBP_PAYM_DT DATE 
, AR_EBP_PROC_BY VARCHAR2(1 CHAR) NOT NULL 
, BUSINESS_UNIT_CA VARCHAR2(5 CHAR) NOT NULL 
, CONTRACT_LINE_NUM NUMBER(*, 0) NOT NULL 
, SUBROG_CASE_NUM VARCHAR2(30 CHAR) NOT NULL 
, SP_ID NUMBER(11, 0) NOT NULL 
, IN_USE_FLAG VARCHAR2(1 CHAR) NOT NULL 
, ENTERED_DTTM TIMESTAMP(6) 
, OPRID VARCHAR2(30 CHAR) NOT NULL 
, LAST_UPDATE_DTTM TIMESTAMP(6) 
, OPRID_LAST_UPDT VARCHAR2(30 CHAR) NOT NULL 
) 
LOGGING 
TABLESPACE ARLARGE 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 40960 
  NEXT 106496 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE PS_XPE_CUST_CYBER 
(
  CUST_ID VARCHAR2(15) NOT NULL 
, PS_CUSTOM_SUBSCRIPTION_ID VARCHAR2(254) NOT NULL 
, CONSTRAINT PS_XPE_CUST_CYBER_PK PRIMARY KEY 
  (
    CUST_ID 
  , PS_CUSTOM_SUBSCRIPTION_ID 
  )
  ENABLE 
);

CREATE TABLE XPE_DCC_CARRIERS 
(
  XPE_CARRIER_ID VARCHAR2(20) NOT NULL 
, XPE_CARRIER_DESC VARCHAR2(50) NOT NULL 
, CONSTRAINT XPE_DCC_CARRIERS_PK PRIMARY KEY 
  (
    XPE_CARRIER_ID 
  )
  ENABLE 
);

CREATE TABLE XPE_DCC_CONTRACTS 
(
  XPE_CONTRACT_ID VARCHAR2(20) NOT NULL 
, XPE_CONTRACT_DESC VARCHAR2(120) 
, SETID VARCHAR2(5) 
, CUST_ID VARCHAR2(15) 
, CREATED_BY VARCHAR2(20) 
, CURRENCY_CD VARCHAR2(20) 
, CONSTRAINT XPE_DCC_CONTRACTS_PK PRIMARY KEY 
  (
    XPE_CONTRACT_ID 
  )
  ENABLE 
);

CREATE TABLE XPE_DCC_LOOKUP_MASTER 
(
  XPE_LOOKUP_TYPE VARCHAR2(5) NOT NULL 
, XPE_LOOKUP_ID VARCHAR2(3) NOT NULL 
, XPE_LOOKUP_DESC VARCHAR2(20) 
, CONSTRAINT XPE_DCC_LOOKUP_MASTER_PK PRIMARY KEY 
  (
    XPE_LOOKUP_TYPE 
  , XPE_LOOKUP_ID 
  )
  ENABLE 
);

CREATE TABLE XPE_DCC_CONTRACT_PARTY 
(
  XPE_CONTRACT_ID VARCHAR2(20) NOT NULL 
, SETID VARCHAR2(5) NOT NULL 
, CUST_ID VARCHAR2(15) NOT NULL 
, XPE_PRIMARY VARCHAR2(1) DEFAULT 'Y' 
, XPE_PARTY_TYPE VARCHAR2(3) DEFAULT 'CUS' 
, CONSTRAINT XPE_DCC_CONTRACT_PARTY_PK PRIMARY KEY 
  (
    XPE_CONTRACT_ID 
  , SETID 
  , CUST_ID 
  )
  ENABLE 
);

CREATE TABLE XPE_DCC_CONTRACT_VERSION 
(
  XPE_CONTRACT_ID VARCHAR2(20) NOT NULL 
, XPE_CONTRACT_VERSION VARCHAR2(20) NOT NULL 
, XPE_CONTRACT_STATUS VARCHAR2(3) 
, XPE_START_DATE TIMESTAMP 
, XPE_END_DATE TIMESTAMP 
, XPE_NEW_TERM_MODE VARCHAR2(3) DEFAULT 'REM' 
, CREATED_BY VARCHAR2(20) 
, UPDATED_BY VARCHAR2(20) 
, XPE_BILL_OPTIONS_SET VARCHAR2(10) 
, XPE_ACCTG_OPTIONS_SET VARCHAR2(10) 
, XPE_CONTRACT_TEMPLATE VARCHAR2(20) 
, BUSINESS_UNIT_GL VARCHAR2(5) 
, CURRENCY_CD VARCHAR2(3) 
, CONSTRAINT XPE_DCC_CONTRACT_VERSION_PK PRIMARY KEY 
  (
    XPE_CONTRACT_ID 
  , XPE_CONTRACT_VERSION 
  )
  ENABLE 
);

CREATE TABLE XPE_DCC_PLATFORM_EVENT 
(
  XPE_CONTRACT_ID VARCHAR2(20) NOT NULL 
, XPE_PRICING_TERM_LINE NUMBER NOT NULL 
, XPE_CONTRACT_LINE VARCHAR2(20) NOT NULL 
, XPE_CONTRACT_VERSION VARCHAR2(20) NOT NULL 
, XPE_CARRIER_ID VARCHAR2(20) NOT NULL 
, XPE_VEHICLE_TYPE VARCHAR2(3) NOT NULL 
, XPE_SUB_NBR NUMBER(2) NOT NULL 
, XPE_VEHICLE_NBR VARCHAR2(20) NOT NULL 
, XPE_EVENT_DTTM TIMESTAMP NOT NULL 
, XPE_EVENT_NBR VARCHAR2(10) NOT NULL 
, COLUMN1 VARCHAR2(5) NOT NULL 
, XPE_EVENT_TYPE VARCHAR2(3) 
, XPE_EVENT_REF VARCHAR2(20) 
, XPE_EVENT_UOM VARCHAR2(3) 
, XPE_EVENT_QTY NUMBER(5, 5) 
, XPE_RESULT_UOM VARCHAR2(3) 
, XPE_RESULT_QTY NUMBER(5, 2) 
, XPE_RESULT_TYPE VARCHAR2(10) 
, XPE_RESULT_REF VARCHAR2(20) 
, XPE_SYSTEM_MSG VARCHAR2(50) 
, XPE_ICON VARCHAR2(20) 
, CONSTRAINT XPE_DCC_PLATFORM_EVENT_PK PRIMARY KEY 
  (
    COLUMN1 
  , XPE_EVENT_NBR 
  , XPE_EVENT_DTTM 
  , XPE_VEHICLE_NBR 
  , XPE_VEHICLE_TYPE 
  , XPE_SUB_NBR 
  , XPE_CARRIER_ID 
  , XPE_CONTRACT_VERSION 
  , XPE_CONTRACT_LINE 
  , XPE_PRICING_TERM_LINE 
  , XPE_CONTRACT_ID 
  )
  ENABLE 
);

CREATE TABLE XPE_DCC_CONTRACT_LINE 
(
  XPE_CONTRACT_ID VARCHAR2(20) NOT NULL 
, XPE_CONTRACT_VERSION VARCHAR2(20) NOT NULL 
, XPE_CONTRACT_LINE VARCHAR2(20) NOT NULL 
, XPE_FACILITY VARCHAR2(20) 
, XPE_PRODUCT_ID VARCHAR2(20) 
, XPE_PRODUCT_UOM VARCHAR2(20) 
, XPE_QTY_MIN NUMBER(20, 5) 
, XPE_QTY_MAX NUMBER(20, 5) 
, XPE_PERIOD_TYPE VARCHAR2(20) 
, XPE_ICON VARCHAR2(20) 
, XPE_SW_APPR_NBR VARCHAR2(40) 
, CONSTRAINT XPE_DCC_CONTRACT_LINE_PK PRIMARY KEY 
  (
    XPE_CONTRACT_ID 
  , XPE_CONTRACT_VERSION 
  , XPE_CONTRACT_LINE 
  )
  ENABLE 
);

CREATE TABLE XPE_DCC_CONTRACT_NOTES 
(
  XPE_CONTRACT_ID VARCHAR2(20) NOT NULL 
, XPE_CONTRACT_VERSION VARCHAR2(20) NOT NULL 
, XPE_NOTE_DTTM TIMESTAMP NOT NULL 
, XPE_NOTE VARCHAR2(255) 
, XPE_USER VARCHAR2(20) DEFAULT 'admin' NOT NULL 
, XPE_NOTE_LONG CLOB 
, XPE_NOTE_TYPE VARCHAR2(3) DEFAULT 'int' NOT NULL 
, CONSTRAINT XPE_DCC_CONTRACT_NOTES_PK PRIMARY KEY 
  (
    XPE_CONTRACT_ID 
  , XPE_CONTRACT_VERSION 
  , XPE_NOTE_DTTM 
  )
  ENABLE 
);

CREATE TABLE XPE_DCC_WORKFLOW 
(
  XPE_CONTRACT_ID VARCHAR2(20) NOT NULL 
, XPE_CONTRACT_VERSION VARCHAR2(20) NOT NULL 
, XPE_WF_TYPE VARCHAR2(3) NOT NULL 
, XPE_WF_DTTM TIMESTAMP NOT NULL 
, XPE_WF_NBR VARCHAR2(20) NOT NULL 
, XPE_WF_USER VARCHAR2(20) 
, XPE_WF_COMMENT VARCHAR2(50) 
, XPE_ICON VARCHAR2(20) 
, CONSTRAINT XPE_DCC_WORKFLOW_PK PRIMARY KEY 
  (
    XPE_CONTRACT_ID 
  , XPE_CONTRACT_VERSION 
  , XPE_WF_DTTM 
  , XPE_WF_TYPE 
  , XPE_WF_NBR 
  )
  ENABLE 
);

CREATE TABLE XPE_DCC_CONTRACT_DOC_TERM 
(
  XPE_CONTRACT_ID VARCHAR2(20) NOT NULL 
, XPE_CONTRACT_VERSION VARCHAR2(20) NOT NULL 
, XPE_CONTRACT_LINE VARCHAR2(20) NOT NULL 
, XPE_CONTRACT_DOC_TERM_ID NUMBER NOT NULL 
, CONSTRAINT XPE_DCC_CONTRACT_DOC_TERM_PK PRIMARY KEY 
  (
    XPE_CONTRACT_ID 
  , XPE_CONTRACT_VERSION 
  , XPE_CONTRACT_LINE 
  , XPE_CONTRACT_DOC_TERM_ID 
  )
  ENABLE 
);

CREATE TABLE XPE_DCC_CONTRACT_PRICING_TERM 
(
  XPE_CONTRACT_ID VARCHAR2(20) NOT NULL 
, XPE_CONTRACT_VERSION VARCHAR2(20) NOT NULL 
, XPE_CONTRACT_LINE VARCHAR2(20) NOT NULL 
, XPE_PRICING_TERM_LINE NUMBER NOT NULL 
, XPE_PRICING_TERM_TYPE VARCHAR2(3) 
, XPE_QTY_MAX NUMBER(20, 5) 
, XPE_RATE NUMBER(20, 5) 
, XPE_CHARGE_OVER_MIN NUMBER(20, 5) 
, XPE_CHARGE_OVER_MAX NUMBER(20, 5) 
, XPE_CHARGE_DESC VARCHAR2(50) 
, XPE_ROLLOVER_TYPE VARCHAR2(3) 
, XPE_RESET_TYPE VARCHAR2(3) 
, XPE_PERIOD_TYPE VARCHAR2(3) 
, XPE_PERIOD_NBR NUMBER(1, 0) 
, XPE_ICON VARCHAR2(20) 
, CONSTRAINT XPE_DCC_CONTRACT_PRICING_T_PK PRIMARY KEY 
  (
    XPE_CONTRACT_ID 
  , XPE_PRICING_TERM_LINE 
  , XPE_CONTRACT_LINE 
  , XPE_CONTRACT_VERSION 
  )
  ENABLE 
);

CREATE TABLE XPE_DCC_CONTRACT_CARRIER 
(
  XPE_CONTRACT_ID VARCHAR2(20) NOT NULL 
, XPE_PRICING_TERM_LINE NUMBER NOT NULL 
, XPE_CONTRACT_LINE VARCHAR2(20) NOT NULL 
, XPE_CONTRACT_VERSION VARCHAR2(20) NOT NULL 
, XPE_CARRIER_ID VARCHAR2(20) NOT NULL 
, XPE_VEHICLE_TYPE VARCHAR2(3) NOT NULL 
, XPE_SUB_NBR NUMBER(2) NOT NULL 
, XPE_VEHICLE_NBR VARCHAR2(20) NOT NULL 
, XPE_RATE_OVERRIDE NUMBER(5, 5) 
, XPE_SURCHARGE NUMBER(5, 5) 
, CONSTRAINT XPE_DCC_CONTRACT_CARRIER_PK PRIMARY KEY 
  (
    XPE_CONTRACT_ID 
  , XPE_PRICING_TERM_LINE 
  , XPE_CONTRACT_LINE 
  , XPE_CONTRACT_VERSION 
  , XPE_CARRIER_ID 
  , XPE_VEHICLE_TYPE 
  , XPE_SUB_NBR 
  , XPE_VEHICLE_NBR 
  )
  ENABLE 
);

CREATE TABLE XPE_DCC_CONTRACT_PRICING_OVER 
(
  XPE_CONTRACT_ID VARCHAR2(20) NOT NULL 
, XPE_PRICING_TERM_LINE NUMBER NOT NULL 
, XPE_CONTRACT_LINE VARCHAR2(20) NOT NULL 
, XPE_CONTRACT_VERSION VARCHAR2(20) NOT NULL 
, XPE_CONTRACT_OVER_NBR NUMBER NOT NULL 
, XPE_OVER_TYPE VARCHAR2(3) 
, XPE_OVER_START TIMESTAMP 
, XPE_OVER_END TIMESTAMP 
, XPE_SOURCE_FLD VARCHAR2(20) 
, XPE_CONDITION VARCHAR2(3) 
, XPE_CHECK VARCHAR2(20) 
, XPE_TARGET_FLD VARCHAR2(20) 
, XPE_OVER_MSG VARCHAR2(50) 
, XPE_OVER_DESC VARCHAR2(50) 
, CONSTRAINT XPE_DCC_CONTRACT_PRICING_O_PK PRIMARY KEY 
  (
    XPE_CONTRACT_ID 
  , XPE_PRICING_TERM_LINE 
  , XPE_CONTRACT_LINE 
  , XPE_CONTRACT_VERSION 
  , XPE_CONTRACT_OVER_NBR 
  )
  ENABLE 
);

CREATE TABLE XPE_DCC_CONTRACT_CARRIER_OVER 
(
  XPE_CONTRACT_ID VARCHAR2(20) NOT NULL 
, XPE_PRICING_TERM_LINE NUMBER NOT NULL 
, XPE_CONTRACT_LINE VARCHAR2(20) NOT NULL 
, XPE_CONTRACT_VERSION VARCHAR2(20) NOT NULL 
, XPE_CARRIER_ID VARCHAR2(20) NOT NULL 
, XPE_CARRIER_OVER_ID NUMBER NOT NULL 
, XPE_VEHICLE_TYPE VARCHAR2(3) NOT NULL 
, XPE_SUB_NBR NUMBER(2) NOT NULL 
, XPE_VEHICLE_NBR VARCHAR2(20) NOT NULL 
, XPE_OVER_TYPE VARCHAR2(3) 
, XPE_OVER_START TIMESTAMP 
, XPE_OVER_END TIMESTAMP 
, XPE_SOURCE_FLD VARCHAR2(20) 
, XPE_CONDITION VARCHAR2(3) 
, XPE_CHECK VARCHAR2(20) 
, XPE_TARGET_FLD VARCHAR2(20) 
, XPE_OVER_MSG VARCHAR2(50) 
, XPE_OVER_DESC VARCHAR2(50) 
, CONSTRAINT XPE_DCC_CONTRACT_CARRIER_O_PK PRIMARY KEY 
  (
    XPE_CONTRACT_ID 
  , XPE_PRICING_TERM_LINE 
  , XPE_CONTRACT_LINE 
  , XPE_CONTRACT_VERSION 
  , XPE_CARRIER_OVER_ID 
  , XPE_CARRIER_ID 
  , XPE_VEHICLE_TYPE 
  , XPE_SUB_NBR 
  , XPE_VEHICLE_NBR 
  )
  ENABLE 
);

CREATE INDEX PS0CUSTOMER ON PS_CUSTOMER (NAME1 ASC, SETID ASC, CUST_ID ASC) 
LOGGING 
TABLESPACE PSINDEX 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 40960 
  NEXT 106496 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX PS1CUSTOMER ON PS_CUSTOMER (CNTCT_SEQ_NUM ASC, SETID ASC, CUST_ID ASC) 
LOGGING 
TABLESPACE PSINDEX 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 40960 
  NEXT 106496 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX PSACUSTOMER ON PS_CUSTOMER (CORPORATE_CUST_ID ASC, CORPORATE_SETID ASC, CUST_ID ASC, SETID ASC) 
LOGGING 
TABLESPACE PSINDEX 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 139264 
  NEXT 106496 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX PSBCUSTOMER ON PS_CUSTOMER (REMIT_FROM_CUST_ID ASC, REMIT_FROM_SETID ASC) 
LOGGING 
TABLESPACE PSINDEX 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 40960 
  NEXT 106496 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX PSCCUSTOMER ON PS_CUSTOMER (CRSPD_CUST_ID ASC, CRSPD_SETID ASC) 
LOGGING 
TABLESPACE PSINDEX 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 40960 
  NEXT 106496 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX PSDCUSTOMER ON PS_CUSTOMER (CRSPD_CUST_ID ASC, CRSPD_SETID ASC, CUST_ID ASC, SETID ASC, CNTCT_SEQ_NUM ASC) 
LOGGING 
TABLESPACE PSINDEX 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 40960 
  NEXT 106496 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX PSECUSTOMER ON PS_CUSTOMER (VENDOR_SETID ASC, VENDOR_ID ASC) 
LOGGING 
TABLESPACE PSINDEX 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 40960 
  NEXT 106496 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX PSFCUSTOMER ON PS_CUSTOMER (PARENT_CUST_ID ASC, PARENT_SETID ASC) 
LOGGING 
TABLESPACE PSINDEX 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 40960 
  NEXT 106496 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX PS_CUSTOMER ON PS_CUSTOMER (CUST_ID ASC, SETID ASC) 
LOGGING 
TABLESPACE PSINDEX 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 24576 
  NEXT 106496 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX PSACUST_ADDRESS ON PS_CUST_ADDRESS (CUST_ID ASC, SETID ASC) 
LOGGING 
TABLESPACE PSINDEX 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 40960 
  NEXT 106496 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX PS_CUST_ADDRESS ON PS_CUST_ADDRESS (CUST_ID ASC, SETID ASC, ADDRESS_SEQ_NUM ASC, "EFFDT" DESC) 
LOGGING 
TABLESPACE PSINDEX 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 24576 
  NEXT 106496 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX PS_CUST_ADDR_SEQ ON PS_CUST_ADDR_SEQ (CUST_ID ASC, SETID ASC, ADDRESS_SEQ_NUM ASC) 
LOGGING 
TABLESPACE PSINDEX 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 24576 
  NEXT 106496 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX PS0ITEM ON PS_ITEM (ITEM_STATUS ASC, BUSINESS_UNIT ASC, CUST_ID ASC, ITEM ASC, ITEM_LINE ASC) 
LOGGING 
TABLESPACE PSINDEX 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 40960 
  NEXT 106496 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX PS1ITEM ON PS_ITEM (CR_ANALYST ASC, BUSINESS_UNIT ASC, CUST_ID ASC, ITEM ASC, ITEM_LINE ASC) 
LOGGING 
TABLESPACE PSINDEX 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 40960 
  NEXT 106496 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX PS2ITEM ON PS_ITEM (COLLECTOR ASC, BUSINESS_UNIT ASC, CUST_ID ASC, ITEM ASC, ITEM_LINE ASC) 
LOGGING 
TABLESPACE PSINDEX 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 40960 
  NEXT 106496 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX PS3ITEM ON PS_ITEM (PO_REF ASC, BUSINESS_UNIT ASC, CUST_ID ASC, ITEM ASC, ITEM_LINE ASC) 
LOGGING 
TABLESPACE PSINDEX 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 40960 
  NEXT 106496 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX PS4ITEM ON PS_ITEM (DOCUMENT ASC, BUSINESS_UNIT ASC, CUST_ID ASC, ITEM ASC, ITEM_LINE ASC) 
LOGGING 
TABLESPACE PSINDEX 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 40960 
  NEXT 106496 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX PS5ITEM ON PS_ITEM (BILL_OF_LADING ASC, BUSINESS_UNIT ASC, CUST_ID ASC, ITEM ASC, ITEM_LINE ASC) 
LOGGING 
TABLESPACE PSINDEX 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 40960 
  NEXT 106496 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX PSAITEM ON PS_ITEM (DRAFT_ID ASC, DRAFT_BU ASC) 
LOGGING 
TABLESPACE PSINDEX 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 131072 
  NEXT 106496 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX PSBITEM ON PS_ITEM (BAL_CURRENCY ASC) 
LOGGING 
TABLESPACE PSINDEX 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 40960 
  NEXT 106496 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX PSCITEM ON PS_ITEM (ITEM ASC, ITEM_STATUS ASC, CURRENCY_CD ASC) 
LOGGING 
TABLESPACE PSINDEX 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 40960 
  NEXT 106496 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX PSDITEM ON PS_ITEM (CUST_ID ASC, ITEM ASC) 
LOGGING 
TABLESPACE PSINDEX 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 40960 
  NEXT 106496 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX PSEITEM ON PS_ITEM (BUSINESS_UNIT ASC, CUST_ID ASC, ITEM ASC, ITEM_LINE_ORIG ASC, OVERDUE_CHG_LINE ASC) 
LOGGING 
TABLESPACE PSINDEX 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 40960 
  NEXT 106496 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX PSFITEM ON PS_ITEM (PROCESS_INSTANCE ASC, BUSINESS_UNIT ASC, CUST_ID ASC, ITEM ASC, ITEM_LINE ASC) 
LOGGING 
TABLESPACE PSINDEX 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 40960 
  NEXT 106496 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX PS_ITEM ON PS_ITEM (BUSINESS_UNIT ASC, CUST_ID ASC, ITEM ASC, ITEM_LINE ASC) 
LOGGING 
TABLESPACE PSINDEX 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 40960 
  NEXT 106496 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE XPE_DCC_CONTRACT_CARRIER
ADD CONSTRAINT XPE_DCC_CONTRACT_CARRIER_FK1 FOREIGN KEY
(
  XPE_CONTRACT_ID 
, XPE_PRICING_TERM_LINE 
, XPE_CONTRACT_LINE 
, XPE_CONTRACT_VERSION 
)
REFERENCES XPE_DCC_CONTRACT_PRICING_TERM
(
  XPE_CONTRACT_ID 
, XPE_PRICING_TERM_LINE 
, XPE_CONTRACT_LINE 
, XPE_CONTRACT_VERSION 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE XPE_DCC_CONTRACT_CARRIER
ADD CONSTRAINT XPE_DCC_CONTRACT_CARRIER_FK2 FOREIGN KEY
(
  XPE_CARRIER_ID 
)
REFERENCES XPE_DCC_CARRIERS
(
  XPE_CARRIER_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE XPE_DCC_CONTRACT_CARRIER_OVER
ADD CONSTRAINT XPE_DCC_CONTRACT_CARRIER__FK2 FOREIGN KEY
(
  XPE_CONTRACT_ID 
, XPE_PRICING_TERM_LINE 
, XPE_CONTRACT_LINE 
, XPE_CONTRACT_VERSION 
, XPE_CARRIER_ID 
, XPE_VEHICLE_TYPE 
, XPE_SUB_NBR 
, XPE_VEHICLE_NBR 
)
REFERENCES XPE_DCC_CONTRACT_CARRIER
(
  XPE_CONTRACT_ID 
, XPE_PRICING_TERM_LINE 
, XPE_CONTRACT_LINE 
, XPE_CONTRACT_VERSION 
, XPE_CARRIER_ID 
, XPE_VEHICLE_TYPE 
, XPE_SUB_NBR 
, XPE_VEHICLE_NBR 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE XPE_DCC_CONTRACT_DOC_TERM
ADD CONSTRAINT XPE_DCC_CONTRACT_DOC_TERM_FK1 FOREIGN KEY
(
  XPE_CONTRACT_ID 
, XPE_CONTRACT_VERSION 
, XPE_CONTRACT_LINE 
)
REFERENCES XPE_DCC_CONTRACT_LINE
(
  XPE_CONTRACT_ID 
, XPE_CONTRACT_VERSION 
, XPE_CONTRACT_LINE 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE XPE_DCC_CONTRACT_LINE
ADD CONSTRAINT XPE_DCC_CONTRACT_LINE_FK1 FOREIGN KEY
(
  XPE_CONTRACT_ID 
, XPE_CONTRACT_VERSION 
)
REFERENCES XPE_DCC_CONTRACT_VERSION
(
  XPE_CONTRACT_ID 
, XPE_CONTRACT_VERSION 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE XPE_DCC_CONTRACT_NOTES
ADD CONSTRAINT XPE_DCC_CONTRACT_NOTES_FK1 FOREIGN KEY
(
  XPE_CONTRACT_ID 
, XPE_CONTRACT_VERSION 
)
REFERENCES XPE_DCC_CONTRACT_VERSION
(
  XPE_CONTRACT_ID 
, XPE_CONTRACT_VERSION 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE XPE_DCC_CONTRACT_PARTY
ADD CONSTRAINT XPE_DCC_CONTRACT_PARTY_FK1 FOREIGN KEY
(
  XPE_CONTRACT_ID 
)
REFERENCES XPE_DCC_CONTRACTS
(
  XPE_CONTRACT_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE XPE_DCC_CONTRACT_PRICING_OVER
ADD CONSTRAINT XPE_DCC_CONTRACT_PRICING__FK2 FOREIGN KEY
(
  XPE_CONTRACT_ID 
, XPE_PRICING_TERM_LINE 
, XPE_CONTRACT_LINE 
, XPE_CONTRACT_VERSION 
)
REFERENCES XPE_DCC_CONTRACT_PRICING_TERM
(
  XPE_CONTRACT_ID 
, XPE_PRICING_TERM_LINE 
, XPE_CONTRACT_LINE 
, XPE_CONTRACT_VERSION 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE XPE_DCC_CONTRACT_PRICING_TERM
ADD CONSTRAINT XPE_DCC_CONTRACT_PRICING__FK1 FOREIGN KEY
(
  XPE_CONTRACT_ID 
, XPE_CONTRACT_VERSION 
, XPE_CONTRACT_LINE 
)
REFERENCES XPE_DCC_CONTRACT_LINE
(
  XPE_CONTRACT_ID 
, XPE_CONTRACT_VERSION 
, XPE_CONTRACT_LINE 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE XPE_DCC_CONTRACT_VERSION
ADD CONSTRAINT XPE_DCC_CONTRACT_VERSION_FK1 FOREIGN KEY
(
  XPE_CONTRACT_ID 
)
REFERENCES XPE_DCC_CONTRACTS
(
  XPE_CONTRACT_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE XPE_DCC_PLATFORM_EVENT
ADD CONSTRAINT XPE_DCC_PLATFORM_EVENT_FK1 FOREIGN KEY
(
  XPE_CONTRACT_ID 
)
REFERENCES XPE_DCC_CONTRACTS
(
  XPE_CONTRACT_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE XPE_DCC_WORKFLOW
ADD CONSTRAINT XPE_DCC_WORKFLOW_FK1 FOREIGN KEY
(
  XPE_CONTRACT_ID 
, XPE_CONTRACT_VERSION 
)
REFERENCES XPE_DCC_CONTRACT_VERSION
(
  XPE_CONTRACT_ID 
, XPE_CONTRACT_VERSION 
)
ENABLE;

COMMENT ON COLUMN XPE_DCC_CARRIERS.XPE_CARRIER_ID IS 'Carrier Id';

COMMENT ON COLUMN XPE_DCC_CARRIERS.XPE_CARRIER_DESC IS 'Carrier Name';

COMMENT ON COLUMN XPE_DCC_CONTRACTS.XPE_CONTRACT_DESC IS 'Contract Description';

COMMENT ON COLUMN XPE_DCC_LOOKUP_MASTER.XPE_LOOKUP_TYPE IS 'Lookup type';

COMMENT ON COLUMN XPE_DCC_LOOKUP_MASTER.XPE_LOOKUP_ID IS 'Lookup code';

COMMENT ON COLUMN XPE_DCC_LOOKUP_MASTER.XPE_LOOKUP_DESC IS 'Description';
