package model.views.readonly;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 02 22:54:40 EDT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ContractDuplicateCheckROVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ContractDuplicateCheckROVOImpl() {
    }

    /**
     * Returns the bind variable value for bind_CustId.
     * @return bind variable value for bind_CustId
     */
    public String getbind_CustId() {
        return (String) getNamedWhereClauseParam("bind_CustId");
    }

    /**
     * Sets <code>value</code> for bind variable bind_CustId.
     * @param value value to bind as bind_CustId
     */
    public void setbind_CustId(String value) {
        setNamedWhereClauseParam("bind_CustId", value);
    }
}

