package model.views.readonly;

import java.math.BigDecimal;

import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 23 16:19:53 EDT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XpeDccCfgBillingandAccountingROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        XpeFacilityId,
        XpeBillCycleId,
        XpeBillDate;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int XPEFACILITYID = AttributesEnum.XpeFacilityId.index();
    public static final int XPEBILLCYCLEID = AttributesEnum.XpeBillCycleId.index();
    public static final int XPEBILLDATE = AttributesEnum.XpeBillDate.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XpeDccCfgBillingandAccountingROVORowImpl() {
    }


    /**
     * Gets the attribute value for the calculated attribute XpeFacilityId.
     * @return the XpeFacilityId
     */
    public String getXpeFacilityId() {
        return (String) getAttributeInternal(XPEFACILITYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute XpeFacilityId.
     * @param value value to set the  XpeFacilityId
     */
    public void setXpeFacilityId(String value) {
        setAttributeInternal(XPEFACILITYID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute XpeBillCycleId.
     * @return the XpeBillCycleId
     */
    public String getXpeBillCycleId() {
        return (String) getAttributeInternal(XPEBILLCYCLEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute XpeBillCycleId.
     * @param value value to set the  XpeBillCycleId
     */
    public void setXpeBillCycleId(String value) {
        setAttributeInternal(XPEBILLCYCLEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute XpeBillDate.
     * @return the XpeBillDate
     */
    public Date getXpeBillDate() {
        return (Date) getAttributeInternal(XPEBILLDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute XpeBillDate.
     * @param value value to set the  XpeBillDate
     */
    public void setXpeBillDate(Date value) {
        setAttributeInternal(XPEBILLDATE, value);
    }
}

