package model.views.readonly;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 21 07:52:36 EDT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XpeDccTermsForMasterTermROVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public XpeDccTermsForMasterTermROVOImpl() {
    }

    /**
     * Returns the bind variable value for bind_Term.
     * @return bind variable value for bind_Term
     */
    public String getbind_Term() {
        return (String) getNamedWhereClauseParam("bind_Term");
    }

    /**
     * Sets <code>value</code> for bind variable bind_Term.
     * @param value value to bind as bind_Term
     */
    public void setbind_Term(String value) {
        setNamedWhereClauseParam("bind_Term", value);
    }
}

