package model.views.readonly;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jan 31 14:00:13 EST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XpeDccUserInfoROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Id,
        USER_NAME;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int USER_NAME = AttributesEnum.USER_NAME.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XpeDccUserInfoROVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute Id.
     * @return the Id
     */
    public BigDecimal getId() {
        return (BigDecimal) getAttributeInternal(ID);
    }

    /**
     * Gets the attribute value for the calculated attribute USER_NAME.
     * @return the USER_NAME
     */
    public String getUSER_NAME() {
        return (String) getAttributeInternal(USER_NAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute USER_NAME.
     * @param value value to set the  USER_NAME
     */
    public void setUSER_NAME(String value) {
        setAttributeInternal(USER_NAME, value);
    }
}

