package model.views.readonly;

import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 11 18:47:12 EDT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XpeDccCfgTerminalsSearchROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        TerminalId,
        TerminalDesc,
        TerminalType,
        State,
        County,
        LookupSharedAppModule_XpeDccDicNewContractSetupROVO1,
        XpeDccCfgCountiesROVO1,
        XpeDccCfgStatesROVO1,
        XpeDccGeneralItemListROVO1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int TERMINALID = AttributesEnum.TerminalId.index();
    public static final int TERMINALDESC = AttributesEnum.TerminalDesc.index();
    public static final int TERMINALTYPE = AttributesEnum.TerminalType.index();
    public static final int STATE = AttributesEnum.State.index();
    public static final int COUNTY = AttributesEnum.County.index();
    public static final int LOOKUPSHAREDAPPMODULE_XPEDCCDICNEWCONTRACTSETUPROVO1 =
        AttributesEnum.LookupSharedAppModule_XpeDccDicNewContractSetupROVO1.index();
    public static final int XPEDCCCFGCOUNTIESROVO1 = AttributesEnum.XpeDccCfgCountiesROVO1.index();
    public static final int XPEDCCCFGSTATESROVO1 = AttributesEnum.XpeDccCfgStatesROVO1.index();
    public static final int XPEDCCGENERALITEMLISTROVO1 = AttributesEnum.XpeDccGeneralItemListROVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XpeDccCfgTerminalsSearchROVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute TerminalId.
     * @return the TerminalId
     */
    public String getTerminalId() {
        return (String) getAttributeInternal(TERMINALID);
    }

    /**
     * Gets the attribute value for the calculated attribute TerminalDesc.
     * @return the TerminalDesc
     */
    public String getTerminalDesc() {
        return (String) getAttributeInternal(TERMINALDESC);
    }

    /**
     * Gets the attribute value for the calculated attribute TerminalType.
     * @return the TerminalType
     */
    public String getTerminalType() {
        return (String) getAttributeInternal(TERMINALTYPE);
    }

    /**
     * Gets the attribute value for the calculated attribute State.
     * @return the State
     */
    public String getState() {
        return (String) getAttributeInternal(STATE);
    }

    /**
     * Gets the attribute value for the calculated attribute County.
     * @return the County
     */
    public String getCounty() {
        return (String) getAttributeInternal(COUNTY);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LookupSharedAppModule_XpeDccDicNewContractSetupROVO1.
     */
    public RowSet getLookupSharedAppModule_XpeDccDicNewContractSetupROVO1() {
        return (RowSet) getAttributeInternal(LOOKUPSHAREDAPPMODULE_XPEDCCDICNEWCONTRACTSETUPROVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> XpeDccCfgCountiesROVO1.
     */
    public RowSet getXpeDccCfgCountiesROVO1() {
        return (RowSet) getAttributeInternal(XPEDCCCFGCOUNTIESROVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> XpeDccCfgStatesROVO1.
     */
    public RowSet getXpeDccCfgStatesROVO1() {
        return (RowSet) getAttributeInternal(XPEDCCCFGSTATESROVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> XpeDccGeneralItemListROVO1.
     */
    public RowSet getXpeDccGeneralItemListROVO1() {
        return (RowSet) getAttributeInternal(XPEDCCGENERALITEMLISTROVO1);
    }
}

