package model.views.readonly;

import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 13 16:34:06 EST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XpeDccCfgAccrualandRevenueGenerationROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        XpeFacilityId,
        XpeJournalGeneratorTemplate,
        XpeAccountingDate;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int XPEFACILITYID = AttributesEnum.XpeFacilityId.index();
    public static final int XPEJOURNALGENERATORTEMPLATE = AttributesEnum.XpeJournalGeneratorTemplate.index();
    public static final int XPEACCOUNTINGDATE = AttributesEnum.XpeAccountingDate.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XpeDccCfgAccrualandRevenueGenerationROVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute XpeFacilityId.
     * @return the XpeFacilityId
     */
    public String getXpeFacilityId() {
        return (String) getAttributeInternal(XPEFACILITYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute XpeFacilityId.
     * @param value value to set the  XpeFacilityId
     */
    public void setXpeFacilityId(String value) {
        setAttributeInternal(XPEFACILITYID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute XpeJournalGeneratorTemplate.
     * @return the XpeJournalGeneratorTemplate
     */
    public String getXpeJournalGeneratorTemplate() {
        return (String) getAttributeInternal(XPEJOURNALGENERATORTEMPLATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute XpeJournalGeneratorTemplate.
     * @param value value to set the  XpeJournalGeneratorTemplate
     */
    public void setXpeJournalGeneratorTemplate(String value) {
        setAttributeInternal(XPEJOURNALGENERATORTEMPLATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute XpeAccountingDate.
     * @return the XpeAccountingDate
     */
    public Date getXpeAccountingDate() {
        return (Date) getAttributeInternal(XPEACCOUNTINGDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute XpeAccountingDate.
     * @param value value to set the  XpeAccountingDate
     */
    public void setXpeAccountingDate(Date value) {
        setAttributeInternal(XPEACCOUNTINGDATE, value);
    }
}

