package model.views.readonly;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 27 00:33:53 EDT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XpeDccCfgCountiesROVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public XpeDccCfgCountiesROVOImpl() {
    }

    /**
     * Returns the variable value for bindCountyName.
     * @return variable value for bindCountyName
     */
    public String getbindCountyName() {
        return (String) ensureVariableManager().getVariableValue("bindCountyName");
    }

    /**
     * Sets <code>value</code> for variable bindCountyName.
     * @param value value to bind as bindCountyName
     */
    public void setbindCountyName(String value) {
        ensureVariableManager().setVariableValue("bindCountyName", value);
    }

    /**
     * Returns the variable value for bindState.
     * @return variable value for bindState
     */
    public String getbindState() {
        return (String) ensureVariableManager().getVariableValue("bindState");
    }

    /**
     * Sets <code>value</code> for variable bindState.
     * @param value value to bind as bindState
     */
    public void setbindState(String value) {
        ensureVariableManager().setVariableValue("bindState", value);
    }

    /**
     * Returns the variable value for bindCountyId.
     * @return variable value for bindCountyId
     */
    public String getbindCountyId() {
        return (String) ensureVariableManager().getVariableValue("bindCountyId");
    }

    /**
     * Sets <code>value</code> for variable bindCountyId.
     * @param value value to bind as bindCountyId
     */
    public void setbindCountyId(String value) {
        ensureVariableManager().setVariableValue("bindCountyId", value);
    }
}

