package model.views.readonly;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 11 19:33:03 EDT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XpeDccCfgDstAssTerminalsROVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public XpeDccCfgDstAssTerminalsROVOImpl() {
    }

    /**
     * Returns the variable value for bind_DestinationId.
     * @return variable value for bind_DestinationId
     */
    public String getbind_DestinationId() {
        return (String) ensureVariableManager().getVariableValue("bind_DestinationId");
    }

    /**
     * Sets <code>value</code> for variable bind_DestinationId.
     * @param value value to bind as bind_DestinationId
     */
    public void setbind_DestinationId(String value) {
        ensureVariableManager().setVariableValue("bind_DestinationId", value);
    }

    /**
     * Returns the variable value for bind_TerminalId.
     * @return variable value for bind_TerminalId
     */
    public String getbind_TerminalId() {
        return (String) ensureVariableManager().getVariableValue("bind_TerminalId");
    }

    /**
     * Sets <code>value</code> for variable bind_TerminalId.
     * @param value value to bind as bind_TerminalId
     */
    public void setbind_TerminalId(String value) {
        ensureVariableManager().setVariableValue("bind_TerminalId", value);
    }
}

