package model.entities;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 29 15:54:12 EST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XpeDccCfgBusinessunitEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        BusinessUnit,
        TerminalId,
        SiteId,
        SiteDesc,
        AccountingClass,
        StatsOnly,
        Inactive,
        InactiveDate,
        BillingBusinessUnit,
        BusinessUnitRef,
        GlBusinessUnit,
        Affliate,
        OperatingUnit,
        CreatedBy,
        CreatedDate,
        LastUpdatedBy,
        LastUpdatedDate,
        BillingGlBusinessUnit,
        BillingAffiliate,
        BillingOperatingUnit,
        BusinessunitId;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BUSINESSUNIT = AttributesEnum.BusinessUnit.index();
    public static final int TERMINALID = AttributesEnum.TerminalId.index();
    public static final int SITEID = AttributesEnum.SiteId.index();
    public static final int SITEDESC = AttributesEnum.SiteDesc.index();
    public static final int ACCOUNTINGCLASS = AttributesEnum.AccountingClass.index();
    public static final int STATSONLY = AttributesEnum.StatsOnly.index();
    public static final int INACTIVE = AttributesEnum.Inactive.index();
    public static final int INACTIVEDATE = AttributesEnum.InactiveDate.index();
    public static final int BILLINGBUSINESSUNIT = AttributesEnum.BillingBusinessUnit.index();
    public static final int BUSINESSUNITREF = AttributesEnum.BusinessUnitRef.index();
    public static final int GLBUSINESSUNIT = AttributesEnum.GlBusinessUnit.index();
    public static final int AFFLIATE = AttributesEnum.Affliate.index();
    public static final int OPERATINGUNIT = AttributesEnum.OperatingUnit.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int BILLINGGLBUSINESSUNIT = AttributesEnum.BillingGlBusinessUnit.index();
    public static final int BILLINGAFFILIATE = AttributesEnum.BillingAffiliate.index();
    public static final int BILLINGOPERATINGUNIT = AttributesEnum.BillingOperatingUnit.index();
    public static final int BUSINESSUNITID = AttributesEnum.BusinessunitId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XpeDccCfgBusinessunitEOImpl() {
    }

    /**
     * Gets the attribute value for BusinessUnit, using the alias name BusinessUnit.
     * @return the value of BusinessUnit
     */
    public String getBusinessUnit() {
        return (String) getAttributeInternal(BUSINESSUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for BusinessUnit.
     * @param value value to set the BusinessUnit
     */
    public void setBusinessUnit(String value) {
        setAttributeInternal(BUSINESSUNIT, value);
    }

    /**
     * Gets the attribute value for TerminalId, using the alias name TerminalId.
     * @return the value of TerminalId
     */
    public String getTerminalId() {
        return (String) getAttributeInternal(TERMINALID);
    }

    /**
     * Sets <code>value</code> as the attribute value for TerminalId.
     * @param value value to set the TerminalId
     */
    public void setTerminalId(String value) {
        setAttributeInternal(TERMINALID, value);
    }

    /**
     * Gets the attribute value for SiteId, using the alias name SiteId.
     * @return the value of SiteId
     */
    public String getSiteId() {
        return (String) getAttributeInternal(SITEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SiteId.
     * @param value value to set the SiteId
     */
    public void setSiteId(String value) {
        setAttributeInternal(SITEID, value);
    }

    /**
     * Gets the attribute value for SiteDesc, using the alias name SiteDesc.
     * @return the value of SiteDesc
     */
    public String getSiteDesc() {
        return (String) getAttributeInternal(SITEDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for SiteDesc.
     * @param value value to set the SiteDesc
     */
    public void setSiteDesc(String value) {
        setAttributeInternal(SITEDESC, value);
    }

    /**
     * Gets the attribute value for AccountingClass, using the alias name AccountingClass.
     * @return the value of AccountingClass
     */
    public String getAccountingClass() {
        return (String) getAttributeInternal(ACCOUNTINGCLASS);
    }

    /**
     * Sets <code>value</code> as the attribute value for AccountingClass.
     * @param value value to set the AccountingClass
     */
    public void setAccountingClass(String value) {
        setAttributeInternal(ACCOUNTINGCLASS, value);
    }

    /**
     * Gets the attribute value for StatsOnly, using the alias name StatsOnly.
     * @return the value of StatsOnly
     */
    public String getStatsOnly() {
        return (String) getAttributeInternal(STATSONLY);
    }

    /**
     * Sets <code>value</code> as the attribute value for StatsOnly.
     * @param value value to set the StatsOnly
     */
    public void setStatsOnly(String value) {
        setAttributeInternal(STATSONLY, value);
    }

    /**
     * Gets the attribute value for Inactive, using the alias name Inactive.
     * @return the value of Inactive
     */
    public String getInactive() {
        return (String) getAttributeInternal(INACTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Inactive.
     * @param value value to set the Inactive
     */
    public void setInactive(String value) {
        setAttributeInternal(INACTIVE, value);
    }

    /**
     * Gets the attribute value for InactiveDate, using the alias name InactiveDate.
     * @return the value of InactiveDate
     */
    public Timestamp getInactiveDate() {
        return (Timestamp) getAttributeInternal(INACTIVEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for InactiveDate.
     * @param value value to set the InactiveDate
     */
    public void setInactiveDate(Timestamp value) {
        setAttributeInternal(INACTIVEDATE, value);
    }

    /**
     * Gets the attribute value for BillingBusinessUnit, using the alias name BillingBusinessUnit.
     * @return the value of BillingBusinessUnit
     */
    public String getBillingBusinessUnit() {
        return (String) getAttributeInternal(BILLINGBUSINESSUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for BillingBusinessUnit.
     * @param value value to set the BillingBusinessUnit
     */
    public void setBillingBusinessUnit(String value) {
        setAttributeInternal(BILLINGBUSINESSUNIT, value);
    }

    /**
     * Gets the attribute value for BusinessUnitRef, using the alias name BusinessUnitRef.
     * @return the value of BusinessUnitRef
     */
    public String getBusinessUnitRef() {
        return (String) getAttributeInternal(BUSINESSUNITREF);
    }

    /**
     * Sets <code>value</code> as the attribute value for BusinessUnitRef.
     * @param value value to set the BusinessUnitRef
     */
    public void setBusinessUnitRef(String value) {
        setAttributeInternal(BUSINESSUNITREF, value);
    }

    /**
     * Gets the attribute value for GlBusinessUnit, using the alias name GlBusinessUnit.
     * @return the value of GlBusinessUnit
     */
    public String getGlBusinessUnit() {
        return (String) getAttributeInternal(GLBUSINESSUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for GlBusinessUnit.
     * @param value value to set the GlBusinessUnit
     */
    public void setGlBusinessUnit(String value) {
        setAttributeInternal(GLBUSINESSUNIT, value);
    }

    /**
     * Gets the attribute value for Affliate, using the alias name Affliate.
     * @return the value of Affliate
     */
    public String getAffliate() {
        return (String) getAttributeInternal(AFFLIATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Affliate.
     * @param value value to set the Affliate
     */
    public void setAffliate(String value) {
        setAttributeInternal(AFFLIATE, value);
    }

    /**
     * Gets the attribute value for OperatingUnit, using the alias name OperatingUnit.
     * @return the value of OperatingUnit
     */
    public String getOperatingUnit() {
        return (String) getAttributeInternal(OPERATINGUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for OperatingUnit.
     * @param value value to set the OperatingUnit
     */
    public void setOperatingUnit(String value) {
        setAttributeInternal(OPERATINGUNIT, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the value of LastUpdatedDate
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for BillingGlBusinessUnit, using the alias name BillingGlBusinessUnit.
     * @return the value of BillingGlBusinessUnit
     */
    public String getBillingGlBusinessUnit() {
        return (String) getAttributeInternal(BILLINGGLBUSINESSUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for BillingGlBusinessUnit.
     * @param value value to set the BillingGlBusinessUnit
     */
    public void setBillingGlBusinessUnit(String value) {
        setAttributeInternal(BILLINGGLBUSINESSUNIT, value);
    }

    /**
     * Gets the attribute value for BillingAffiliate, using the alias name BillingAffiliate.
     * @return the value of BillingAffiliate
     */
    public String getBillingAffiliate() {
        return (String) getAttributeInternal(BILLINGAFFILIATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for BillingAffiliate.
     * @param value value to set the BillingAffiliate
     */
    public void setBillingAffiliate(String value) {
        setAttributeInternal(BILLINGAFFILIATE, value);
    }

    /**
     * Gets the attribute value for BillingOperatingUnit, using the alias name BillingOperatingUnit.
     * @return the value of BillingOperatingUnit
     */
    public String getBillingOperatingUnit() {
        return (String) getAttributeInternal(BILLINGOPERATINGUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for BillingOperatingUnit.
     * @param value value to set the BillingOperatingUnit
     */
    public void setBillingOperatingUnit(String value) {
        setAttributeInternal(BILLINGOPERATINGUNIT, value);
    }

    /**
     * Gets the attribute value for BusinessunitId, using the alias name BusinessunitId.
     * @return the value of BusinessunitId
     */
    public String getBusinessunitId() {
        return (String) getAttributeInternal(BUSINESSUNITID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BusinessunitId.
     * @param value value to set the BusinessunitId
     */
    public void setBusinessunitId(String value) {
        setAttributeInternal(BUSINESSUNITID, value);
    }

    /**
     * @param businessunitId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String businessunitId) {
        return new Key(new Object[] { businessunitId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.entities.XpeDccCfgBusinessunitEO");
    }


    protected String nextVal(String sequenceName) {
        SequenceImpl s = new SequenceImpl(sequenceName, getDBTransaction());
        return s.getSequenceNumber().toString();
    }
    
    @Override
    protected void doDML(int i, TransactionEvent transactionEvent) {
        // TODO Implement this method
        String userName = "DB_ADMIN";
        ViewObjectImpl userInfoVO = (ViewObjectImpl)this.getDBTransaction().getRootApplicationModule().findViewObject("XpeDccUserInfoROVO");
        Row userInforVORow = userInfoVO.first();
        if(null!=userInforVORow)
            userName = (String)userInforVORow.getAttribute("USER_NAME");
        //INSERT
        if(i==this.DML_INSERT){
            this.setCreatedBy(userName);
            this.setLastUpdatedBy(userName);
        }
        //UPDATE
        if(i==this.DML_UPDATE) 
            this.setLastUpdatedBy(userName);
        
        super.doDML(i, transactionEvent);
    }
}

