package model.entities;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 01 23:11:32 CDT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XpeDccCfgNycDosTermCustEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        OriginId,
        TerminalId,
        PcsshortnameId,
        Inactive,
        InactiveDate,
        CreatedBy,
        CreatedDate,
        LastUpdatedBy,
        LastUpdatedDate,
        XpeDccCfgOgnAssTerminalsEO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ORIGINID = AttributesEnum.OriginId.index();
    public static final int TERMINALID = AttributesEnum.TerminalId.index();
    public static final int PCSSHORTNAMEID = AttributesEnum.PcsshortnameId.index();
    public static final int INACTIVE = AttributesEnum.Inactive.index();
    public static final int INACTIVEDATE = AttributesEnum.InactiveDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int XPEDCCCFGOGNASSTERMINALSEO = AttributesEnum.XpeDccCfgOgnAssTerminalsEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XpeDccCfgNycDosTermCustEOImpl() {
    }

    /**
     * Gets the attribute value for OriginId, using the alias name OriginId.
     * @return the value of OriginId
     */
    public String getOriginId() {
        return (String) getAttributeInternal(ORIGINID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OriginId.
     * @param value value to set the OriginId
     */
    public void setOriginId(String value) {
        setAttributeInternal(ORIGINID, value);
    }

    /**
     * Gets the attribute value for TerminalId, using the alias name TerminalId.
     * @return the value of TerminalId
     */
    public String getTerminalId() {
        return (String) getAttributeInternal(TERMINALID);
    }

    /**
     * Sets <code>value</code> as the attribute value for TerminalId.
     * @param value value to set the TerminalId
     */
    public void setTerminalId(String value) {
        setAttributeInternal(TERMINALID, value);
    }

    /**
     * Gets the attribute value for PcsshortnameId, using the alias name PcsshortnameId.
     * @return the value of PcsshortnameId
     */
    public String getPcsshortnameId() {
        return (String) getAttributeInternal(PCSSHORTNAMEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PcsshortnameId.
     * @param value value to set the PcsshortnameId
     */
    public void setPcsshortnameId(String value) {
        setAttributeInternal(PCSSHORTNAMEID, value);
    }

    /**
     * Gets the attribute value for Inactive, using the alias name Inactive.
     * @return the value of Inactive
     */
    public String getInactive() {
        return (String) getAttributeInternal(INACTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Inactive.
     * @param value value to set the Inactive
     */
    public void setInactive(String value) {
        setAttributeInternal(INACTIVE, value);
    }

    /**
     * Gets the attribute value for InactiveDate, using the alias name InactiveDate.
     * @return the value of InactiveDate
     */
    public Timestamp getInactiveDate() {
        return (Timestamp) getAttributeInternal(INACTIVEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for InactiveDate.
     * @param value value to set the InactiveDate
     */
    public void setInactiveDate(Timestamp value) {
        setAttributeInternal(INACTIVEDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the value of LastUpdatedDate
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * @return the associated entity XpeDccCfgOgnAssTerminalsEOImpl.
     */
    public XpeDccCfgOgnAssTerminalsEOImpl getXpeDccCfgOgnAssTerminalsEO() {
        return (XpeDccCfgOgnAssTerminalsEOImpl) getAttributeInternal(XPEDCCCFGOGNASSTERMINALSEO);
    }

    /**
     * Sets <code>value</code> as the associated entity XpeDccCfgOgnAssTerminalsEOImpl.
     */
    public void setXpeDccCfgOgnAssTerminalsEO(XpeDccCfgOgnAssTerminalsEOImpl value) {
        setAttributeInternal(XPEDCCCFGOGNASSTERMINALSEO, value);
    }

    /**
     * @param originId key constituent
     * @param terminalId key constituent
     * @param pcsshortnameId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String originId, String terminalId, String pcsshortnameId) {
        return new Key(new Object[] { originId, terminalId, pcsshortnameId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.entities.XpeDccCfgNycDosTermCustEO");
    }
    
    @Override
    protected void doDML(int i, TransactionEvent transactionEvent) {
        // TODO Implement this method
        String userName = "DB_ADMIN";
        ViewObjectImpl userInfoVO = (ViewObjectImpl)this.getDBTransaction().getRootApplicationModule().findViewObject("XpeDccUserInfoROVO");
        Row userInforVORow = userInfoVO.first();
        if(null!=userInforVORow)
            userName = (String)userInforVORow.getAttribute("USER_NAME");
        //INSERT
        if(i==this.DML_INSERT){
            this.setCreatedBy(userName);
            this.setLastUpdatedBy(userName);
        }
        //UPDATE
        if(i==this.DML_UPDATE) 
            this.setLastUpdatedBy(userName);
        
        super.doDML(i, transactionEvent);
    }
}

