package model.entities;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.domain.BlobDomain;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 01 22:59:42 CDT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XpeDccCfgMswFacilityEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        XpeFacilityId,
        CustomerCareReview,
        LegalReview,
        GeneralManagerReview,
        CreatedBy,
        CreationDate,
        LastUpdatedBy,
        LastUpdateDate,
        InactiveDate,
        Inactive,
        GeneralManagerSignature;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int XPEFACILITYID = AttributesEnum.XpeFacilityId.index();
    public static final int CUSTOMERCAREREVIEW = AttributesEnum.CustomerCareReview.index();
    public static final int LEGALREVIEW = AttributesEnum.LegalReview.index();
    public static final int GENERALMANAGERREVIEW = AttributesEnum.GeneralManagerReview.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int INACTIVEDATE = AttributesEnum.InactiveDate.index();
    public static final int INACTIVE = AttributesEnum.Inactive.index();
    public static final int GENERALMANAGERSIGNATURE = AttributesEnum.GeneralManagerSignature.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XpeDccCfgMswFacilityEOImpl() {
    }

    /**
     * Gets the attribute value for XpeFacilityId, using the alias name XpeFacilityId.
     * @return the value of XpeFacilityId
     */
    public String getXpeFacilityId() {
        return (String) getAttributeInternal(XPEFACILITYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for XpeFacilityId.
     * @param value value to set the XpeFacilityId
     */
    public void setXpeFacilityId(String value) {
        setAttributeInternal(XPEFACILITYID, value);
    }

    /**
     * Gets the attribute value for CustomerCareReview, using the alias name CustomerCareReview.
     * @return the value of CustomerCareReview
     */
    public String getCustomerCareReview() {
        return (String) getAttributeInternal(CUSTOMERCAREREVIEW);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustomerCareReview.
     * @param value value to set the CustomerCareReview
     */
    public void setCustomerCareReview(String value) {
        setAttributeInternal(CUSTOMERCAREREVIEW, value);
    }

    /**
     * Gets the attribute value for LegalReview, using the alias name LegalReview.
     * @return the value of LegalReview
     */
    public String getLegalReview() {
        return (String) getAttributeInternal(LEGALREVIEW);
    }

    /**
     * Sets <code>value</code> as the attribute value for LegalReview.
     * @param value value to set the LegalReview
     */
    public void setLegalReview(String value) {
        setAttributeInternal(LEGALREVIEW, value);
    }

    /**
     * Gets the attribute value for GeneralManagerReview, using the alias name GeneralManagerReview.
     * @return the value of GeneralManagerReview
     */
    public String getGeneralManagerReview() {
        return (String) getAttributeInternal(GENERALMANAGERREVIEW);
    }

    /**
     * Sets <code>value</code> as the attribute value for GeneralManagerReview.
     * @param value value to set the GeneralManagerReview
     */
    public void setGeneralManagerReview(String value) {
        setAttributeInternal(GENERALMANAGERREVIEW, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the value of LastUpdateDate
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Gets the attribute value for InactiveDate, using the alias name InactiveDate.
     * @return the value of InactiveDate
     */
    public Timestamp getInactiveDate() {
        return (Timestamp) getAttributeInternal(INACTIVEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for InactiveDate.
     * @param value value to set the InactiveDate
     */
    public void setInactiveDate(Timestamp value) {
        setAttributeInternal(INACTIVEDATE, value);
    }

    /**
     * Gets the attribute value for Inactive, using the alias name Inactive.
     * @return the value of Inactive
     */
    public String getInactive() {
        return (String) getAttributeInternal(INACTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Inactive.
     * @param value value to set the Inactive
     */
    public void setInactive(String value) {
        setAttributeInternal(INACTIVE, value);
    }

    /**
     * Gets the attribute value for GeneralManagerSignature, using the alias name GeneralManagerSignature.
     * @return the value of GeneralManagerSignature
     */
    public BlobDomain getGeneralManagerSignature() {
        return (BlobDomain) getAttributeInternal(GENERALMANAGERSIGNATURE);
    }

    /**
     * Sets <code>value</code> as the attribute value for GeneralManagerSignature.
     * @param value value to set the GeneralManagerSignature
     */
    public void setGeneralManagerSignature(BlobDomain value) {
        setAttributeInternal(GENERALMANAGERSIGNATURE, value);
    }

    /**
     * @param xpeFacilityId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String xpeFacilityId) {
        return new Key(new Object[] { xpeFacilityId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.entities.XpeDccCfgMswFacilityEO");
    }


    @Override
    protected void doDML(int i, TransactionEvent transactionEvent) {
        // TODO Implement this method
        String userName = "DB_ADMIN";
        ViewObjectImpl userInfoVO = (ViewObjectImpl)this.getDBTransaction().getRootApplicationModule().findViewObject("XpeDccUserInfoROVO");
        Row userInforVORow = userInfoVO.first();
        if(null!=userInforVORow)
            userName = (String)userInforVORow.getAttribute("USER_NAME");
        //INSERT
        if(i==this.DML_INSERT){
            this.setCreatedBy(userName);
            this.setLastUpdatedBy(userName);
        }
        //UPDATE
        if(i==this.DML_UPDATE) 
            this.setLastUpdatedBy(userName);
        
        super.doDML(i, transactionEvent);
    }
}

