package model.entities;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 13 00:23:57 EDT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XpeDccCfgPcsshortnamesEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        PcsshortnameId,
        PcsshortName,
        AccountClass,
        Inactive,
        InactiveDate,
        CreatedBy,
        CreatedDate,
        LastUpdatedBy,
        LastUpdatedDate,
        CovId,
        CovSoldId,
        CovBillId,
        CovSoldLocNum,
        CovBillLocNum,
        BillCycleId,
        InvSupress;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PCSSHORTNAMEID = AttributesEnum.PcsshortnameId.index();
    public static final int PCSSHORTNAME = AttributesEnum.PcsshortName.index();
    public static final int ACCOUNTCLASS = AttributesEnum.AccountClass.index();
    public static final int INACTIVE = AttributesEnum.Inactive.index();
    public static final int INACTIVEDATE = AttributesEnum.InactiveDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int COVID = AttributesEnum.CovId.index();
    public static final int COVSOLDID = AttributesEnum.CovSoldId.index();
    public static final int COVBILLID = AttributesEnum.CovBillId.index();
    public static final int COVSOLDLOCNUM = AttributesEnum.CovSoldLocNum.index();
    public static final int COVBILLLOCNUM = AttributesEnum.CovBillLocNum.index();
    public static final int BILLCYCLEID = AttributesEnum.BillCycleId.index();
    public static final int INVSUPRESS = AttributesEnum.InvSupress.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XpeDccCfgPcsshortnamesEOImpl() {
    }

    /**
     * @param pcsshortnameId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String pcsshortnameId) {
        return new Key(new Object[] { pcsshortnameId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.entities.XpeDccCfgPcsshortnamesEO");
    }


    protected String nextVal(String sequenceName) {
        SequenceImpl s = new SequenceImpl(sequenceName, getDBTransaction());
        return "SN"+s.getSequenceNumber().toString();
    }
}

