package model.entities;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 07 23:48:07 CST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XpeDccCfgMtlIndicesHeaderEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        XpeIndexChangeId,
        XpeMtlIndexName,
        CreatedBy,
        CreationDate,
        LastUpdatedBy,
        LastUpdateDate,
        XpeDccCfgMtlIndicesDetailEO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int XPEINDEXCHANGEID = AttributesEnum.XpeIndexChangeId.index();
    public static final int XPEMTLINDEXNAME = AttributesEnum.XpeMtlIndexName.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int XPEDCCCFGMTLINDICESDETAILEO = AttributesEnum.XpeDccCfgMtlIndicesDetailEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XpeDccCfgMtlIndicesHeaderEOImpl() {
    }

    /**
     * Gets the attribute value for XpeIndexChangeId, using the alias name XpeIndexChangeId.
     * @return the value of XpeIndexChangeId
     */
    public BigDecimal getXpeIndexChangeId() {
        return (BigDecimal) getAttributeInternal(XPEINDEXCHANGEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for XpeIndexChangeId.
     * @param value value to set the XpeIndexChangeId
     */
    public void setXpeIndexChangeId(BigDecimal value) {
        setAttributeInternal(XPEINDEXCHANGEID, value);
    }

    /**
     * Gets the attribute value for XpeMtlIndexName, using the alias name XpeMtlIndexName.
     * @return the value of XpeMtlIndexName
     */
    public String getXpeMtlIndexName() {
        return (String) getAttributeInternal(XPEMTLINDEXNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for XpeMtlIndexName.
     * @param value value to set the XpeMtlIndexName
     */
    public void setXpeMtlIndexName(String value) {
        setAttributeInternal(XPEMTLINDEXNAME, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the value of LastUpdateDate
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getXpeDccCfgMtlIndicesDetailEO() {
        return (RowIterator) getAttributeInternal(XPEDCCCFGMTLINDICESDETAILEO);
    }

    /**
     * @param xpeIndexChangeId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal xpeIndexChangeId) {
        return new Key(new Object[] { xpeIndexChangeId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.entities.XpeDccCfgMtlIndicesHeaderEO");
    }
    
    @Override
    protected void doDML(int i, TransactionEvent transactionEvent) {
        // TODO Implement this method
        String userName = "DB_ADMIN";
        ViewObjectImpl userInfoVO = (ViewObjectImpl)this.getDBTransaction().getRootApplicationModule().findViewObject("XpeDccUserInfoROVO");
        Row userInforVORow = userInfoVO.first();
        if(null!=userInforVORow)
            userName = (String)userInforVORow.getAttribute("USER_NAME");
        //INSERT
        if(i==this.DML_INSERT) 
            this.setCreatedBy(userName);
        //UPDATE
        if(i==this.DML_UPDATE) 
            this.setLastUpdatedBy(userName);
        
        super.doDML(i, transactionEvent);
    }
}

