package model.entities;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 07 22:13:20 EDT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XpeDmsCustomerEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        CustId,
        SetId,
        CompanyName,
        BillingAddress1,
        BillingAddress2,
        City,
        State,
        Country,
        Postal,
        MailingAddress1,
        MailingAddress2,
        MailingCity,
        MailingState,
        MailingCountry,
        MailingPostal,
        Email,
        PhoneNum,
        ContactType,
        ContactName,
        Title,
        BusinessType;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int CUSTID = AttributesEnum.CustId.index();
    public static final int SETID = AttributesEnum.SetId.index();
    public static final int COMPANYNAME = AttributesEnum.CompanyName.index();
    public static final int BILLINGADDRESS1 = AttributesEnum.BillingAddress1.index();
    public static final int BILLINGADDRESS2 = AttributesEnum.BillingAddress2.index();
    public static final int CITY = AttributesEnum.City.index();
    public static final int STATE = AttributesEnum.State.index();
    public static final int COUNTRY = AttributesEnum.Country.index();
    public static final int POSTAL = AttributesEnum.Postal.index();
    public static final int MAILINGADDRESS1 = AttributesEnum.MailingAddress1.index();
    public static final int MAILINGADDRESS2 = AttributesEnum.MailingAddress2.index();
    public static final int MAILINGCITY = AttributesEnum.MailingCity.index();
    public static final int MAILINGSTATE = AttributesEnum.MailingState.index();
    public static final int MAILINGCOUNTRY = AttributesEnum.MailingCountry.index();
    public static final int MAILINGPOSTAL = AttributesEnum.MailingPostal.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int PHONENUM = AttributesEnum.PhoneNum.index();
    public static final int CONTACTTYPE = AttributesEnum.ContactType.index();
    public static final int CONTACTNAME = AttributesEnum.ContactName.index();
    public static final int TITLE = AttributesEnum.Title.index();
    public static final int BUSINESSTYPE = AttributesEnum.BusinessType.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XpeDmsCustomerEOImpl() {
    }

    /**
     * @param custId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String custId) {
        return new Key(new Object[] { custId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.entities.XpeDmsCustomerEO");
    }
    
    protected String nextVal(String sequenceName) {
        SequenceImpl s = new SequenceImpl(sequenceName, getDBTransaction());
        return "TMP"+s.getSequenceNumber().toString();
    }
}

